// Package main checks that every supported installation channel installed the
// same release.
//
// Nise is installable three ways — a release archive from GitHub Releases,
// `go install github.com/drilonrecica/nise-and-go/cmd/nise@vX.Y.Z`, and the
// official Homebrew tap — across up to three operating systems each. The
// loud failure is a channel that does not work. The quiet one, and the reason
// this command exists, is two channels that both work and disagree.
//
// They can. An archive binary is stamped by the release build's -ldflags. A
// `go install` binary is compiled on the installing machine from a module zip
// and reads its version out of runtime/debug.BuildInfo. Homebrew installs the
// archive, but through a formula generated by a separate workflow that could
// point at the wrong release. Three independent paths to one version string,
// and nothing but this comparison makes them agree.
//
// It matters past tidiness: `nise new` writes the running binary's version
// into the project recipe verbatim, and `nise doctor` compares it against the
// running binary later. Two channels that name one release differently make
// the same release generate two different project trees.
//
// The input is the per-channel output of `nise --json version`, collected by
// .github/workflows/install-channels.yml. This command performs no
// installation and touches no network; it reads files and compares them.
package main

import (
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
)

// channels are the installation paths this project supports, and the runners
// each one is exercised on. They are written out rather than discovered from
// the report directory, because a channel whose job failed produces no report
// — and a comparison that only compares what turned up would pass loudest
// when the most was broken.
var channels = []struct {
	name string
	// runners the channel is installed on. Homebrew has no Windows.
	runners []string
	// stamped reports whether this channel's binary can carry the commit and
	// build date. A `go install` binary cannot: it is built from a module
	// zip, which carries no VCS metadata at all, so the Go toolchain has
	// nothing to record. That is a property of the channel, not a defect, and
	// it is written down here rather than quietly tolerated.
	stamped bool
}{
	{"archive", []string{"ubuntu-latest", "macos-latest", "windows-latest"}, true},
	{"go-install", []string{"ubuntu-latest", "macos-latest", "windows-latest"}, false},
	{"homebrew", []string{"ubuntu-latest", "macos-latest"}, true},
}

// releaseTag accepts a release tag, prereleases included.
var releaseTag = regexp.MustCompile(`^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(-[0-9A-Za-z.-]+)?$`)

// reportName is the file each channel job uploads.
const reportName = "channel.json"

// report is `nise --json version`, which is internal/version.Info.
type report struct {
	Version string `json:"version"`
	Commit  string `json:"commit"`
	Date    string `json:"date"`
}

func main() {
	os.Exit(run(os.Args[1:], os.Stdout, os.Stderr))
}

func run(args []string, stdout, stderr io.Writer) int {
	fs := flag.NewFlagSet("channel-agreement", flag.ContinueOnError)
	fs.SetOutput(stderr)
	tag := fs.String("tag", "", "release tag every channel was asked to install, e.g. v0.1.0")
	dir := fs.String("dir", "", "directory of downloaded per-channel report artifacts")
	if err := fs.Parse(args); err != nil {
		return 2
	}

	problems, err := compare(*tag, *dir)
	if err != nil {
		_, _ = fmt.Fprintf(stderr, "channel-agreement: %v\n", err)
		return 2
	}
	if len(problems) > 0 {
		for _, p := range problems {
			_, _ = fmt.Fprintf(stdout, "channel-agreement: %s\n", p)
		}
		_, _ = fmt.Fprintf(stdout, "channel-agreement: the channels do not agree on %s (%s)\n", *tag, count(len(problems)))
		return 1
	}
	_, _ = fmt.Fprintf(stdout, "channel-agreement: every channel installed %s and reports it identically\n", *tag)
	return 0
}

func count(n int) string {
	if n == 1 {
		return "1 problem"
	}
	return fmt.Sprintf("%d problems", n)
}

func compare(tag, dir string) ([]string, error) {
	if tag == "" || dir == "" {
		return nil, errors.New("-tag and -dir are both required")
	}
	if !releaseTag.MatchString(tag) {
		return nil, fmt.Errorf("tag %q is not a release tag of the form vMAJOR.MINOR.PATCH[-prerelease]", tag)
	}
	if _, err := os.Stat(dir); err != nil {
		return nil, fmt.Errorf("reading the report directory: %w", err)
	}

	var problems []string
	// stampedSeen collects the commit reported by the channels that can carry
	// one, so they can be compared against each other as well as against the
	// tag.
	stamped := map[string]string{}

	for _, channel := range channels {
		for _, runner := range channel.runners {
			label := channel.name + " on " + runner
			path := filepath.Join(dir, "channel-"+channel.name+"-"+runner, reportName)

			got, err := readReport(path)
			if errors.Is(err, os.ErrNotExist) {
				// The job failed, was cancelled, or never ran. Silence here
				// would mean this command passes most loudly when the most is
				// broken.
				problems = append(problems, fmt.Sprintf("%s reported nothing; that channel did not install", label))
				continue
			}
			if err != nil {
				problems = append(problems, fmt.Sprintf("%s: %v", label, err))
				continue
			}

			if got.Version != tag {
				problems = append(problems, fmt.Sprintf("%s installed %q, and the release is %s", label, got.Version, tag))
			}
			if !channel.stamped {
				// Nothing more to check: this channel has no VCS metadata to
				// report, by construction.
				continue
			}
			if got.Commit == "" {
				problems = append(problems, fmt.Sprintf("%s reports no commit, and a channel that installs the release archive carries one", label))
				continue
			}
			if got.Date == "" {
				problems = append(problems, fmt.Sprintf("%s reports no build date, and a channel that installs the release archive carries one", label))
			}
			stamped[label] = got.Commit
		}
	}

	return append(problems, disagreeingCommits(stamped)...), nil
}

// disagreeingCommits reports channels that installed archives built from
// different commits. Every archive-installing channel serves the same six
// files, so two different commits mean one of them is serving something else
// — a stale Homebrew formula pointing at the previous release is the way this
// actually happens, and it is invisible from any single channel.
func disagreeingCommits(stamped map[string]string) []string {
	if len(stamped) < 2 {
		return nil
	}
	labels := make([]string, 0, len(stamped))
	for label := range stamped {
		labels = append(labels, label)
	}
	sort.Strings(labels)

	first := labels[0]
	var problems []string
	for _, label := range labels[1:] {
		if stamped[label] != stamped[first] {
			problems = append(problems, fmt.Sprintf(
				"%s installed a binary built from %s, and %s installed one built from %s",
				label, short(stamped[label]), first, short(stamped[first])))
		}
	}
	return problems
}

func short(commit string) string {
	if len(commit) > 12 {
		return commit[:12]
	}
	return commit
}

func readReport(path string) (report, error) {
	data, err := os.ReadFile(path) // #nosec G304 -- reading the directory the operator named is what the command is.
	if err != nil {
		return report{}, err
	}
	var got report
	if err := json.Unmarshal(data, &got); err != nil {
		return report{}, fmt.Errorf("%s is not the JSON `nise --json version` writes: %w", reportName, err)
	}
	if strings.TrimSpace(got.Version) == "" {
		return report{}, fmt.Errorf("%s names no version", reportName)
	}
	return got, nil
}
