# Generated by cmd/homebrew-formula in github.com/drilonrecica/nise-and-go from the
# checksums.txt of release v0.1.0. This file is owned by the release
# automation: every published release regenerates it completely. Do not edit
# by hand — change the generator instead.
class Nise < Formula
  desc "Opinionated application foundation for Go, chi, PostgreSQL, and SvelteKit"
  homepage "https://github.com/drilonrecica/nise-and-go"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/drilonrecica/nise-and-go/releases/download/v0.1.0/nise_0.1.0_darwin_amd64.tar.gz"
      sha256 "8bf2769743fc36c27dbe7645eacb185f8df0c51adf3675ab25c1c011202e22d9"
    end

    on_arm do
      url "https://github.com/drilonrecica/nise-and-go/releases/download/v0.1.0/nise_0.1.0_darwin_arm64.tar.gz"
      sha256 "54777fdd0ce6a6d22166d5431fc4a14a34ee1e9bda0c93479611aefebf0a5c42"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/drilonrecica/nise-and-go/releases/download/v0.1.0/nise_0.1.0_linux_amd64.tar.gz"
      sha256 "e71607ccd55b0316177e7fbf9a546964638842c5f14fda010d5b04824bf5ab34"
    end

    on_arm do
      url "https://github.com/drilonrecica/nise-and-go/releases/download/v0.1.0/nise_0.1.0_linux_arm64.tar.gz"
      sha256 "110f49fb547bf43e3f74ee7150756ad8ea72033a0eb74229ce06a8f1aea664ee"
    end
  end

  def install
    bin.install "nise"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nise --version")
  end
end
