// Package runtime documents the public Go surface of Nise & Go. It declares no
// identifiers and is not meant to be imported: the surface is its subpackages.
//
// Applications generated by the nise CLI import these packages and nothing else
// from this module. Everything outside runtime — cmd, internal, templates, test
// and examples — is private and may change in any release.
//
//   - runtime/config        typed environment configuration, _FILE secret
//     variants, and fail-closed production validation
//   - runtime/logging       structured JSON and human-readable logs over
//     log/slog, request and correlation IDs, and central redaction
//   - runtime/health        startup, liveness, and readiness checks and handlers
//   - runtime/lifecycle     the all, web, and worker process modes, HTTP server
//     construction, graceful shutdown, and bounded draining
//   - runtime/observability HTTP, database-pool, and job metrics, and the
//     optional tracing interface
//   - runtime/secure        security headers and Content Security Policy
//   - runtime/transaction   driver-independent use-case transaction lifecycle,
//     rollback bounds, and closed isolation/access options
//   - runtime/pagination    authenticated versioned cursor tokens, key
//     rotation, cursor request parsing, and the separate offset reporting
//     contract
//   - runtime/forwarded     trusted-proxy policy, and the real client address,
//     scheme, and host behind it
//   - runtime/password      Argon2id hashing, versioned parameter sets,
//     rehash detection, and parameter benchmarking
//   - runtime/session       opaque session tokens, their stored digests, the
//     idle, absolute, and revoked lifecycle rules, and the browser cookie
//     policy
//
// The name runtime/internal is reserved for shared implementation. No such
// package exists yet: every package above compiles against the standard library
// alone, except runtime/password, which uses golang.org/x/crypto/argon2 because
// Argon2id is not in the standard library. If one is added, the Go toolchain makes it invisible to applications,
// and it will carry no compatibility promise.
//
// # Boundaries
//
// A runtime package may import the standard library, golang.org/x/crypto for
// the one algorithm named above, and, should one ever exist, runtime/internal. It may import another runtime package only along an edge
// named in ADR 0011;
// today that is lifecycle depending on config, logging, and health. No runtime
// package imports internal, cmd, templates, test, or examples.
//
// net/http middleware lives in the package that owns the concern it implements.
// There is no middleware aggregator here: the ordered chain is generated
// application code, where an application can read the order and insert its own
// handlers.
//
// Nothing in runtime performs a network request, checks for updates, emits
// telemetry, holds global mutable state, registers anything in an init
// function, or resolves a dependency by reflection.
//
// # Stability
//
// Version 0.x is explicitly unstable. Breaking changes are permitted in any 0.x
// release and ship with a changelog entry and migration notes. From 1.0,
// documented exported identifiers in runtime follow semantic versioning;
// generator internals never do.
//
// Every exported identifier here carries a doc comment. Adding, removing, or
// retyping one is a contract change: it requires that doc comment, an update to
// docs/runtime-packages.md, and an explicit line in the commit message saying
// what the surface gained or lost.
package runtime
