// Package config provides typed configuration loading for applications
// generated by Nise: reading values from the process environment, resolving
// secrets through file indirection, and validating that a production
// configuration is safe before the process starts serving traffic.
//
// # Design: explicit combinators, not struct tags
//
// This package uses a small explicit combinator API — [Loader.String],
// [Loader.Int], [Loader.Bool], [Loader.Duration], [Loader.Secret], and
// [Loader.Environment] — rather than a struct-tag decoder driven by
// reflection. An application builds its configuration struct field by field:
//
//	l := config.NewLoader()
//	cfg := AppConfig{
//	    Env:      l.Environment("APP_ENV", config.Default("development")),
//	    Port:     l.String("PORT", config.Default("8080")),
//	    Debug:    l.Bool("DEBUG", config.Default("false")),
//	    DBPassword: l.Secret("DB_PASSWORD"),
//	}
//	if err := l.Err(); err != nil {
//	    return AppConfig{}, err
//	}
//
// A struct-tag decoder was considered and rejected in favor of this. Both
// designs can express the same fields, but the combinator API uses zero
// reflection: it cannot silently misparse an unknown or malformed tag, every
// field's source and default are visible at the call site rather than
// hidden in a tag string, and each combinator function is trivially
// unit-testable in isolation. The cost is one line of code per field instead
// of one struct tag per field; for the number of settings a generated
// application has, that cost is small and the removal of reflection-driven
// behavior discovery is worth it, consistent with this project's "no magic"
// constraint.
//
// # Source precedence
//
// Every value has at most three possible sources, consulted in this order:
//
//  1. The explicit process environment variable (`FOO`).
//  2. For fields loaded with [Loader.Secret] only: file indirection
//     (`FOO_FILE`), naming a file whose contents are the value.
//  3. The compiled-in default passed via the [Default] option, if any.
//
// If neither the environment variable nor a default is available, loading
// that field fails. If both `FOO` and `FOO_FILE` are set at once, that is
// always an error, never a silent preference for one over the other: an
// operator who sets both almost certainly intended to change one and forgot
// to remove the other, and guessing which one they meant is exactly the kind
// of silent behavior this package exists to avoid.
//
// This package never reads `.env` files. Loading a `.env` file is a local
// development convenience, owned by `nise dev`, not a production runtime
// behavior; loading one here would make the runtime's behavior depend on
// which files happen to exist next to the binary.
//
// # Secrets
//
// [Secret] wraps any sensitive configuration value — a password, API key, or
// connection-string credential. It is unprintable through every formatting
// path Go offers ([fmt.Stringer], [fmt.GoStringer], [json.Marshaler],
// [encoding.TextMarshaler], and [log/slog.LogValuer]); the only way to read
// the underlying value is the explicit [Secret.Reveal] method. [Loader.Secret]
// loads a Secret field with the same environment-variable precedence as
// other fields, plus `FOO_FILE` support: the named file is read, exactly one
// trailing newline (`\n` or `\r\n`) is stripped, and the file must not be
// missing, unreadable, a directory, empty, or larger than
// [MaxSecretFileSize]. A file that is readable by group or other on Unix
// produces a warning (retrievable from [Loader.Warnings]), not a load
// failure — an operator should fix it, but a wrong file permission is not
// itself proof the secret has leaked, so refusing to start over it would be
// disproportionate.
//
// # Environment
//
// [Environment] is a closed, typed enum: [Development], [Test], and
// [Production]. [ParseEnvironment] rejects any other value as an error
// rather than silently defaulting to either Development or Production.
// Defaulting to Development on an unrecognized value could start a
// misconfigured deployment with production's safety checks disabled;
// defaulting to Production could impose production-only requirements (for
// example a required secret that a real Production deployment relies on but
// that a merely-misspelled environment name never intended to satisfy) on a
// deployment nobody meant to be production. Neither guess is safe, so an
// unrecognized value refuses to start instead, consistent with this
// project's fail-closed constraint.
//
// # Production validation
//
// [Validate] runs a caller-supplied set of checks only when the environment
// is [Production], and it runs all of them before returning: a startup
// failure lists every violation at once, not just the first one found, so an
// operator does not have to restart the container repeatedly to discover
// problems one at a time. [Validator.Check] and [Validator.RequireSecretSet]
// record violations without ever including a secret's value; every message
// names the offending variable, states what is wrong, and says what to do.
package config
