package cli

import (
	"bytes"
	"encoding/json"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/drilonrecica/nise-and-go/internal/check"
	"github.com/drilonrecica/nise-and-go/internal/cli/clierr"
	"github.com/drilonrecica/nise-and-go/internal/generator"
	"github.com/drilonrecica/nise-and-go/internal/version"
)

func TestInvariantCheckResultHumanRendering(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		c    check.Check
		want string
	}{
		{
			name: "a passing check states its invariant and what it saw",
			c: check.Check{
				Name: "recipe", Status: check.StatusOK,
				Invariant: "The project declares a recipe this build understands.",
				Detail:    "nise.json: schemaVersion 1",
			},
			want: "[OK] recipe\n" +
				"    invariant: The project declares a recipe this build understands.\n" +
				"    detail:    nise.json: schemaVersion 1",
		},
		{
			name: "a failing check lists its paths and its remedy",
			c: check.Check{
				Name: "generation-deterministic", Status: check.StatusFail,
				Invariant: "Regenerating reproduces nise-owned files byte for byte.",
				Detail:    "1 of 6 differ",
				Remedy:    "Restore the listed files from version control.",
				Paths:     []string{"internal/app/modules.gen.go"},
			},
			want: "[FAIL] generation-deterministic\n" +
				"    invariant: Regenerating reproduces nise-owned files byte for byte.\n" +
				"    detail:    1 of 6 differ\n" +
				"    path:      internal/app/modules.gen.go\n" +
				"    remedy:    Restore the listed files from version control.",
		},
		{
			name: "a skipped check still states what went unverified",
			c: check.Check{
				Name: "migrations", Status: check.StatusSkipped,
				Invariant: "Migrations are ordered and forward-only.",
				Detail:    "no migration subsystem yet (milestone M3)",
			},
			want: "[SKIPPED] migrations\n" +
				"    invariant: Migrations are ordered and forward-only.\n" +
				"    detail:    no migration subsystem yet (milestone M3)",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if got := (invariantCheckResult{tt.c}).Human(); got != tt.want {
				t.Errorf("Human() =\n%s\nwant\n%s", got, tt.want)
			}
		})
	}
}

// runCheckFixture dispatches the real checkCommand from inside dir.
func runCheckFixture(t *testing.T, dir string, args []string) (code int, stdout, stderr string) {
	t.Helper()

	t.Chdir(dir)
	var out, errOut bytes.Buffer
	code = execute(args, IO{Stdout: &out, Stderr: &errOut, Getenv: emptyGetenv}, []*Command{checkCommand()})
	return code, out.String(), errOut.String()
}

// generatedProject writes a real project into a temporary directory. The CLI
// tests run against genuinely generated output for the same reason
// internal/check's do: a hand-built fixture would be a second copy of what
// `nise new` writes, and these checks exist to notice when two copies
// disagree.
//
// The recipe records this test binary's own version rather than a pinned
// literal, because checkCommand reads the running version from
// internal/version and cannot be told otherwise. A pinned literal would make
// the fixture look like a project generated by a different nise, and the
// regeneration check would correctly downgrade itself to a skip — leaving
// the exit-code tests below asserting a code the command would never reach
// in the situation they claim to describe.
func generatedProject(t *testing.T) string {
	t.Helper()

	root := filepath.Join(t.TempDir(), "myapp")
	if _, err := generator.Write(root, generator.Options{
		Name:       "myapp",
		ModulePath: "github.com/example/myapp",
		CLIVersion: version.Get().Version,
	}); err != nil {
		t.Fatalf("generating the fixture project: %v", err)
	}
	return root
}

// TestCheckOutsideAProjectIsAPrecondition covers the deliberate refusal to
// report nine skips and exit 0 outside a project: a green result that
// verified nothing is the dishonest pass this command exists to prevent.
func TestCheckOutsideAProjectIsAPrecondition(t *testing.T) {
	code, _, stderr := runCheckFixture(t, t.TempDir(), []string{"check"})

	if code != int(clierr.ExitPrecondition) {
		t.Errorf("exit code = %d, want %d (precondition)", code, clierr.ExitPrecondition)
	}
	if !strings.Contains(stderr, "nise.json") {
		t.Errorf("stderr = %q, want it to name the file that was not found", stderr)
	}
}

// TestCheckInAFreshProjectExitsZero is the first-context case at the CLI
// level: `nise new` followed by `nise check` must be green.
func TestCheckInAFreshProjectExitsZero(t *testing.T) {
	code, stdout, stderr := runCheckFixture(t, generatedProject(t), []string{"check"})

	if code != int(clierr.ExitOK) {
		t.Errorf("exit code = %d, want 0; stdout=%s stderr=%s", code, stdout, stderr)
	}
	for _, name := range []string{
		check.CheckRecipe, check.CheckCLIVersion, check.CheckRuntimeVersion,
		check.CheckOwnershipHeaders, check.CheckOwnershipContent, check.CheckGeneration,
		check.CheckMigrations, check.CheckConfig, check.CheckSecrets,
	} {
		if !strings.Contains(stdout, "] "+name) {
			t.Errorf("stdout is missing check %q; stdout=%s", name, stdout)
		}
	}
	if !strings.Contains(stdout, "0 fail") {
		t.Errorf("stdout does not report a summary line with no failures; stdout=%s", stdout)
	}
}

// TestCheckRunsFromASubdirectory covers the project-root convention end to
// end: a developer deep in the tree gets the same answer.
func TestCheckRunsFromASubdirectory(t *testing.T) {
	root := generatedProject(t)

	code, stdout, stderr := runCheckFixture(t, filepath.Join(root, "internal", "app"), []string{"check"})
	if code != int(clierr.ExitOK) {
		t.Errorf("exit code = %d, want 0; stdout=%s stderr=%s", code, stdout, stderr)
	}
}

// TestCheckFailsAndExitsNonZeroOnAHandEditedFile is the exit-code contract's
// other half. A CI job gates on this number.
func TestCheckFailsAndExitsNonZeroOnAHandEditedFile(t *testing.T) {
	root := generatedProject(t)
	appendTo(t, filepath.Join(root, "internal", "app", "modules.gen.go"), "\n// edited by hand\n")

	code, stdout, stderr := runCheckFixture(t, root, []string{"check"})
	if code != int(clierr.ExitError) {
		t.Errorf("exit code = %d, want %d; stdout=%s stderr=%s", code, clierr.ExitError, stdout, stderr)
	}
	if !strings.Contains(stdout, "[FAIL] "+check.CheckGeneration) {
		t.Errorf("stdout does not report the regeneration check as failed; stdout=%s", stdout)
	}
	if !strings.Contains(stderr, "invariant") {
		t.Errorf("stderr = %q, want it to say what did not hold", stderr)
	}
}

// TestCheckJSONModeIsValidNDJSON proves --json emits exactly what
// docs/cli-output.md promises: one JSON document per line, all on stdout,
// nothing on stderr, and one document per check plus the error envelope.
func TestCheckJSONModeIsValidNDJSON(t *testing.T) {
	root := generatedProject(t)
	appendTo(t, filepath.Join(root, "internal", "app", "modules.gen.go"), "\n// edited by hand\n")

	code, stdout, stderr := runCheckFixture(t, root, []string{"check", "--json"})

	if stderr != "" {
		t.Errorf("stderr = %q, want empty: JSON mode keeps everything, errors included, on stdout", stderr)
	}
	if code != int(clierr.ExitError) {
		t.Errorf("exit code = %d, want %d", code, clierr.ExitError)
	}

	lines := strings.Split(strings.TrimRight(stdout, "\n"), "\n")
	seen := map[string]string{}
	sawError := false
	for i, line := range lines {
		var probe map[string]json.RawMessage
		if err := json.Unmarshal([]byte(line), &probe); err != nil {
			t.Fatalf("line %d is not valid JSON: %v\nline: %s", i, err, line)
		}
		if _, isErr := probe["error"]; isErr {
			sawError = true
			continue
		}
		var c struct {
			Name      string `json:"name"`
			Status    string `json:"status"`
			Invariant string `json:"invariant"`
			Detail    string `json:"detail"`
		}
		if err := json.Unmarshal([]byte(line), &c); err != nil {
			t.Fatalf("line %d did not decode as a check document: %v", i, err)
		}
		if c.Name == "" || c.Status == "" || c.Invariant == "" || c.Detail == "" {
			t.Errorf("line %d is missing a required field of the stable schema: %s", i, line)
		}
		seen[c.Name] = c.Status
	}

	if !sawError {
		t.Error("a failing run emitted no error envelope")
	}
	if got := seen[check.CheckGeneration]; got != string(check.StatusFail) {
		t.Errorf("%s reported status %q, want %q", check.CheckGeneration, got, check.StatusFail)
	}
}

// TestCheckFixErrorsHonestly pins the one thing --fix must do in this slice.
// A flag that silently did nothing — or worse, edited files — would be the
// least recoverable kind of surprise.
func TestCheckFixErrorsHonestly(t *testing.T) {
	root := generatedProject(t)
	before := treeDigest(t, root)

	code, _, stderr := runCheckFixture(t, root, []string{"check", "--fix"})

	if code == int(clierr.ExitOK) {
		t.Error("nise check --fix exited 0, which claims a repair that did not happen")
	}
	if !strings.Contains(stderr, "not implemented") {
		t.Errorf("stderr = %q, want it to say --fix is not implemented", stderr)
	}
	if after := treeDigest(t, root); after != before {
		t.Error("nise check --fix modified the project")
	}
}

// TestCheckWithAnEnvFileValidatesIt covers the flag that turns the
// configuration check from a skip into a real verification.
func TestCheckWithAnEnvFileValidatesIt(t *testing.T) {
	root := generatedProject(t)

	code, stdout, _ := runCheckFixture(t, root, []string{"check", "--env-file", ".env.example"})
	if code != int(clierr.ExitOK) {
		t.Errorf("exit code = %d, want 0; stdout=%s", code, stdout)
	}
	if !strings.Contains(stdout, "[OK] "+check.CheckConfig) {
		t.Errorf("the configuration check did not run against the supplied file; stdout=%s", stdout)
	}
}

// appendTo appends to a file inside a fixture project, standing in for a
// developer editing a generated file by hand.
func appendTo(t *testing.T, path, extra string) {
	t.Helper()

	data, err := os.ReadFile(path) // #nosec G304 -- a path this test built under its own t.TempDir().
	if err != nil {
		t.Fatalf("reading %s: %v", path, err)
	}
	// #nosec G703 -- path is built by this test under its own t.TempDir();
	// nothing in it comes from outside the test process.
	if err := os.WriteFile(path, append(data, extra...), 0o600); err != nil {
		t.Fatalf("writing %s: %v", path, err)
	}
}

// treeDigest renders a tree as a stable "path\0content" listing, so a test
// can assert that a command changed nothing.
//
// Paths are collected during the walk and read afterwards, so no filesystem
// operation happens inside the walk callback — the same shape
// internal/generator's own treeManifest uses.
func treeDigest(t *testing.T, root string) string {
	t.Helper()

	var paths []string
	if err := filepath.WalkDir(root, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if !d.IsDir() {
			paths = append(paths, p)
		}
		return nil
	}); err != nil {
		t.Fatalf("walking %s: %v", root, err)
	}
	slices.Sort(paths)

	var b strings.Builder
	for _, p := range paths {
		rel, err := filepath.Rel(root, p)
		if err != nil {
			t.Fatalf("relativizing %s: %v", p, err)
		}
		data, err := os.ReadFile(p) // #nosec G304 -- a path from walking a directory this test created.
		if err != nil {
			t.Fatalf("reading %s: %v", p, err)
		}
		b.WriteString(filepath.ToSlash(rel))
		b.WriteByte(0)
		b.Write(data)
		b.WriteByte(0)
	}
	return b.String()
}
