package check

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"github.com/drilonrecica/nise-and-go/internal/doctor"
	"github.com/drilonrecica/nise-and-go/internal/generator"
	"github.com/drilonrecica/nise-and-go/internal/recipe"
)

const invariantGeneration = "Regenerating this project's nise-owned files reproduces them byte for byte (ADR 0002)."

// checkGeneration regenerates the whole project into a temporary directory
// and compares every Nise-owned file against what is on disk.
//
// # Why the whole tree is written, not just compared in memory
//
// The plan is already in memory, so a byte comparison could be done without
// touching a filesystem at all. It is written out anyway because the
// invariant is about generation, not about rendering: path separators,
// directory creation, and the write itself are all part of what has to be
// reproducible, and an in-memory comparison would pass while a real
// regeneration produced a different tree. The temporary directory is removed
// before this function returns, and the project itself is never written to.
//
// # Why a version mismatch downgrades this to a skip
//
// This is the check with the sharpest wrong-remedy hazard in the whole
// command. A difference between what is on disk and what today's nise
// renders has two possible causes that this check cannot tell apart:
// somebody edited a Nise-owned file, or the project was generated by a
// different nise whose templates have since changed. Only the first is an
// invariant violation, and only the first has "restore the file" as its
// remedy — telling a developer who simply upgraded their CLI that they
// hand-edited a file, and to throw their file away, is a wrong remedy of
// exactly the kind `nise doctor` shipped once and had to withdraw.
//
// So when the running nise is not the nise recorded in the recipe, the
// comparison still runs and its findings are still reported — they are real
// information — but as a skip with the honest reason, not as a failure with
// a remedy that might be wrong. Hand edits are not thereby unguarded: the
// two ownership checks catch them independently of version, one from the
// header and one from the embedded content hash.
func checkGeneration(root string, r *recipe.Recipe, plan []generator.File, running string) Check {
	if r == nil {
		return skip(CheckGeneration, invariantGeneration,
			"no valid recipe, so there is nothing to regenerate from; see the \""+CheckRecipe+"\" check")
	}
	if plan == nil {
		return skip(CheckGeneration, invariantGeneration,
			"the recipe did not produce a generation plan, so there is nothing to compare against")
	}

	scratch, err := os.MkdirTemp("", "nise-check-generate-")
	if err != nil {
		return skip(CheckGeneration, invariantGeneration,
			fmt.Sprintf("could not create a temporary directory to regenerate into (%s)", err))
	}
	defer func() { _ = os.RemoveAll(scratch) }()

	target := filepath.Join(scratch, "regenerated")
	if _, err := generator.Write(target, generator.Options{
		Name:           projectName(root),
		ModulePath:     projectModulePath(root),
		Profile:        r.Profile,
		Modules:        r.Modules,
		CLIVersion:     r.CLIVersion,
		RuntimeVersion: r.RuntimeVersion,
	}); err != nil {
		return skip(CheckGeneration, invariantGeneration,
			fmt.Sprintf("regeneration into a temporary directory failed (%s), so there is nothing to compare against", err))
	}

	owned := 0
	var differing []string
	var details []string
	for _, f := range plan {
		if f.Owner != generator.OwnerNise {
			continue
		}
		owned++

		want, wantErr := os.ReadFile(filepath.Join(target, filepath.FromSlash(f.Path))) // #nosec G304 -- a path this call just wrote into its own temporary directory.
		if wantErr != nil {
			return skip(CheckGeneration, invariantGeneration,
				fmt.Sprintf("could not read the regenerated %s (%s)", f.Path, wantErr))
		}
		got, gotErr := os.ReadFile(filepath.Join(root, filepath.FromSlash(f.Path))) // #nosec G304 -- the project root joined with a path from the generator's own template manifest.
		if gotErr != nil {
			differing = append(differing, f.Path)
			details = append(details, fmt.Sprintf("%s could not be read (%s)", f.Path, gotErr))
			continue
		}
		if !bytes.Equal(got, want) {
			differing = append(differing, f.Path)
			details = append(details, fmt.Sprintf("%s differs from what nise generates (%s)", f.Path, describeDiff(got, want)))
		}
	}
	slices.Sort(differing)

	sameCLI := sameGeneratingCLI(running, r.CLIVersion)
	switch {
	case len(differing) == 0 && sameCLI:
		return pass(CheckGeneration, invariantGeneration, fmt.Sprintf(
			"all %d nise-owned file(s) regenerate byte for byte with nise %s, the nise that generated this project", owned, running))

	case len(differing) == 0:
		return pass(CheckGeneration, invariantGeneration, fmt.Sprintf(
			"all %d nise-owned file(s) regenerate byte for byte, even though this nise (%s) is not the one that generated the project (%s)",
			owned, running, r.CLIVersion))

	case sameCLI:
		c := fail(CheckGeneration, invariantGeneration,
			fmt.Sprintf("%d of %d nise-owned file(s) do not match what nise %s generates: %s",
				len(differing), owned, running, strings.Join(details, "; ")),
			`Restore the listed files from version control. They are nise-owned: any edit to them is lost the next time nise regenerates them, so the edit belongs in an application-owned file instead. "nise agents --force" regenerates AGENTS.md and .nise/architecture.json.`,
		)
		c.Paths = differing
		return c

	default:
		c := skip(CheckGeneration, invariantGeneration,
			fmt.Sprintf("this nise (%s) is not the nise that generated this project (%s), so a difference cannot be told apart from a template change between the two versions; regenerating anyway differs in %d of %d nise-owned file(s): %s",
				running, r.CLIVersion, len(differing), owned, strings.Join(details, "; ")))
		c.Remedy = fmt.Sprintf(
			"Re-run this check with nise %s to get a conclusive answer. The \"%s\" and \"%s\" checks above already cover hand edits independently of which nise generated the project.",
			r.CLIVersion, CheckOwnershipHeaders, CheckOwnershipContent)
		c.Paths = differing
		return c
	}
}

// sameGeneratingCLI reports whether the nise running this check renders the
// same templates as the nise that generated the project.
//
// The comparison is on the parsed version, not on the raw string, and that
// distinction is load-bearing rather than cosmetic. A binary built from a
// source checkout with uncommitted changes reports a version with a "+dirty"
// suffix appended to the very pseudo-version the recipe recorded: the same
// build, the same templates, a different string. Comparing strings there
// downgrades the check to a skip for the one person most likely to be
// running it — a framework developer, in the framework's own generated test
// project — and a hand-edited file would slip through with exit 0.
//
// Build metadata is exactly what semantic versioning says does not affect
// precedence, so two versions that parse equal render the same templates. If
// either string carries no comparable version at all, the raw strings are
// compared instead, which is the conservative answer: unequal means skip.
func sameGeneratingCLI(running, recipeCLI string) bool {
	rv, rerr := doctor.ParseVersion(running)
	cv, cerr := doctor.ParseVersion(recipeCLI)
	if rerr == nil && cerr == nil {
		return rv.Compare(cv) == 0
	}
	return running == recipeCLI
}

// describeDiff summarizes how two versions of a file differ, without
// printing either one. A generated file can be several hundred lines long
// and, in the case of the recipe, carries version strings; a check's output
// is a summary line, not a patch. The first differing line number is what a
// developer actually needs to go look at.
func describeDiff(got, want []byte) string {
	gotLines := strings.Split(string(got), "\n")
	wantLines := strings.Split(string(want), "\n")
	for i := 0; i < len(gotLines) && i < len(wantLines); i++ {
		if gotLines[i] != wantLines[i] {
			return fmt.Sprintf("first difference at line %d", i+1)
		}
	}
	switch {
	case len(gotLines) > len(wantLines):
		return fmt.Sprintf("%d extra line(s) at the end", len(gotLines)-len(wantLines))
	case len(wantLines) > len(gotLines):
		return fmt.Sprintf("%d line(s) missing from the end", len(wantLines)-len(gotLines))
	default:
		return "content differs"
	}
}
