package check

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/drilonrecica/nise-and-go/internal/doctor"
	"github.com/drilonrecica/nise-and-go/internal/generator"
	"github.com/drilonrecica/nise-and-go/internal/recipe"
)

// The invariant sentences. They are constants so the same wording appears on
// a check whether it passed, failed, or was skipped — a reader of a skipped
// check has to learn what went unverified, and a sentence written twice is a
// sentence that eventually disagrees with itself.
const (
	invariantRecipe = "The project declares a recipe this build of nise understands (ADR 0010)."
	invariantCLI    = "The running nise is not older than the nise that generated the project."
	invariantRT     = "The recipe's runtimeVersion is the runtime version go.mod actually requires."
)

// checkRecipe loads the recipe at root and returns both the check and the
// parsed recipe, so no later check has to read the file a second time. The
// returned recipe is nil whenever it did not load, which is what makes every
// dependent check skip rather than fail.
func checkRecipe(root string) (Check, *recipe.Recipe) {
	r, err := recipe.Load(os.DirFS(root), recipe.FileName)
	if err != nil {
		return fail(CheckRecipe, invariantRecipe,
			fmt.Sprintf("%s did not load: %s", recipe.FileName, err),
			recipeRemedy(err),
		), nil
	}

	c := pass(CheckRecipe, invariantRecipe, fmt.Sprintf(
		"%s: schemaVersion %d, profile %s, %s, cliVersion %s, runtimeVersion %s",
		recipe.FileName, r.SchemaVersion, r.Profile, describeModules(r.Modules), r.CLIVersion, r.RuntimeVersion,
	))
	c.Paths = []string{recipe.FileName}
	return c, &r
}

// describeModules renders the selected module list for a one-line detail.
func describeModules(modules []recipe.Module) string {
	if len(modules) == 0 {
		return "no modules"
	}
	names := make([]string, len(modules))
	for i, m := range modules {
		names[i] = string(m)
	}
	return "modules " + strings.Join(names, "+")
}

// recipeRemedy picks the recovery action for a recipe that did not load.
// A recipe written by a newer schema version is an upgrade, not a repair:
// telling that user to "fix the file by hand" would be the wrong remedy.
func recipeRemedy(err error) string {
	var schemaErr *recipe.SchemaVersionError
	if errors.As(err, &schemaErr) {
		return fmt.Sprintf(
			"Upgrade nise: this recipe declares schema version %d and this build understands up to %d.",
			schemaErr.Found, schemaErr.Supported,
		)
	}
	return "Restore " + recipe.FileName + " from version control, or fix the named field; the format is fixed by docs/adr/0010-project-recipe-format.md."
}

// checkCLIVersion compares the running nise against the version recorded in
// the recipe.
//
// Running an older nise than the one that generated the project is a
// compatibility violation, not a preference: this binary's templates,
// recipe schema, and ownership rules are the older ones, so every
// regeneration it performs is a downgrade of files it does not fully
// understand. Running a newer nise is fine and expected.
//
// Either version failing to parse is a skip, not a pass and not a failure:
// a source build reports a version string no comparison can order, and
// reporting ok without having compared anything is the dishonest-status
// failure this package exists to avoid.
func checkCLIVersion(r *recipe.Recipe, running string) Check {
	if r == nil {
		return skip(CheckCLIVersion, invariantCLI, "no valid recipe to compare against; see the \""+CheckRecipe+"\" check")
	}

	runningVersion, runErr := doctor.ParseVersion(running)
	if runErr != nil {
		return skip(CheckCLIVersion, invariantCLI, fmt.Sprintf(
			"this nise build reports version %q, which carries no comparable version number (a from-source build); nothing to compare the recipe's cliVersion %q against",
			running, r.CLIVersion,
		))
	}
	recipeVersion, recErr := doctor.ParseVersion(r.CLIVersion)
	if recErr != nil {
		return skip(CheckCLIVersion, invariantCLI, fmt.Sprintf(
			"the recipe's cliVersion %q carries no comparable version number; nothing to compare the running nise %s against",
			r.CLIVersion, runningVersion,
		))
	}

	if runningVersion.AtLeast(recipeVersion) {
		return pass(CheckCLIVersion, invariantCLI, fmt.Sprintf(
			"running nise %s; project generated by nise %s", runningVersion, recipeVersion,
		))
	}
	return fail(CheckCLIVersion, invariantCLI,
		fmt.Sprintf("running nise %s, but the project was generated or last upgraded by nise %s", runningVersion, recipeVersion),
		fmt.Sprintf("Upgrade the nise binary to at least %s, or run this check with the nise that generated the project.", recipeVersion),
	)
}

// goModFileName is the generated project's module file.
const goModFileName = "go.mod"

// checkRuntimeVersion compares the recipe's runtimeVersion against the
// version of the Nise module go.mod actually requires. A recipe that names a
// runtime the project does not use is a recipe that lies about the project,
// and every later compatibility decision — including the upgrade path M6
// builds — reads that field rather than go.mod.
//
// Every way of not being able to compare is a skip. In particular, a project
// with no requirement on the Nise module at all is not a failure: BLUEPRINT
// §5's escape hatch says detaching means "removing the project recipe,
// replacing any remaining small runtime imports, and ceasing to use the
// CLI", and a project partway through that is not broken.
func checkRuntimeVersion(root string, r *recipe.Recipe) Check {
	if r == nil {
		return skip(CheckRuntimeVersion, invariantRT, "no valid recipe to compare against; see the \""+CheckRecipe+"\" check")
	}

	path := filepath.Join(root, goModFileName)
	data, err := os.ReadFile(path) // #nosec G304 -- path is root joined with this package's own goModFileName constant, never with external input.
	if err != nil {
		return skip(CheckRuntimeVersion, invariantRT, fmt.Sprintf(
			"could not read %s (%s); nothing to compare the recipe's runtimeVersion %q against", goModFileName, err, r.RuntimeVersion,
		))
	}

	required, ok := requiredModuleVersion(string(data), generator.NiseModulePath)
	if !ok {
		return skip(CheckRuntimeVersion, invariantRT, fmt.Sprintf(
			"%s states no single require for %s; nothing to compare the recipe's runtimeVersion %q against",
			goModFileName, generator.NiseModulePath, r.RuntimeVersion,
		))
	}

	if required == r.RuntimeVersion {
		return Check{
			Name: CheckRuntimeVersion, Status: StatusOK, Invariant: invariantRT,
			Detail: fmt.Sprintf("%s requires %s %s, which is the recipe's runtimeVersion", goModFileName, generator.NiseModulePath, required),
			Paths:  []string{goModFileName, recipe.FileName},
		}
	}
	c := fail(CheckRuntimeVersion, invariantRT,
		fmt.Sprintf("%s requires %s %s, but the recipe's runtimeVersion is %s", goModFileName, generator.NiseModulePath, required, r.RuntimeVersion),
		fmt.Sprintf("Set runtimeVersion to %q in %s, or change the %s requirement in %s back to %q — whichever version this project actually targets.",
			required, recipe.FileName, generator.NiseModulePath, goModFileName, r.RuntimeVersion),
	)
	c.Paths = []string{goModFileName, recipe.FileName}
	return c
}

// requiredModuleVersion extracts the version go.mod requires for module, and
// reports false when there is not exactly one such requirement.
//
// It is a deliberately narrow line scanner, not a go.mod parser:
// golang.org/x/mod would be the first runtime dependency this module has
// ever taken (Global Constraint 2, zero runtime dependencies), for one
// lookup whose only consumer reports "skipped" the moment anything is
// ambiguous. Anything it does not confidently understand — a replace
// directive's arrow, an exclude, two different required versions, a line
// whose second token is not the module path — makes it return false, and a
// false is a skip, never a failure. It can under-report; by construction it
// cannot mis-report.
func requiredModuleVersion(goMod, module string) (string, bool) {
	var found []string
	inBlock := false
	for _, raw := range strings.Split(goMod, "\n") {
		line := strings.TrimSpace(raw)
		if i := strings.Index(line, "//"); i >= 0 {
			line = strings.TrimSpace(line[:i])
		}
		switch {
		case line == "require (":
			inBlock = true
			continue
		case inBlock && line == ")":
			inBlock = false
			continue
		}

		fields := strings.Fields(line)
		switch {
		case inBlock:
			// Inside a require block a line is "<module> <version>".
			if len(fields) == 2 && fields[0] == module {
				found = append(found, fields[1])
			}
		case len(fields) == 3 && fields[0] == "require" && fields[1] == module:
			// A single-line "require <module> <version>".
			found = append(found, fields[2])
		}
	}

	if len(found) != 1 {
		return "", false
	}
	return found[0], true
}
