// Package main generates the Homebrew formula for the nise CLI from a
// published release's checksums.txt.
//
// It exists so that the official tap (github.com/drilonrecica/homebrew-tap)
// is updated from the release's canonical artifacts rather than from a
// rebuild. GoReleaser can push a formula itself, but it does so during the
// tag build — and this project's releases are drafts at that point, so the
// formula would point at download URLs that do not exist until a human
// publishes. The publish click is the trigger that matters, and
// .github/workflows/homebrew.yml runs this command when it happens.
//
// The generator reads exactly two inputs — the release tag and the release's
// checksums.txt — and writes one file. Same inputs, same bytes: no
// timestamps, no environment, no network. The four SHA-256 values it embeds
// are the ones GoReleaser published, which brew re-verifies against every
// archive it downloads; the workflow verifies the build attestation on
// checksums.txt before this command ever runs, so a formula cannot be
// generated from artifacts the release workflow did not produce.
package main

import (
	"errors"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"regexp"
	"strconv"
	"strings"
	"text/template"
)

// repo is the canonical repository, locked by ADR 0007. It is a constant
// rather than a flag because a formula pointing anywhere else is a bug, not
// a configuration.
const repo = "drilonrecica/nise-and-go"

// brewTargets are the release platforms Homebrew can install: the six pairs
// in .goreleaser.yaml minus the two Windows ones, because Homebrew does not
// run on Windows. test/release checks this list against the release targets
// so that a platform added to the release is consciously added or excluded
// here.
var brewTargets = []struct{ goos, goarch string }{
	{"darwin", "amd64"},
	{"darwin", "arm64"},
	{"linux", "amd64"},
	{"linux", "arm64"},
}

// releaseTag accepts exactly a plain semantic version tag. A prerelease tag
// (v0.2.0-rc.1) is refused here even though the workflow already skips
// prereleases, because the tap is what `brew install` gives everybody and a
// release candidate must never reach it through any path.
var releaseTag = regexp.MustCompile(`^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$`)

// checksumLine is the shape GoReleaser writes: a SHA-256 in lowercase hex,
// two spaces, a filename. Anything else in the file means this is not the
// file the release published, and the only safe response is refusal.
var checksumLine = regexp.MustCompile(`^([0-9a-f]{64})  (\S+)$`)

// formulaVersion reads the version stanza back out of an existing formula,
// for the downgrade check.
var formulaVersion = regexp.MustCompile(`(?m)^  version "(\d+)\.(\d+)\.(\d+)"$`)

// formulaTemplate is the entire generated file. The header declares the
// ownership model: the release automation owns every byte, and a hand edit
// survives only until the next publish.
var formulaTemplate = template.Must(template.New("nise.rb").Parse(`# Generated by cmd/homebrew-formula in github.com/{{.Repo}} from the
# checksums.txt of release {{.Tag}}. This file is owned by the release
# automation: every published release regenerates it completely. Do not edit
# by hand — change the generator instead.
class Nise < Formula
  desc "Opinionated application foundation for Go, chi, PostgreSQL, and SvelteKit"
  homepage "https://github.com/{{.Repo}}"
  version "{{.Version}}"
  license "MIT"
{{range .Platforms}}
  {{.Open}}
    on_intel do
      url "https://github.com/{{$.Repo}}/releases/download/{{$.Tag}}/{{.Intel.Name}}"
      sha256 "{{.Intel.SHA256}}"
    end

    on_arm do
      url "https://github.com/{{$.Repo}}/releases/download/{{$.Tag}}/{{.Arm.Name}}"
      sha256 "{{.Arm.SHA256}}"
    end
  end
{{end}}
  def install
    bin.install "nise"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/nise --version")
  end
end
`))

type archive struct {
	Name   string
	SHA256 string
}

type platform struct {
	Open       string
	Intel, Arm archive
}

func main() {
	os.Exit(run(os.Args[1:], os.Stderr))
}

// run executes the generator and returns the process exit code, so the whole
// command is testable in-process. All diagnostics go to stderr; the only
// output is the file named by -out.
func run(args []string, stderr io.Writer) int {
	fs := flag.NewFlagSet("homebrew-formula", flag.ContinueOnError)
	fs.SetOutput(stderr)
	tag := fs.String("tag", "", "published release tag, e.g. v0.1.0")
	checksums := fs.String("checksums", "", "path to the release's checksums.txt")
	out := fs.String("out", "", "formula file to write, e.g. tap/Formula/nise.rb")
	allowDowngrade := fs.Bool("allow-downgrade", false,
		"permit writing a version older than the one the formula already names (rollback)")
	if err := fs.Parse(args); err != nil {
		return 2
	}
	if err := generate(*tag, *checksums, *out, *allowDowngrade); err != nil {
		// A diagnostic that cannot be written has nowhere else to go.
		_, _ = fmt.Fprintf(stderr, "homebrew-formula: %v\n", err)
		return 1
	}
	return 0
}

func generate(tag, checksumsPath, outPath string, allowDowngrade bool) error {
	if tag == "" || checksumsPath == "" || outPath == "" {
		return errors.New("-tag, -checksums, and -out are all required")
	}
	if !releaseTag.MatchString(tag) {
		return fmt.Errorf("tag %q is not a plain vMAJOR.MINOR.PATCH release tag; prereleases never reach the tap", tag)
	}
	version := strings.TrimPrefix(tag, "v")

	sums, err := parseChecksums(checksumsPath)
	if err != nil {
		return err
	}

	platforms, err := brewPlatforms(version, sums)
	if err != nil {
		return err
	}

	if err := refuseDowngrade(outPath, version, allowDowngrade); err != nil {
		return err
	}

	var rendered strings.Builder
	err = formulaTemplate.Execute(&rendered, struct {
		Repo, Tag, Version string
		Platforms          []platform
	}{repo, tag, version, platforms})
	if err != nil {
		return fmt.Errorf("rendering the formula: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(outPath), 0o750); err != nil {
		return fmt.Errorf("creating the formula directory: %w", err)
	}
	// 0644 rather than 0600: the formula is committed to a public tap, so
	// there is nothing about it to keep from other local users.
	// #nosec G306 -- the file's whole purpose is to be published.
	if err := os.WriteFile(outPath, []byte(rendered.String()), 0o644); err != nil {
		return fmt.Errorf("writing the formula: %w", err)
	}
	return nil
}

// parseChecksums reads a GoReleaser checksums.txt into filename → SHA-256.
// Every line must parse: a malformed line means the input is not the file
// the release published, and continuing would embed hashes from something
// else.
func parseChecksums(path string) (map[string]string, error) {
	data, err := os.ReadFile(path) // #nosec G304 -- opening the path the operator named is what the command is.
	if err != nil {
		return nil, fmt.Errorf("reading the checksums file: %w", err)
	}
	sums := make(map[string]string)
	for i, line := range strings.Split(strings.TrimRight(string(data), "\n"), "\n") {
		match := checksumLine.FindStringSubmatch(line)
		if match == nil {
			return nil, fmt.Errorf("%s line %d is not a GoReleaser checksum line: %q", path, i+1, line)
		}
		sums[match[2]] = match[1]
	}
	if len(sums) == 0 {
		return nil, fmt.Errorf("%s names no artifacts", path)
	}
	return sums, nil
}

// brewPlatforms resolves the four Homebrew-installable archives out of the
// checksum list. A missing archive is a hard error: a formula silently
// covering three platforms is a broken install for the fourth's users.
func brewPlatforms(version string, sums map[string]string) ([]platform, error) {
	lookup := func(goos, goarch string) (archive, error) {
		name := fmt.Sprintf("nise_%s_%s_%s.tar.gz", version, goos, goarch)
		sha, ok := sums[name]
		if !ok {
			return archive{}, fmt.Errorf("checksums.txt does not name %s; is this the checksums file of release v%s?", name, version)
		}
		return archive{Name: name, SHA256: sha}, nil
	}

	byOS := map[string]*platform{
		"darwin": {Open: "on_macos do"},
		"linux":  {Open: "on_linux do"},
	}
	for _, target := range brewTargets {
		arch, err := lookup(target.goos, target.goarch)
		if err != nil {
			return nil, err
		}
		if target.goarch == "amd64" {
			byOS[target.goos].Intel = arch
		} else {
			byOS[target.goos].Arm = arch
		}
	}
	return []platform{*byOS["darwin"], *byOS["linux"]}, nil
}

// refuseDowngrade compares the version an existing formula names against the
// one about to be written. Publishing an old release again — or re-running
// the workflow against one — must not silently move every `brew upgrade`
// user backwards; rolling the tap back is a real operation, and it is spelled
// -allow-downgrade so it only happens when somebody means it.
func refuseDowngrade(outPath, version string, allowDowngrade bool) error {
	existing, err := os.ReadFile(outPath) // #nosec G304 -- opening the path the operator named is what the command is.
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("reading the existing formula: %w", err)
	}
	match := formulaVersion.FindStringSubmatch(string(existing))
	if match == nil {
		return fmt.Errorf("%s exists but carries no version stanza this generator writes; refusing to overwrite a file it does not own", outPath)
	}
	if allowDowngrade || !newerThan(match[1:4], strings.SplitN(version, ".", 3)) {
		return nil
	}
	return fmt.Errorf("the tap already serves %s.%s.%s, which is newer than %s; pass -allow-downgrade only to deliberately roll the tap back",
		match[1], match[2], match[3], version)
}

// newerThan reports whether version a (three numeric parts) is strictly
// newer than b. Both inputs have already been shape-checked by regexp, so a
// parse failure here is impossible rather than handled.
func newerThan(a, b []string) bool {
	for i := range 3 {
		x, _ := strconv.Atoi(a[i])
		y, _ := strconv.Atoi(b[i])
		if x != y {
			return x > y
		}
	}
	return false
}
