// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Resource struct {
	ID          pgtype.UUID
	OrgID       pgtype.UUID
	Name        string
	Description string
	Location    string
	PhotoKey    pgtype.Text
	RetiredAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
