// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountResources(ctx context.Context, arg CountResourcesParams) (int64, error)
	//
	// The tenant is not a parameter. It is established by the transaction with
	// SET LOCAL before this statement runs, and the row-level-security policy's
	// WITH CHECK clause is what puts it in the row — so a resource cannot be
	// created in an organization the caller is not inside, whatever the caller
	// passes.
	CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error)
	GetResource(ctx context.Context, arg GetResourceParams) (Resource, error)
	//
	// Cursor pagination, keyed on (lower(name), id). The name is what somebody
	// browses by, and the identifier breaks ties so that two resources with the
	// same lowercased name cannot make a page boundary ambiguous — which is how a
	// cursor silently skips or repeats a row.
	//
	// sqlc.arg(after_name) and sqlc.arg(after_id) are empty on the first page; the
	// comparison is written so that an empty cursor matches everything.
	ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error)
	//
	// Retiring is idempotent by omission rather than by construction: the WHERE
	// clause matches only a resource still in service, so a second call returns no
	// rows and the use case reports the resource as already retired instead of
	// moving the timestamp.
	RetireResource(ctx context.Context, arg RetireResourceParams) (Resource, error)
	SetResourcePhoto(ctx context.Context, arg SetResourcePhotoParams) (Resource, error)
	UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error)
}

var _ Querier = (*Queries)(nil)
