// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: resource.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countResources = `-- name: CountResources :one
SELECT count(*)
FROM resources
WHERE ($1::boolean OR retired_at IS NULL)
`

type CountResourcesParams struct {
	IncludeRetired bool
}

func (q *Queries) CountResources(ctx context.Context, arg CountResourcesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countResources, arg.IncludeRetired)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createResource = `-- name: CreateResource :one
INSERT INTO resources (org_id, name, description, location)
VALUES (current_tenant(), $1, $2, $3)
RETURNING id, org_id, name, description, location, photo_key, retired_at, created_at, updated_at
`

type CreateResourceParams struct {
	Name        string
	Description string
	Location    string
}

// The tenant is not a parameter. It is established by the transaction with
// SET LOCAL before this statement runs, and the row-level-security policy's
// WITH CHECK clause is what puts it in the row — so a resource cannot be
// created in an organization the caller is not inside, whatever the caller
// passes.
func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource, arg.Name, arg.Description, arg.Location)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.PhotoKey,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getResource = `-- name: GetResource :one
SELECT id, org_id, name, description, location, photo_key, retired_at, created_at, updated_at
FROM resources
WHERE id = $1
`

type GetResourceParams struct {
	ID pgtype.UUID
}

func (q *Queries) GetResource(ctx context.Context, arg GetResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, getResource, arg.ID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.PhotoKey,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listResources = `-- name: ListResources :many
SELECT id, org_id, name, description, location, photo_key, retired_at, created_at, updated_at
FROM resources
WHERE ($1::boolean OR retired_at IS NULL)
  AND (
    $2::text = ''
    OR (lower(name), id) > ($2::text, $3::uuid)
  )
ORDER BY lower(name), id
LIMIT $4
`

type ListResourcesParams struct {
	IncludeRetired bool
	AfterName      string
	AfterID        pgtype.UUID
	PageSize       int32
}

// Cursor pagination, keyed on (lower(name), id). The name is what somebody
// browses by, and the identifier breaks ties so that two resources with the
// same lowercased name cannot make a page boundary ambiguous — which is how a
// cursor silently skips or repeats a row.
//
// sqlc.arg(after_name) and sqlc.arg(after_id) are empty on the first page; the
// comparison is written so that an empty cursor matches everything.
func (q *Queries) ListResources(ctx context.Context, arg ListResourcesParams) ([]Resource, error) {
	rows, err := q.db.Query(ctx, listResources,
		arg.IncludeRetired,
		arg.AfterName,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Resource{}
	for rows.Next() {
		var i Resource
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.Name,
			&i.Description,
			&i.Location,
			&i.PhotoKey,
			&i.RetiredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retireResource = `-- name: RetireResource :one
UPDATE resources
SET retired_at = now(), updated_at = now()
WHERE id = $1 AND retired_at IS NULL
RETURNING id, org_id, name, description, location, photo_key, retired_at, created_at, updated_at
`

type RetireResourceParams struct {
	ID pgtype.UUID
}

// Retiring is idempotent by omission rather than by construction: the WHERE
// clause matches only a resource still in service, so a second call returns no
// rows and the use case reports the resource as already retired instead of
// moving the timestamp.
func (q *Queries) RetireResource(ctx context.Context, arg RetireResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, retireResource, arg.ID)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.PhotoKey,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setResourcePhoto = `-- name: SetResourcePhoto :one
UPDATE resources
SET photo_key = $2, updated_at = now()
WHERE id = $1
RETURNING id, org_id, name, description, location, photo_key, retired_at, created_at, updated_at
`

type SetResourcePhotoParams struct {
	ID       pgtype.UUID
	PhotoKey pgtype.Text
}

func (q *Queries) SetResourcePhoto(ctx context.Context, arg SetResourcePhotoParams) (Resource, error) {
	row := q.db.QueryRow(ctx, setResourcePhoto, arg.ID, arg.PhotoKey)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.PhotoKey,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateResource = `-- name: UpdateResource :one
UPDATE resources
SET name = $2, description = $3, location = $4, updated_at = now()
WHERE id = $1 AND retired_at IS NULL
RETURNING id, org_id, name, description, location, photo_key, retired_at, created_at, updated_at
`

type UpdateResourceParams struct {
	ID          pgtype.UUID
	Name        string
	Description string
	Location    string
}

func (q *Queries) UpdateResource(ctx context.Context, arg UpdateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, updateResource,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Location,
	)
	var i Resource
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.Name,
		&i.Description,
		&i.Location,
		&i.PhotoKey,
		&i.RetiredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
