package observability

import (
	"context"
	"errors"
	"testing"
)

func TestNoopTracerReturnsContextUnchanged(t *testing.T) {
	type key struct{}
	ctx := context.WithValue(context.Background(), key{}, "value")

	got, span := (NoopTracer{}).Start(ctx, "op")
	if got != ctx {
		t.Error("NoopTracer.Start must return the same context it was given")
	}
	span.RecordError(errors.New("boom"))
	span.RecordError(nil)
	span.End()
}

// TestNoopTracerAllocsPerRun proves the brief's central claim: the unused
// tracing path costs nothing. Every application generated by this
// framework calls Tracer.Start on every traced operation whether or not it
// has wired a real tracer behind the interface; if NoopTracer allocated on
// that path, "optional tracing" would carry a permanent tax even when
// unused.
func TestNoopTracerAllocsPerRun(t *testing.T) {
	tracer := NoopTracer{}
	ctx := context.Background()
	err := errors.New("boom")

	allocs := testing.AllocsPerRun(1000, func() {
		spanCtx, span := tracer.Start(ctx, "operation")
		span.RecordError(err)
		span.End()
		_ = spanCtx
	})

	t.Logf("NoopTracer: %v allocations/op over 1000 runs", allocs)
	if allocs != 0 {
		t.Fatalf("NoopTracer allocated %v allocations/op, want 0", allocs)
	}
}
