// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Reservation struct {
	ID             pgtype.UUID
	OrgID          pgtype.UUID
	ResourceID     pgtype.UUID
	HolderID       pgtype.UUID
	During         pgtype.Range[pgtype.Timestamptz]
	State          string
	Note           string
	ReturnNote     string
	ReturnPhotoKey pgtype.Text
	CheckedOutAt   pgtype.Timestamptz
	ReturnedAt     pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}
