// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error)
	//
	// The state is in the WHERE clause as well as being checked by the use case.
	// The use case's check produces the readable refusal; this one is what makes
	// the transition atomic even if a future caller forgets to lock the row first.
	CheckOutReservation(ctx context.Context, arg CheckOutReservationParams) (Reservation, error)
	CountReservations(ctx context.Context, arg CountReservationsParams) (int64, error)
	//
	// The tenant is not a parameter: it is established by the transaction and the
	// policy's WITH CHECK clause is what puts it in the row.
	//
	// Nothing here checks whether the window is free. That check does not exist in
	// this file because it cannot be written correctly: under concurrency, two
	// transactions both read "free" and both insert. The exclusion constraint on
	// the table is what refuses the second one, and it is the only version of the
	// check that is true.
	CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error)
	GetReservation(ctx context.Context, arg GetReservationParams) (Reservation, error)
	//
	// The row-locking read every state transition starts with. FOR UPDATE is what
	// makes "read the state, decide, write the state" atomic; without it two
	// concurrent check-outs both read 'booked' and the second overwrites the
	// first's timestamp.
	GetReservationForUpdate(ctx context.Context, arg GetReservationForUpdateParams) (Reservation, error)
	//
	// The filtered, paginated listing. Every filter is optional and expressed as
	// "the argument is empty OR it matches", so one query serves the calendar, the
	// steward view, and "my reservations" rather than three that can disagree.
	//
	// Ordering is by window start then identifier: the identifier breaks ties so a
	// page boundary between two reservations starting at the same instant cannot
	// skip or repeat one.
	ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error)
	//
	// The periodic sweep. A reservation still 'booked' after its window has closed
	// was never collected.
	//
	// The cutoff is a parameter rather than now(), so a test can run the sweep
	// against a clock it controls instead of waiting, and so an operator can
	// replay it for a past window after an outage without it seeing a different
	// "now" than the one being repaired.
	MarkNoShows(ctx context.Context, arg MarkNoShowsParams) ([]Reservation, error)
	ReturnReservation(ctx context.Context, arg ReturnReservationParams) (Reservation, error)
}

var _ Querier = (*Queries)(nil)
