// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reservation.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelReservation = `-- name: CancelReservation :one
UPDATE reservations
SET state = 'cancelled', cancelled_at = now(), updated_at = now()
WHERE id = $1 AND state = 'booked'
RETURNING id, org_id, resource_id, holder_id, during, state, note, return_note,
          return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
`

type CancelReservationParams struct {
	ID pgtype.UUID
}

func (q *Queries) CancelReservation(ctx context.Context, arg CancelReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, cancelReservation, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.HolderID,
		&i.During,
		&i.State,
		&i.Note,
		&i.ReturnNote,
		&i.ReturnPhotoKey,
		&i.CheckedOutAt,
		&i.ReturnedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkOutReservation = `-- name: CheckOutReservation :one
UPDATE reservations
SET state = 'checked_out', checked_out_at = now(), updated_at = now()
WHERE id = $1 AND state = 'booked'
RETURNING id, org_id, resource_id, holder_id, during, state, note, return_note,
          return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
`

type CheckOutReservationParams struct {
	ID pgtype.UUID
}

// The state is in the WHERE clause as well as being checked by the use case.
// The use case's check produces the readable refusal; this one is what makes
// the transition atomic even if a future caller forgets to lock the row first.
func (q *Queries) CheckOutReservation(ctx context.Context, arg CheckOutReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, checkOutReservation, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.HolderID,
		&i.During,
		&i.State,
		&i.Note,
		&i.ReturnNote,
		&i.ReturnPhotoKey,
		&i.CheckedOutAt,
		&i.ReturnedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countReservations = `-- name: CountReservations :one
SELECT count(*)
FROM reservations
WHERE ($1::uuid IS NULL OR resource_id = $1::uuid)
  AND ($2::uuid IS NULL OR holder_id = $2::uuid)
  AND ($3::text[] = '{}' OR state = ANY ($3::text[]))
  AND ($4::timestamptz IS NULL
       OR during && tstzrange($4::timestamptz, $5::timestamptz, '[)'))
`

type CountReservationsParams struct {
	ResourceID  pgtype.UUID
	HolderID    pgtype.UUID
	States      []string
	WindowStart pgtype.Timestamptz
	WindowEnd   pgtype.Timestamptz
}

func (q *Queries) CountReservations(ctx context.Context, arg CountReservationsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReservations,
		arg.ResourceID,
		arg.HolderID,
		arg.States,
		arg.WindowStart,
		arg.WindowEnd,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReservation = `-- name: CreateReservation :one
INSERT INTO reservations (org_id, resource_id, holder_id, during, note)
VALUES (current_tenant(), $1, $2, tstzrange($4::timestamptz, $5::timestamptz, '[)'), $3)
RETURNING id, org_id, resource_id, holder_id, during, state, note, return_note,
          return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
`

type CreateReservationParams struct {
	ResourceID pgtype.UUID
	HolderID   pgtype.UUID
	Note       string
	StartsAt   pgtype.Timestamptz
	EndsAt     pgtype.Timestamptz
}

// The tenant is not a parameter: it is established by the transaction and the
// policy's WITH CHECK clause is what puts it in the row.
//
// Nothing here checks whether the window is free. That check does not exist in
// this file because it cannot be written correctly: under concurrency, two
// transactions both read "free" and both insert. The exclusion constraint on
// the table is what refuses the second one, and it is the only version of the
// check that is true.
func (q *Queries) CreateReservation(ctx context.Context, arg CreateReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, createReservation,
		arg.ResourceID,
		arg.HolderID,
		arg.Note,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.HolderID,
		&i.During,
		&i.State,
		&i.Note,
		&i.ReturnNote,
		&i.ReturnPhotoKey,
		&i.CheckedOutAt,
		&i.ReturnedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservation = `-- name: GetReservation :one
SELECT id, org_id, resource_id, holder_id, during, state, note, return_note,
       return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
FROM reservations
WHERE id = $1
`

type GetReservationParams struct {
	ID pgtype.UUID
}

func (q *Queries) GetReservation(ctx context.Context, arg GetReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservation, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.HolderID,
		&i.During,
		&i.State,
		&i.Note,
		&i.ReturnNote,
		&i.ReturnPhotoKey,
		&i.CheckedOutAt,
		&i.ReturnedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReservationForUpdate = `-- name: GetReservationForUpdate :one
SELECT id, org_id, resource_id, holder_id, during, state, note, return_note,
       return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
FROM reservations
WHERE id = $1
FOR UPDATE
`

type GetReservationForUpdateParams struct {
	ID pgtype.UUID
}

// The row-locking read every state transition starts with. FOR UPDATE is what
// makes "read the state, decide, write the state" atomic; without it two
// concurrent check-outs both read 'booked' and the second overwrites the
// first's timestamp.
func (q *Queries) GetReservationForUpdate(ctx context.Context, arg GetReservationForUpdateParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, getReservationForUpdate, arg.ID)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.HolderID,
		&i.During,
		&i.State,
		&i.Note,
		&i.ReturnNote,
		&i.ReturnPhotoKey,
		&i.CheckedOutAt,
		&i.ReturnedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReservations = `-- name: ListReservations :many
SELECT id, org_id, resource_id, holder_id, during, state, note, return_note,
       return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
FROM reservations
WHERE ($1::uuid IS NULL OR resource_id = $1::uuid)
  AND ($2::uuid IS NULL OR holder_id = $2::uuid)
  AND ($3::text[] = '{}' OR state = ANY ($3::text[]))
  AND ($4::timestamptz IS NULL
       OR during && tstzrange($4::timestamptz, $5::timestamptz, '[)'))
  AND ($6::timestamptz IS NULL
       OR (lower(during), id) > ($6::timestamptz, $7::uuid))
ORDER BY lower(during), id
LIMIT $8
`

type ListReservationsParams struct {
	ResourceID  pgtype.UUID
	HolderID    pgtype.UUID
	States      []string
	WindowStart pgtype.Timestamptz
	WindowEnd   pgtype.Timestamptz
	AfterStart  pgtype.Timestamptz
	AfterID     pgtype.UUID
	PageSize    int32
}

// The filtered, paginated listing. Every filter is optional and expressed as
// "the argument is empty OR it matches", so one query serves the calendar, the
// steward view, and "my reservations" rather than three that can disagree.
//
// Ordering is by window start then identifier: the identifier breaks ties so a
// page boundary between two reservations starting at the same instant cannot
// skip or repeat one.
func (q *Queries) ListReservations(ctx context.Context, arg ListReservationsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, listReservations,
		arg.ResourceID,
		arg.HolderID,
		arg.States,
		arg.WindowStart,
		arg.WindowEnd,
		arg.AfterStart,
		arg.AfterID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ResourceID,
			&i.HolderID,
			&i.During,
			&i.State,
			&i.Note,
			&i.ReturnNote,
			&i.ReturnPhotoKey,
			&i.CheckedOutAt,
			&i.ReturnedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markNoShows = `-- name: MarkNoShows :many
UPDATE reservations
SET state = 'no_show', updated_at = now()
WHERE state = 'booked' AND upper(during) <= $1::timestamptz
RETURNING id, org_id, resource_id, holder_id, during, state, note, return_note,
          return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
`

type MarkNoShowsParams struct {
	Cutoff pgtype.Timestamptz
}

// The periodic sweep. A reservation still 'booked' after its window has closed
// was never collected.
//
// The cutoff is a parameter rather than now(), so a test can run the sweep
// against a clock it controls instead of waiting, and so an operator can
// replay it for a past window after an outage without it seeing a different
// "now" than the one being repaired.
func (q *Queries) MarkNoShows(ctx context.Context, arg MarkNoShowsParams) ([]Reservation, error) {
	rows, err := q.db.Query(ctx, markNoShows, arg.Cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Reservation{}
	for rows.Next() {
		var i Reservation
		if err := rows.Scan(
			&i.ID,
			&i.OrgID,
			&i.ResourceID,
			&i.HolderID,
			&i.During,
			&i.State,
			&i.Note,
			&i.ReturnNote,
			&i.ReturnPhotoKey,
			&i.CheckedOutAt,
			&i.ReturnedAt,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const returnReservation = `-- name: ReturnReservation :one
UPDATE reservations
SET state = 'returned', returned_at = now(), return_note = $2,
    return_photo_key = $3, updated_at = now()
WHERE id = $1 AND state = 'checked_out'
RETURNING id, org_id, resource_id, holder_id, during, state, note, return_note,
          return_photo_key, checked_out_at, returned_at, cancelled_at, created_at, updated_at
`

type ReturnReservationParams struct {
	ID             pgtype.UUID
	ReturnNote     string
	ReturnPhotoKey pgtype.Text
}

func (q *Queries) ReturnReservation(ctx context.Context, arg ReturnReservationParams) (Reservation, error) {
	row := q.db.QueryRow(ctx, returnReservation, arg.ID, arg.ReturnNote, arg.ReturnPhotoKey)
	var i Reservation
	err := row.Scan(
		&i.ID,
		&i.OrgID,
		&i.ResourceID,
		&i.HolderID,
		&i.During,
		&i.State,
		&i.Note,
		&i.ReturnNote,
		&i.ReturnPhotoKey,
		&i.CheckedOutAt,
		&i.ReturnedAt,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
