// Package totp implements the second-factor primitives of the optional TOTP
// module: time-based one-time passwords (RFC 6238) and recovery codes.
//
// It is a primitive package, not a policy one. It produces and checks codes;
// it stores nothing, decides nothing about when a code is required, and knows
// nothing about accounts. The generated application's mfa feature owns the
// storage, the enrollment lifecycle, the replay window, and the audit trail.
//
// # HMAC-SHA1, deliberately
//
// RFC 6238 allows SHA-1, SHA-256, and SHA-512, and every authenticator
// application in practical use implements SHA-1 and only some implement the
// others — several silently compute SHA-1 regardless of what the provisioning
// URI says, which produces codes that never match and an enrollment nobody can
// debug. This package therefore fixes SHA-1, and that is a compatibility
// decision rather than a cryptographic preference.
//
// It is not a weakness here. TOTP uses HMAC, whose security rests on the key
// rather than on the hash's collision resistance, and the SHA-1 collision work
// says nothing about HMAC-SHA1. The output is six digits from a 160-bit key,
// valid for thirty seconds; the attack on it is guessing one of a million
// codes, which is a rate-limiting problem and not a hash problem.
//
// # Period and digits are fixed
//
// Thirty seconds and six digits are not configurable. Both are carried in the
// provisioning URI, both are ignored by some authenticator applications, and a
// deployment that changed either would discover it from users whose codes stop
// working rather than from a test.
//
// # Recovery codes are not passwords
//
// A recovery code is generated by this package with 50 bits of entropy from a
// cryptographic source, so it has no dictionary to search and nothing for a
// slow hash to defend. It is stored as SHA-256, for the same reason a session
// token is: the digest is enough to check it and useless to whoever reads the
// table. Argon2id belongs to secrets a human chose, which these are not.
package totp
