// Package generator writes a new Nise application from the golden-profile
// templates in templates/.
//
// # Determinism
//
// Generation is a pure function of its [Options]. Plan renders every file
// into memory, sorted by path, before anything is written; Write creates
// the tree from that plan with fixed file modes and LF line endings. No
// timestamp, hostname, username, absolute path, random value, or map
// iteration order reaches a generated byte, so two runs with equal Options
// produce byte-identical trees on every machine (constraints.md §5,
// docs/adr/0002-deterministic-generation.md).
//
// # No network, no subprocesses
//
// Generation writes files and does nothing else. It never runs go, pnpm,
// or git, and never opens a socket (constraints.md §4). The commands a
// user must run next are returned in [Result.NextCommands] for the CLI to
// print.
//
// # Refusing to destroy
//
// Write refuses a target directory that already contains anything, naming
// what is in the way. There is no force flag in this slice: the safe
// recovery is always a different directory or an explicit removal the user
// performs themselves (constraints.md §6).
//
// This package is private to Nise and imports only the standard library
// and Nise's own internal packages.
package generator
