package generator

import (
	"strings"

	"github.com/drilonrecica/nise-and-go/internal/recipe"
)

// Ownership is the ownership model a generated file declares, per ADR 0003
// and docs/generated-application-layout.md.
type Ownership string

const (
	// OwnerNise marks a file Nise regenerates. Hand edits are lost. Such a
	// file carries either NiseOwnedHeader or, for checked-in output from a
	// pinned generator, that tool's standard generated-code marker.
	OwnerNise Ownership = "nise"
	// OwnerApp marks a file the application owns. Nise writes it once and
	// never overwrites it.
	OwnerApp Ownership = "app"
)

// The two ownership headers. Neither records a Nise version: a version in
// the header would rewrite every file on every CLI upgrade and defeat the
// clean-regeneration check.
const (
	// NiseOwnedHeader marks a regenerated file. It matches Go's
	// `^// Code generated .* DO NOT EDIT\.$` convention exactly, which is
	// what makes it machine-readable rather than merely prose.
	NiseOwnedHeader = "Code generated by nise; DO NOT EDIT."
	// AppOwnedHeader marks a file written once and never overwritten.
	AppOwnedHeader = "Generated once by nise; owned by this application. Nise will not overwrite it."

	// OpenAPIGeneratedPath is the sole output whose bytes and ownership
	// marker come directly from the pinned OpenAPI generator.
	OpenAPIGeneratedPath = "internal/platform/httpapi/openapigen/openapi.gen.go"

	// OpenAPITypescriptGeneratedHeader is the standard marker emitted by
	// openapi-typescript. Unlike oapi-codegen's marker it does not carry the
	// tool version; the generated package pin and byte-diff gate provide that
	// reproducibility contract.
	OpenAPITypescriptGeneratedHeader = "This file was auto-generated by openapi-typescript."

	// OpenAPITypescriptGeneratedPath is the checked-in frontend model output.
	OpenAPITypescriptGeneratedPath = "frontend/src/lib/api/schema.d.ts"

	// SQLCGeneratedHeader is the standard marker sqlc writes. Like
	// oapi-codegen's, it is kept as the generator wrote it: rewriting an
	// external tool's header would make an ordinary regeneration dirty.
	// A feature's store/ directory is the structural ownership marker.
	SQLCGeneratedHeader = "Code generated by sqlc. DO NOT EDIT."
)

// IsFeatureQueryPath reports whether path is a feature's hand-written SQL.
//
// Those files carry no ownership header, and declare their ownership by path
// instead. A comment in a query file is not inert: sqlc copies it into the
// generated Go doc comment, so a "Nise will not overwrite it" header placed
// there would appear inside a tool-owned file and contradict that file's own
// marker. queries/ is application-owned and store/ is tool-owned; the two
// directory names are the declaration, which is the same resolution ADR 0009
// applies to files with no comment syntax at all.
func IsFeatureQueryPath(path string) bool {
	const prefix = "internal/features/"
	remainder, found := strings.CutPrefix(path, prefix)
	if !found || !strings.HasSuffix(path, ".sql") {
		return false
	}
	parts := strings.Split(remainder, "/")
	return len(parts) == 3 && parts[0] != "" && parts[1] == "queries"
}

// IsMailTemplatePath reports whether path is one of the application's
// embedded message templates.
//
// Those files carry no ownership header and declare their ownership by path,
// for a stronger version of the reason a feature's query files do. A comment
// in a message template is not inert: the plain-text part is sent verbatim to
// a person, so a header there would arrive in somebody's inbox reading "Nise
// will not overwrite it". The HTML part could hide one in a comment, but a
// pair of files whose ownership is declared two different ways is worse than
// one rule that covers both.
//
// internal/platform/mail/templates/ is application-owned in its entirety, and
// the directory is the declaration — the same resolution ADR 0009 applies to
// JSON, which has no comment syntax at all.
func IsMailTemplatePath(path string) bool {
	const prefix = "internal/platform/mail/templates/"
	remainder, found := strings.CutPrefix(path, prefix)
	if !found || remainder == "" {
		return false
	}
	return !strings.Contains(remainder, "/")
}

// IsSQLCGeneratedPath reports whether path is inside a feature's sqlc output
// directory, which is the structural ownership marker for that tool's files
// (ADR 0014). Everything under internal/features/<feature>/store is replaced
// wholesale by sqlc generate and is never hand-edited.
func IsSQLCGeneratedPath(path string) bool {
	const prefix = "internal/features/"
	remainder, found := strings.CutPrefix(path, prefix)
	if !found || !strings.HasSuffix(path, ".go") {
		return false
	}
	parts := strings.Split(remainder, "/")
	return len(parts) == 3 && parts[0] != "" && parts[1] == "store"
}

// templateRoot is the directory inside the embedded template filesystem
// holding the nise new templates.
const templateRoot = "new"

// templateFile maps one embedded template to the path it is written to.
type templateFile struct {
	// Template is the path inside templates/new, without the leading
	// "new/" and with its .tmpl suffix.
	Template string
	// Output is the generated file's path relative to the project root. It
	// is itself a template, because one output path depends on the
	// application's name.
	Output string
	// Owner is the ownership model the file's own header declares. It is
	// recorded here as well so a test can assert that the header in the
	// rendered bytes and the manifest agree — a header is easy to copy
	// wrong when a template is added by hand.
	Owner Ownership
	// Raw copies the embedded source bytes without running Nise's template
	// engine. It is reserved for vendored templates whose delimiters belong
	// to another pinned generator.
	Raw bool
	// Module names the compile-time module this file belongs to. An empty
	// value means every project gets the file; otherwise it is written only
	// when the recipe selected that module.
	Module recipe.Module
}

// templateFiles is every template nise new renders, sorted by output path.
//
// The mapping is explicit rather than derived from the template's own path
// for two reasons. Four output paths cannot be spelled as template paths
// at all: ".gitignore" and ".env.example" would be swallowed by this
// repository's own .gitignore, ".dockerignore" follows the same naming
// convention so that all three generated dotfiles are spelled one way, and
// cmd/<app>/main.go's directory is not known until generation time. And an
// explicit table is the thing a reviewer can read to know what a generated
// project contains, which a suffix-stripping rule is not.
//
// TestEveryTemplateIsInTheManifest asserts this list and the embedded
// filesystem name exactly the same set of files, so a template added
// without a manifest entry fails the build rather than being silently
// skipped.
var templateFiles = []templateFile{
	{Template: "dockerignore.tmpl", Output: ".dockerignore", Owner: OwnerApp},
	{Template: "env.example.tmpl", Output: ".env.example", Owner: OwnerApp},
	{Template: "gitignore.tmpl", Output: ".gitignore", Owner: OwnerApp},
	{Template: "golangci.yml.tmpl", Output: ".golangci.yml", Owner: OwnerApp},
	{Template: "Makefile.tmpl", Output: "Makefile", Owner: OwnerApp},
	{Template: "README.md.tmpl", Output: "README.md", Owner: OwnerApp},
	{Template: "api/README.md.tmpl", Output: "api/README.md", Owner: OwnerApp},
	{Template: "api/oapi-codegen.yaml.tmpl", Output: "api/oapi-codegen.yaml", Owner: OwnerApp, Raw: true},
	{Template: "api/openapi.yaml.tmpl", Output: "api/openapi.yaml", Owner: OwnerApp},
	{Template: "cmd/main.go.tmpl", Output: "cmd/{{.AppName}}/main.go", Owner: OwnerApp},
	{Template: "cmd/main_test.go.tmpl", Output: "cmd/{{.AppName}}/main_test.go", Owner: OwnerApp},
	{Template: "db/README.md.tmpl", Output: "db/README.md", Owner: OwnerApp},
	{Template: "db/embed.gen.go.tmpl", Output: "db/embed.gen.go", Owner: OwnerNise},
	{Template: "db/embed_test.go.tmpl", Output: "db/embed_test.go", Owner: OwnerApp},
	{Template: "db/migrations/00001_baseline.sql.tmpl", Output: "db/migrations/00001_baseline.sql", Owner: OwnerApp},
	{Template: "db/migrations/00002_idempotency_keys.sql.tmpl", Output: "db/migrations/00002_idempotency_keys.sql", Owner: OwnerApp},
	{Template: "db/migrations/00003_identity.sql.tmpl", Output: "db/migrations/00003_identity.sql", Owner: OwnerApp},
	{Template: "db/migrations/00004_audit.sql.tmpl", Output: "db/migrations/00004_audit.sql", Owner: OwnerApp},
	{Template: "db/migrations/00005_authorization.sql.tmpl", Output: "db/migrations/00005_authorization.sql", Owner: OwnerApp},
	{Template: "db/migrations/00006_invitations.sql.tmpl", Output: "db/migrations/00006_invitations.sql", Owner: OwnerApp},
	{Template: "db/migrations/00007_throttle.sql.tmpl", Output: "db/migrations/00007_throttle.sql", Owner: OwnerApp},
	{Template: "db/migrations/00008_reauthentication.sql.tmpl", Output: "db/migrations/00008_reauthentication.sql", Owner: OwnerApp},
	{Template: "db/migrations/00009_jobs.sql.tmpl", Output: "db/migrations/00009_jobs.sql", Owner: OwnerApp},
	{Template: "db/migrations/module_notifications.sql.tmpl", Output: "db/migrations/{{.NotificationsMigration}}_notifications.sql", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "db/migrations/module_organizations.sql.tmpl", Output: "db/migrations/{{.OrganizationsMigration}}_organizations.sql", Owner: OwnerApp, Module: recipe.ModuleOrganizations},
	{Template: "db/migrations/module_totp.sql.tmpl", Output: "db/migrations/{{.TOTPMigration}}_totp.sql", Owner: OwnerApp, Module: recipe.ModuleTOTP},
	{Template: "db/migrations/module_uploads.sql.tmpl", Output: "db/migrations/{{.UploadsMigration}}_uploads.sql", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "deploy/Dockerfile.tmpl", Output: "deploy/Dockerfile", Owner: OwnerApp},
	{Template: "deploy/README.md.tmpl", Output: "deploy/README.md", Owner: OwnerApp},
	{Template: "deploy/compose.yaml.tmpl", Output: "deploy/compose.yaml", Owner: OwnerApp},
	{Template: "frontend/README.md.tmpl", Output: "frontend/README.md", Owner: OwnerApp},
	{Template: "frontend/gitignore.tmpl", Output: "frontend/.gitignore", Owner: OwnerApp},
	{Template: "frontend/biome.jsonc.tmpl", Output: "frontend/biome.jsonc", Owner: OwnerApp, Raw: true},
	{Template: "frontend/e2e/README.md.tmpl", Output: "frontend/e2e/README.md", Owner: OwnerApp},
	{Template: "frontend/e2e/session.spec.ts.tmpl", Output: "frontend/e2e/session.spec.ts", Owner: OwnerApp},
	{Template: "frontend/e2e/sign-in.spec.ts.tmpl", Output: "frontend/e2e/sign-in.spec.ts", Owner: OwnerApp},
	{Template: "frontend/package.json.tmpl", Output: "frontend/package.json", Owner: OwnerApp},
	{Template: "frontend/playwright.config.ts.tmpl", Output: "frontend/playwright.config.ts", Owner: OwnerApp},
	{Template: "frontend/scripts/check-contrast.mjs.tmpl", Output: "frontend/scripts/check-contrast.mjs", Owner: OwnerApp},
	{Template: "frontend/scripts/check-runes.mjs.tmpl", Output: "frontend/scripts/check-runes.mjs", Owner: OwnerApp},
	{Template: "frontend/src/app.css.tmpl", Output: "frontend/src/app.css", Owner: OwnerApp},
	{Template: "frontend/src/browser-setup.ts.tmpl", Output: "frontend/src/browser-setup.ts", Owner: OwnerApp},
	{Template: "frontend/src/app.d.ts.tmpl", Output: "frontend/src/app.d.ts", Owner: OwnerApp},
	{Template: "frontend/src/app.html.tmpl", Output: "frontend/src/app.html", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ThemeControl.svelte.tmpl", Output: "frontend/src/lib/components/ThemeControl.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/AccountMenu.svelte.tmpl", Output: "frontend/src/lib/components/shell/AccountMenu.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/AppShell.svelte.tmpl", Output: "frontend/src/lib/components/shell/AppShell.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/Breadcrumbs.svelte.tmpl", Output: "frontend/src/lib/components/shell/Breadcrumbs.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/NavDrawer.svelte.tmpl", Output: "frontend/src/lib/components/shell/NavDrawer.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/Sidebar.svelte.tmpl", Output: "frontend/src/lib/components/shell/Sidebar.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/SidebarNav.svelte.tmpl", Output: "frontend/src/lib/components/shell/SidebarNav.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/shell/TopBar.svelte.tmpl", Output: "frontend/src/lib/components/shell/TopBar.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Alert.svelte.tmpl", Output: "frontend/src/lib/components/ui/Alert.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Badge.svelte.tmpl", Output: "frontend/src/lib/components/ui/Badge.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Button.svelte.tmpl", Output: "frontend/src/lib/components/ui/Button.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Checkbox.svelte.tmpl", Output: "frontend/src/lib/components/ui/Checkbox.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/DataTable.svelte.tmpl", Output: "frontend/src/lib/components/ui/DataTable.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/ConfirmDialog.svelte.tmpl", Output: "frontend/src/lib/components/ui/ConfirmDialog.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Dialog.svelte.tmpl", Output: "frontend/src/lib/components/ui/Dialog.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/EmptyState.svelte.tmpl", Output: "frontend/src/lib/components/ui/EmptyState.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Field.browser.test.ts.tmpl", Output: "frontend/src/lib/components/ui/Field.browser.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Field.svelte.tmpl", Output: "frontend/src/lib/components/ui/Field.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/FieldProbe.svelte.tmpl", Output: "frontend/src/lib/components/ui/FieldProbe.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Icon.svelte.tmpl", Output: "frontend/src/lib/components/ui/Icon.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Input.svelte.tmpl", Output: "frontend/src/lib/components/ui/Input.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Pagination.svelte.tmpl", Output: "frontend/src/lib/components/ui/Pagination.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/ProblemAlert.svelte.tmpl", Output: "frontend/src/lib/components/ui/ProblemAlert.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Select.svelte.tmpl", Output: "frontend/src/lib/components/ui/Select.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Skeleton.svelte.tmpl", Output: "frontend/src/lib/components/ui/Skeleton.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Spinner.svelte.tmpl", Output: "frontend/src/lib/components/ui/Spinner.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Table.svelte.tmpl", Output: "frontend/src/lib/components/ui/Table.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Textarea.svelte.tmpl", Output: "frontend/src/lib/components/ui/Textarea.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Toaster.svelte.tmpl", Output: "frontend/src/lib/components/ui/Toaster.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Tooltip.svelte.tmpl", Output: "frontend/src/lib/components/ui/Tooltip.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/toast.svelte.ts.tmpl", Output: "frontend/src/lib/components/ui/toast.svelte.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/toast.test.ts.tmpl", Output: "frontend/src/lib/components/ui/toast.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Menu.browser.test.ts.tmpl", Output: "frontend/src/lib/components/ui/Menu.browser.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/Menu.svelte.tmpl", Output: "frontend/src/lib/components/ui/Menu.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/MenuProbe.svelte.tmpl", Output: "frontend/src/lib/components/ui/MenuProbe.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/components/ui/icons.ts.tmpl", Output: "frontend/src/lib/components/ui/icons.ts", Owner: OwnerApp},
	{Template: "frontend/messages/en.json.tmpl", Output: "frontend/messages/en.json", Owner: OwnerApp},
	{Template: "frontend/project.inlang/settings.json.tmpl", Output: "frontend/project.inlang/settings.json", Owner: OwnerApp, Raw: true},
	{Template: "frontend/src/lib/components/LocaleControl.svelte.tmpl", Output: "frontend/src/lib/components/LocaleControl.svelte", Owner: OwnerApp},
	{Template: "frontend/src/lib/a11y.ts.tmpl", Output: "frontend/src/lib/a11y.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/forms.svelte.ts.tmpl", Output: "frontend/src/lib/forms.svelte.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/i18n.ts.tmpl", Output: "frontend/src/lib/i18n.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/forms.test.ts.tmpl", Output: "frontend/src/lib/forms.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/navigation.ts.tmpl", Output: "frontend/src/lib/navigation.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/navigation.test.ts.tmpl", Output: "frontend/src/lib/navigation.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/session.svelte.ts.tmpl", Output: "frontend/src/lib/session.svelte.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/session.test.ts.tmpl", Output: "frontend/src/lib/session.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/shell.svelte.ts.tmpl", Output: "frontend/src/lib/shell.svelte.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/table/list-state.ts.tmpl", Output: "frontend/src/lib/table/list-state.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/table/list-state.test.ts.tmpl", Output: "frontend/src/lib/table/list-state.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/theme.svelte.ts.tmpl", Output: "frontend/src/lib/theme.svelte.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/theme.test.ts.tmpl", Output: "frontend/src/lib/theme.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/api/client.test.ts.tmpl", Output: "frontend/src/lib/api/client.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/api/client.ts.tmpl", Output: "frontend/src/lib/api/client.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/api/problem.ts.tmpl", Output: "frontend/src/lib/api/problem.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/api/problem.test.ts.tmpl", Output: "frontend/src/lib/api/problem.test.ts", Owner: OwnerApp},
	{Template: "frontend/src/lib/api/schema.d.ts.tmpl", Output: OpenAPITypescriptGeneratedPath, Owner: OwnerNise},
	{Template: "frontend/src/routes/+error.svelte.tmpl", Output: "frontend/src/routes/+error.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/+layout.svelte.tmpl", Output: "frontend/src/routes/+layout.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/+layout.ts.tmpl", Output: "frontend/src/routes/+layout.ts", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/+layout.svelte.tmpl", Output: "frontend/src/routes/(app)/+layout.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/+layout.ts.tmpl", Output: "frontend/src/routes/(app)/+layout.ts", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/account/+page.svelte.tmpl", Output: "frontend/src/routes/(app)/account/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/sign-out/+page.svelte.tmpl", Output: "frontend/src/routes/(app)/sign-out/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(public)/+layout.svelte.tmpl", Output: "frontend/src/routes/(public)/+layout.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(public)/invitations/accept/+page.svelte.tmpl", Output: "frontend/src/routes/(public)/invitations/accept/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(public)/sign-in/+page.svelte.tmpl", Output: "frontend/src/routes/(public)/sign-in/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(public)/sign-in/second-factor/+page.svelte.tmpl", Output: "frontend/src/routes/(public)/sign-in/second-factor/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/+page.svelte.tmpl", Output: "frontend/src/routes/(app)/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/settings/+page.svelte.tmpl", Output: "frontend/src/routes/(app)/settings/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/(app)/settings/about/+page.svelte.tmpl", Output: "frontend/src/routes/(app)/settings/about/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/static/favicon.svg.tmpl", Output: "frontend/static/favicon.svg", Owner: OwnerApp},
	{Template: "frontend/svelte.config.js.tmpl", Output: "frontend/svelte.config.js", Owner: OwnerApp},
	{Template: "frontend/tsconfig.json.tmpl", Output: "frontend/tsconfig.json", Owner: OwnerApp},
	{Template: "frontend/vite.config.ts.tmpl", Output: "frontend/vite.config.ts", Owner: OwnerApp},
	{Template: "frontend/vitest.config.ts.tmpl", Output: "frontend/vitest.config.ts", Owner: OwnerApp},
	{Template: "go.mod.tmpl", Output: "go.mod", Owner: OwnerApp},
	{Template: "internal/app/app.go.tmpl", Output: "internal/app/app.go", Owner: OwnerApp},
	{Template: "internal/app/database.go.tmpl", Output: "internal/app/database.go", Owner: OwnerApp},
	{Template: "internal/app/database_runtime.go.tmpl", Output: "internal/app/database_runtime.go", Owner: OwnerApp},
	{Template: "internal/app/jobs.go.tmpl", Output: "internal/app/jobs.go", Owner: OwnerApp},
	{Template: "internal/app/mail.go.tmpl", Output: "internal/app/mail.go", Owner: OwnerApp},
	{Template: "internal/app/notifications.go.tmpl", Output: "internal/app/notifications.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/app/storage.go.tmpl", Output: "internal/app/storage.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/app/modes.go.tmpl", Output: "internal/app/modes.go", Owner: OwnerApp},
	{Template: "internal/app/enroll.go.tmpl", Output: "internal/app/enroll.go", Owner: OwnerApp},
	{Template: "internal/app/password.go.tmpl", Output: "internal/app/password.go", Owner: OwnerApp},
	{Template: "internal/app/modules.gen.go.tmpl", Output: "internal/app/modules.gen.go", Owner: OwnerNise},
	{Template: "internal/app/secondfactor.go.tmpl", Output: "internal/app/secondfactor.go", Owner: OwnerApp},
	{Template: "internal/features/README.md.tmpl", Output: "internal/features/README.md", Owner: OwnerApp},
	{Template: "internal/features/auth/queries/invitations.sql.tmpl", Output: "internal/features/auth/queries/invitations.sql", Owner: OwnerApp},
	{Template: "internal/features/auth/queries/sessions.sql.tmpl", Output: "internal/features/auth/queries/sessions.sql", Owner: OwnerApp},
	{Template: "internal/features/auth/queries/users.sql.tmpl", Output: "internal/features/auth/queries/users.sql", Owner: OwnerApp},
	{Template: "internal/features/audit/audit.go.tmpl", Output: "internal/features/audit/audit.go", Owner: OwnerApp},
	{Template: "internal/features/audit/audit_test.go.tmpl", Output: "internal/features/audit/audit_test.go", Owner: OwnerApp},
	{Template: "internal/features/audit/queries/audit.sql.tmpl", Output: "internal/features/audit/queries/audit.sql", Owner: OwnerApp},
	{Template: "internal/features/audit/sqlc.yaml.tmpl", Output: "internal/features/audit/sqlc.yaml", Owner: OwnerApp, Raw: true},
	{Template: "internal/features/audit/store/db.go.tmpl", Output: "internal/features/audit/store/db.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/audit/store/models.go.tmpl", Output: "internal/features/audit/store/models.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/audit/store/querier.go.tmpl", Output: "internal/features/audit/store/querier.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/audit/store/audit.sql.go.tmpl", Output: "internal/features/audit/store/audit.sql.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/auth/accounts.go.tmpl", Output: "internal/features/auth/accounts.go", Owner: OwnerApp},
	{Template: "internal/features/auth/auth_test.go.tmpl", Output: "internal/features/auth/auth_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/invitations.go.tmpl", Output: "internal/features/auth/invitations.go", Owner: OwnerApp},
	{Template: "internal/features/auth/invitations_test.go.tmpl", Output: "internal/features/auth/invitations_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/login.go.tmpl", Output: "internal/features/auth/login.go", Owner: OwnerApp},
	{Template: "internal/features/auth/login_test.go.tmpl", Output: "internal/features/auth/login_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/reauthentication_test.go.tmpl", Output: "internal/features/auth/reauthentication_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/secondfactor.go.tmpl", Output: "internal/features/auth/secondfactor.go", Owner: OwnerApp},
	{Template: "internal/features/auth/secondfactor_test.go.tmpl", Output: "internal/features/auth/secondfactor_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/roles.go.tmpl", Output: "internal/features/auth/roles.go", Owner: OwnerApp},
	{Template: "internal/features/auth/roles_test.go.tmpl", Output: "internal/features/auth/roles_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/rotation_test.go.tmpl", Output: "internal/features/auth/rotation_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/sessions.go.tmpl", Output: "internal/features/auth/sessions.go", Owner: OwnerApp},
	{Template: "internal/features/auth/throttle_test.go.tmpl", Output: "internal/features/auth/throttle_test.go", Owner: OwnerApp},
	{Template: "internal/features/auth/sqlc.yaml.tmpl", Output: "internal/features/auth/sqlc.yaml", Owner: OwnerApp, Raw: true},
	{Template: "internal/features/auth/store/db.go.tmpl", Output: "internal/features/auth/store/db.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/auth/store/invitations.sql.go.tmpl", Output: "internal/features/auth/store/invitations.sql.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/auth/store/models.go.tmpl", Output: "internal/features/auth/store/models.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/auth/store/querier.go.tmpl", Output: "internal/features/auth/store/querier.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/auth/store/sessions.sql.go.tmpl", Output: "internal/features/auth/store/sessions.sql.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/features/auth/store/users.sql.go.tmpl", Output: "internal/features/auth/store/users.sql.go", Owner: OwnerNise, Raw: true},
	{Template: "internal/platform/config/config.go.tmpl", Output: "internal/platform/config/config.go", Owner: OwnerApp},
	{Template: "internal/platform/config/config_test.go.tmpl", Output: "internal/platform/config/config_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/README.md.tmpl", Output: "internal/platform/database/README.md", Owner: OwnerApp},
	{Template: "internal/platform/database/compatibility.go.tmpl", Output: "internal/platform/database/compatibility.go", Owner: OwnerApp},
	{Template: "internal/platform/database/compatibility_test.go.tmpl", Output: "internal/platform/database/compatibility_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/dbtest/database.go.tmpl", Output: "internal/platform/database/dbtest/database.go", Owner: OwnerApp},
	{Template: "internal/platform/database/dbtest/database_test.go.tmpl", Output: "internal/platform/database/dbtest/database_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/directpgx_test.go.tmpl", Output: "internal/platform/database/directpgx_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/migrate.go.tmpl", Output: "internal/platform/database/migrate.go", Owner: OwnerApp},
	{Template: "internal/platform/database/migrate_test.go.tmpl", Output: "internal/platform/database/migrate_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/migration_matrix_test.go.tmpl", Output: "internal/platform/database/migration_matrix_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/pool.go.tmpl", Output: "internal/platform/database/pool.go", Owner: OwnerApp},
	{Template: "internal/platform/database/pool_test.go.tmpl", Output: "internal/platform/database/pool_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/querytrace.go.tmpl", Output: "internal/platform/database/querytrace.go", Owner: OwnerApp},
	{Template: "internal/platform/database/querytrace_test.go.tmpl", Output: "internal/platform/database/querytrace_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/sqlcsafety/config.go.tmpl", Output: "internal/platform/database/sqlcsafety/config.go", Owner: OwnerApp},
	{Template: "internal/platform/database/sqlcsafety/config_test.go.tmpl", Output: "internal/platform/database/sqlcsafety/config_test.go", Owner: OwnerApp},
	{Template: "internal/platform/database/testdata/migration-upgrades/00001_baseline.sql.tmpl", Output: "internal/platform/database/testdata/migration-upgrades/00001_baseline.sql", Owner: OwnerApp},
	{Template: "internal/platform/database/transaction.go.tmpl", Output: "internal/platform/database/transaction.go", Owner: OwnerApp},
	{Template: "internal/platform/database/transaction_test.go.tmpl", Output: "internal/platform/database/transaction_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/api.go.tmpl", Output: "internal/platform/httpapi/api.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/api_test.go.tmpl", Output: "internal/platform/httpapi/api_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/httpjson/json.go.tmpl", Output: "internal/platform/httpapi/httpjson/json.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/httpjson/json_test.go.tmpl", Output: "internal/platform/httpapi/httpjson/json_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/openapigen/openapi.gen.go.tmpl", Output: OpenAPIGeneratedPath, Owner: OwnerNise},
	{Template: "internal/platform/httpapi/problem/problem.go.tmpl", Output: "internal/platform/httpapi/problem/problem.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/problem/problem_test.go.tmpl", Output: "internal/platform/httpapi/problem/problem_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/router.go.tmpl", Output: "internal/platform/httpapi/router.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/session.go.tmpl", Output: "internal/platform/httpapi/session.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/system.go.tmpl", Output: "internal/platform/httpapi/system.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/session_test.go.tmpl", Output: "internal/platform/httpapi/session_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/router_test.go.tmpl", Output: "internal/platform/httpapi/router_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/transport_test.go.tmpl", Output: "internal/platform/httpapi/transport_test.go", Owner: OwnerApp},
	{Template: "internal/features/mfa/mfa.go.tmpl", Output: "internal/features/mfa/mfa.go", Owner: OwnerApp, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/mfa_test.go.tmpl", Output: "internal/features/mfa/mfa_test.go", Owner: OwnerApp, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/queries/mfa.sql.tmpl", Output: "internal/features/mfa/queries/mfa.sql", Owner: OwnerApp, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/sqlc.yaml.tmpl", Output: "internal/features/mfa/sqlc.yaml", Owner: OwnerApp, Raw: true, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/store/db.go.tmpl", Output: "internal/features/mfa/store/db.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/store/mfa.sql.go.tmpl", Output: "internal/features/mfa/store/mfa.sql.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/store/models.go.tmpl", Output: "internal/features/mfa/store/models.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleTOTP},
	{Template: "internal/features/mfa/store/querier.go.tmpl", Output: "internal/features/mfa/store/querier.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleTOTP},
	{Template: "internal/features/notifications/convert.go.tmpl", Output: "internal/features/notifications/convert.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/deliver.go.tmpl", Output: "internal/features/notifications/deliver.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/notifications.go.tmpl", Output: "internal/features/notifications/notifications.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/notifications_test.go.tmpl", Output: "internal/features/notifications/notifications_test.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/queries/notifications.sql.tmpl", Output: "internal/features/notifications/queries/notifications.sql", Owner: OwnerApp, Raw: true, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/stream.go.tmpl", Output: "internal/features/notifications/stream.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/stream_test.go.tmpl", Output: "internal/features/notifications/stream_test.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/sqlc.yaml.tmpl", Output: "internal/features/notifications/sqlc.yaml", Owner: OwnerApp, Raw: true, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/store/db.go.tmpl", Output: "internal/features/notifications/store/db.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/store/models.go.tmpl", Output: "internal/features/notifications/store/models.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/store/notifications.sql.go.tmpl", Output: "internal/features/notifications/store/notifications.sql.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleNotifications},
	{Template: "internal/features/notifications/store/querier.go.tmpl", Output: "internal/features/notifications/store/querier.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleNotifications},
	{Template: "internal/features/organizations/convert.go.tmpl", Output: "internal/features/organizations/convert.go", Owner: OwnerApp, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/organizations.go.tmpl", Output: "internal/features/organizations/organizations.go", Owner: OwnerApp, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/organizations_test.go.tmpl", Output: "internal/features/organizations/organizations_test.go", Owner: OwnerApp, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/tenant_leak_test.go.tmpl", Output: "internal/features/organizations/tenant_leak_test.go", Owner: OwnerApp, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/queries/organizations.sql.tmpl", Output: "internal/features/organizations/queries/organizations.sql", Owner: OwnerApp, Raw: true, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/sqlc.yaml.tmpl", Output: "internal/features/organizations/sqlc.yaml", Owner: OwnerApp, Raw: true, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/store/db.go.tmpl", Output: "internal/features/organizations/store/db.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/store/models.go.tmpl", Output: "internal/features/organizations/store/models.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/store/organizations.sql.go.tmpl", Output: "internal/features/organizations/store/organizations.sql.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/organizations/store/querier.go.tmpl", Output: "internal/features/organizations/store/querier.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleOrganizations},
	{Template: "internal/features/uploads/convert.go.tmpl", Output: "internal/features/uploads/convert.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/queries/uploads.sql.tmpl", Output: "internal/features/uploads/queries/uploads.sql", Owner: OwnerApp, Raw: true, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/scan.go.tmpl", Output: "internal/features/uploads/scan.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/sweep.go.tmpl", Output: "internal/features/uploads/sweep.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/sqlc.yaml.tmpl", Output: "internal/features/uploads/sqlc.yaml", Owner: OwnerApp, Raw: true, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/store/db.go.tmpl", Output: "internal/features/uploads/store/db.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/store/models.go.tmpl", Output: "internal/features/uploads/store/models.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/store/querier.go.tmpl", Output: "internal/features/uploads/store/querier.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/store/uploads.sql.go.tmpl", Output: "internal/features/uploads/store/uploads.sql.go", Owner: OwnerNise, Raw: true, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/uploads.go.tmpl", Output: "internal/features/uploads/uploads.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/features/uploads/uploads_test.go.tmpl", Output: "internal/features/uploads/uploads_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/authorization/authorizer.go.tmpl", Output: "internal/platform/authorization/authorizer.go", Owner: OwnerApp},
	{Template: "internal/platform/authorization/authorizer_test.go.tmpl", Output: "internal/platform/authorization/authorizer_test.go", Owner: OwnerApp},
	{Template: "internal/platform/authorization/catalog.go.tmpl", Output: "internal/platform/authorization/catalog.go", Owner: OwnerApp},
	{Template: "internal/platform/authorization/catalog_test.go.tmpl", Output: "internal/platform/authorization/catalog_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/context.go.tmpl", Output: "internal/platform/httpauth/context.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/cookie.go.tmpl", Output: "internal/platform/httpauth/cookie.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/csrf.go.tmpl", Output: "internal/platform/httpauth/csrf.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/csrf_test.go.tmpl", Output: "internal/platform/httpauth/csrf_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/guard.go.tmpl", Output: "internal/platform/httpauth/guard.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/httpauth_test.go.tmpl", Output: "internal/platform/httpauth/httpauth_test.go", Owner: OwnerApp},
	{Template: "internal/platform/httpauth/middleware.go.tmpl", Output: "internal/platform/httpauth/middleware.go", Owner: OwnerApp},
	{Template: "internal/platform/idempotency/idempotency.go.tmpl", Output: "internal/platform/idempotency/idempotency.go", Owner: OwnerApp},
	{Template: "internal/platform/idempotency/idempotency_test.go.tmpl", Output: "internal/platform/idempotency/idempotency_test.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/jobs.go.tmpl", Output: "internal/platform/jobs/jobs.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/jobs_concurrency_test.go.tmpl", Output: "internal/platform/jobs/jobs_concurrency_test.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/jobs_postgres_test.go.tmpl", Output: "internal/platform/jobs/jobs_postgres_test.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/jobs_test.go.tmpl", Output: "internal/platform/jobs/jobs_test.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/periodic.go.tmpl", Output: "internal/platform/jobs/periodic.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/periodic_test.go.tmpl", Output: "internal/platform/jobs/periodic_test.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/retry.go.tmpl", Output: "internal/platform/jobs/retry.go", Owner: OwnerApp},
	{Template: "internal/platform/jobs/retry_test.go.tmpl", Output: "internal/platform/jobs/retry_test.go", Owner: OwnerApp},
	{Template: "internal/platform/mail/mail.go.tmpl", Output: "internal/platform/mail/mail.go", Owner: OwnerApp},
	{Template: "internal/platform/mail/mail_test.go.tmpl", Output: "internal/platform/mail/mail_test.go", Owner: OwnerApp},
	{Template: "internal/platform/mail/render.go.tmpl", Output: "internal/platform/mail/render.go", Owner: OwnerApp},
	{Template: "internal/platform/mail/render_test.go.tmpl", Output: "internal/platform/mail/render_test.go", Owner: OwnerApp},
	{Template: "internal/platform/mail/smtp.go.tmpl", Output: "internal/platform/mail/smtp.go", Owner: OwnerApp},
	{Template: "internal/platform/mail/smtp_test.go.tmpl", Output: "internal/platform/mail/smtp_test.go", Owner: OwnerApp},
	// The message templates carry the generated application's own template
	// delimiters, which are Go's and therefore Nise's. Raw copies their
	// bytes so `{{.AcceptURL}}` reaches the application instead of being
	// resolved against Nise's generation data — the same reason the
	// vendored sqlc and oapi-codegen configs are raw.
	{Template: "internal/platform/mail/templates/README.md.tmpl", Output: "internal/platform/mail/templates/README.md", Owner: OwnerApp, Raw: true},
	{Template: "internal/platform/mail/templates/invitation.html.tmpl", Output: "internal/platform/mail/templates/invitation.html", Owner: OwnerApp, Raw: true},
	{Template: "internal/platform/mail/templates/invitation.txt.tmpl", Output: "internal/platform/mail/templates/invitation.txt", Owner: OwnerApp, Raw: true},
	// The uploads module's storage layer. Absent entirely when the module
	// was not selected — no import, no dead code, and no configuration
	// variable for a subsystem that is not there.
	{Template: "internal/platform/sse/sse.go.tmpl", Output: "internal/platform/sse/sse.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/platform/sse/sse_test.go.tmpl", Output: "internal/platform/sse/sse_test.go", Owner: OwnerApp, Module: recipe.ModuleNotifications},
	{Template: "internal/platform/storage/local.go.tmpl", Output: "internal/platform/storage/local.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/local_test.go.tmpl", Output: "internal/platform/storage/local_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/modes_unix_test.go.tmpl", Output: "internal/platform/storage/modes_unix_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/modes_windows_test.go.tmpl", Output: "internal/platform/storage/modes_windows_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/s3.go.tmpl", Output: "internal/platform/storage/s3.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/s3_integration_test.go.tmpl", Output: "internal/platform/storage/s3_integration_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/s3_test.go.tmpl", Output: "internal/platform/storage/s3_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/sigv4.go.tmpl", Output: "internal/platform/storage/sigv4.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/sigv4_test.go.tmpl", Output: "internal/platform/storage/sigv4_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/storage.go.tmpl", Output: "internal/platform/storage/storage.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/storage/storage_test.go.tmpl", Output: "internal/platform/storage/storage_test.go", Owner: OwnerApp, Module: recipe.ModuleUploads},
	{Template: "internal/platform/passwords/passwords.go.tmpl", Output: "internal/platform/passwords/passwords.go", Owner: OwnerApp},
	{Template: "internal/platform/reauth/matrix.go.tmpl", Output: "internal/platform/reauth/matrix.go", Owner: OwnerApp},
	{Template: "internal/platform/reauth/reauth_test.go.tmpl", Output: "internal/platform/reauth/reauth_test.go", Owner: OwnerApp},
	{Template: "internal/platform/reauth/require.go.tmpl", Output: "internal/platform/reauth/require.go", Owner: OwnerApp},
	{Template: "internal/platform/throttle/throttle.go.tmpl", Output: "internal/platform/throttle/throttle.go", Owner: OwnerApp},
	{Template: "internal/platform/throttle/throttle_test.go.tmpl", Output: "internal/platform/throttle/throttle_test.go", Owner: OwnerApp},
	{Template: "internal/platform/passwords/passwords_test.go.tmpl", Output: "internal/platform/passwords/passwords_test.go", Owner: OwnerApp},
	{Template: "internal/platform/webui/embedded/placeholder.html.tmpl", Output: "internal/platform/webui/embedded/placeholder.html", Owner: OwnerNise},
	{Template: "internal/platform/webui/webui.go.tmpl", Output: "internal/platform/webui/webui.go", Owner: OwnerNise},
}

// TemplatePaths returns every template path this package renders, sorted.
// It exists so a test can compare the manifest against the embedded
// filesystem without reaching into unexported state.
func TemplatePaths() []string {
	out := make([]string, 0, len(templateFiles))
	for _, tf := range templateFiles {
		out = append(out, tf.Template)
	}
	return out
}
