package generator

// Ownership is the ownership model a generated file declares, per ADR 0003
// and docs/generated-application-layout.md.
type Ownership string

const (
	// OwnerNise marks a file Nise regenerates. Hand edits are lost. Every
	// such file carries NiseOwnedHeader in its own comment syntax, in the
	// exact spelling Go's generated-code convention defines, so linters,
	// diff tools, and a later nise generate all recognize it without a
	// manifest.
	OwnerNise Ownership = "nise"
	// OwnerApp marks a file the application owns. Nise writes it once and
	// never overwrites it.
	OwnerApp Ownership = "app"
)

// The two ownership headers. Neither records a Nise version: a version in
// the header would rewrite every file on every CLI upgrade and defeat the
// clean-regeneration check.
const (
	// NiseOwnedHeader marks a regenerated file. It matches Go's
	// `^// Code generated .* DO NOT EDIT\.$` convention exactly, which is
	// what makes it machine-readable rather than merely prose.
	NiseOwnedHeader = "Code generated by nise; DO NOT EDIT."
	// AppOwnedHeader marks a file written once and never overwritten.
	AppOwnedHeader = "Generated once by nise; owned by this application. Nise will not overwrite it."
)

// templateRoot is the directory inside the embedded template filesystem
// holding the nise new templates.
const templateRoot = "new"

// templateFile maps one embedded template to the path it is written to.
type templateFile struct {
	// Template is the path inside templates/new, without the leading
	// "new/" and with its .tmpl suffix.
	Template string
	// Output is the generated file's path relative to the project root. It
	// is itself a template, because one output path depends on the
	// application's name.
	Output string
	// Owner is the ownership model the file's own header declares. It is
	// recorded here as well so a test can assert that the header in the
	// rendered bytes and the manifest agree — a header is easy to copy
	// wrong when a template is added by hand.
	Owner Ownership
}

// templateFiles is every template nise new renders, sorted by output path.
//
// The mapping is explicit rather than derived from the template's own path
// for two reasons. Three output paths cannot be spelled as template paths
// at all: ".gitignore" and ".env.example" would be swallowed by this
// repository's own .gitignore, and cmd/<app>/main.go's directory is not
// known until generation time. And an explicit table is the thing a reviewer
// can read to know what a generated project contains, which a suffix-
// stripping rule is not.
//
// TestEveryTemplateIsInTheManifest asserts this list and the embedded
// filesystem name exactly the same set of files, so a template added
// without a manifest entry fails the build rather than being silently
// skipped.
var templateFiles = []templateFile{
	{Template: "env.example.tmpl", Output: ".env.example", Owner: OwnerApp},
	{Template: "gitignore.tmpl", Output: ".gitignore", Owner: OwnerApp},
	{Template: "Makefile.tmpl", Output: "Makefile", Owner: OwnerApp},
	{Template: "README.md.tmpl", Output: "README.md", Owner: OwnerApp},
	{Template: "api/README.md.tmpl", Output: "api/README.md", Owner: OwnerApp},
	{Template: "cmd/main.go.tmpl", Output: "cmd/{{.AppName}}/main.go", Owner: OwnerApp},
	{Template: "db/README.md.tmpl", Output: "db/README.md", Owner: OwnerApp},
	{Template: "deploy/Dockerfile.tmpl", Output: "deploy/Dockerfile", Owner: OwnerApp},
	{Template: "deploy/README.md.tmpl", Output: "deploy/README.md", Owner: OwnerApp},
	{Template: "deploy/compose.yaml.tmpl", Output: "deploy/compose.yaml", Owner: OwnerApp},
	{Template: "frontend/README.md.tmpl", Output: "frontend/README.md", Owner: OwnerApp},
	{Template: "frontend/gitignore.tmpl", Output: "frontend/.gitignore", Owner: OwnerApp},
	{Template: "frontend/package.json.tmpl", Output: "frontend/package.json", Owner: OwnerApp},
	{Template: "frontend/src/app.css.tmpl", Output: "frontend/src/app.css", Owner: OwnerApp},
	{Template: "frontend/src/app.d.ts.tmpl", Output: "frontend/src/app.d.ts", Owner: OwnerApp},
	{Template: "frontend/src/app.html.tmpl", Output: "frontend/src/app.html", Owner: OwnerApp},
	{Template: "frontend/src/routes/+layout.svelte.tmpl", Output: "frontend/src/routes/+layout.svelte", Owner: OwnerApp},
	{Template: "frontend/src/routes/+layout.ts.tmpl", Output: "frontend/src/routes/+layout.ts", Owner: OwnerApp},
	{Template: "frontend/src/routes/+page.svelte.tmpl", Output: "frontend/src/routes/+page.svelte", Owner: OwnerApp},
	{Template: "frontend/static/favicon.svg.tmpl", Output: "frontend/static/favicon.svg", Owner: OwnerApp},
	{Template: "frontend/svelte.config.js.tmpl", Output: "frontend/svelte.config.js", Owner: OwnerApp},
	{Template: "frontend/tsconfig.json.tmpl", Output: "frontend/tsconfig.json", Owner: OwnerApp},
	{Template: "frontend/vite.config.ts.tmpl", Output: "frontend/vite.config.ts", Owner: OwnerApp},
	{Template: "go.mod.tmpl", Output: "go.mod", Owner: OwnerApp},
	{Template: "internal/app/app.go.tmpl", Output: "internal/app/app.go", Owner: OwnerApp},
	{Template: "internal/app/modes.go.tmpl", Output: "internal/app/modes.go", Owner: OwnerApp},
	{Template: "internal/app/modules.gen.go.tmpl", Output: "internal/app/modules.gen.go", Owner: OwnerNise},
	{Template: "internal/features/README.md.tmpl", Output: "internal/features/README.md", Owner: OwnerApp},
	{Template: "internal/platform/config/config.go.tmpl", Output: "internal/platform/config/config.go", Owner: OwnerApp},
	{Template: "internal/platform/database/README.md.tmpl", Output: "internal/platform/database/README.md", Owner: OwnerApp},
	{Template: "internal/platform/httpapi/router.go.tmpl", Output: "internal/platform/httpapi/router.go", Owner: OwnerApp},
	{Template: "internal/platform/webui/embedded/placeholder.html.tmpl", Output: "internal/platform/webui/embedded/placeholder.html", Owner: OwnerNise},
	{Template: "internal/platform/webui/webui.go.tmpl", Output: "internal/platform/webui/webui.go", Owner: OwnerNise},
}

// TemplatePaths returns every template path this package renders, sorted.
// It exists so a test can compare the manifest against the embedded
// filesystem without reaching into unexported state.
func TemplatePaths() []string {
	out := make([]string, 0, len(templateFiles))
	for _, tf := range templateFiles {
		out = append(out, tf.Template)
	}
	return out
}
