package generator_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/drilonrecica/nise-and-go/internal/generator"
)

// TestGeneratedProjectRunsColocatedSQLCConfigs catches a feature config
// being undiscoverable, resolving paths from the repository root instead of
// the feature, or emitting generated code outside that feature's store
// directory. It runs the real pinned sqlc binary against a real generated
// project; no parser imitation is involved.
func TestGeneratedProjectRunsColocatedSQLCConfigs(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping: this test builds the generated project's pinned sqlc tool")
	}
	makeBin, err := exec.LookPath("make")
	if err != nil {
		t.Skipf("skipping: make is unavailable: %v", err)
	}
	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skipf("skipping: go is unavailable: %v", err)
	}

	root := filepath.Join(t.TempDir(), "sqlcprobe")
	if _, err := generator.Write(root, generator.Options{
		Name:       "sqlcprobe",
		ModulePath: "example.com/sqlcprobe",
		CLIVersion: fixedVersion,
	}); err != nil {
		t.Fatalf("Write: %v", err)
	}

	feature := filepath.Join(root, "internal", "features", "widgets")
	queries := filepath.Join(feature, "queries")
	if err := os.MkdirAll(queries, 0o750); err != nil {
		t.Fatalf("create feature query directory: %v", err)
	}
	writeProbeFile(t, filepath.Join(feature, "schema.sql"), `
CREATE TABLE widgets (
    id bigint PRIMARY KEY,
    name text NOT NULL
);
`)
	writeProbeFile(t, filepath.Join(queries, "widgets.sql"), `
-- name: ListWidgets :many
SELECT id, name
FROM widgets
ORDER BY id;

-- name: RenameWidget :execrows
UPDATE widgets
SET name = $1
WHERE id = $2;

-- name: DeleteWidget :execrows
DELETE FROM widgets
WHERE id = $1;
`)
	writeProbeFile(t, filepath.Join(feature, "sqlc.yaml"), `
version: "2"
sql:
  - name: widgets
    engine: postgresql
    schema: schema.sql
    queries: queries
    gen:
      go:
        package: store
        out: store
        sql_package: pgx/v5
        emit_interface: true
        emit_empty_slices: true
        query_parameter_limit: 0
        omit_unused_structs: true
    rules:
      - nise-no-unbounded-delete
      - nise-no-unbounded-update
      - nise-no-truncate
rules:
  - name: nise-no-unbounded-delete
    message: "DELETE statements must contain a WHERE clause"
    rule: |
      query.sql.matches("(?is).*\\bDELETE\\s+FROM\\b.*") &&
      !query.sql.matches("(?is).*\\bDELETE\\s+FROM\\b.*\\bWHERE\\b.*")
  - name: nise-no-unbounded-update
    message: "UPDATE statements must contain a WHERE clause"
    rule: |
      query.sql.matches("(?is).*\\bUPDATE\\b.*\\bSET\\b.*") &&
      !query.sql.matches("(?is).*\\bUPDATE\\b.*\\bSET\\b.*\\bWHERE\\b.*")
  - name: nise-no-truncate
    message: "TRUNCATE is forbidden in application queries; use an explicit migration"
    rule: |
      query.sql.matches("(?is).*\\bTRUNCATE\\b.*")
`)

	run := func(bin string, args ...string) string {
		t.Helper()
		cmd := exec.Command(bin, args...) // #nosec G204 -- bin is resolved above and args are fixed test inputs.
		cmd.Dir = root
		cmd.Env = append(os.Environ(), "GOTOOLCHAIN=local", "GOFLAGS=-mod=mod")
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("%s %s: %v\n%s", bin, strings.Join(args, " "), err, out)
		}
		return string(out)
	}

	frameworkRoot := findFrameworkRoot(t)
	run(goBin, "mod", "edit", "-replace", generator.NiseModulePath+"="+frameworkRoot)
	run(goBin, "mod", "tidy")
	run(makeBin, "sqlc-compile")
	run(makeBin, "sqlc-vet")
	run(makeBin, "sqlc-generate")

	store := filepath.Join(feature, "store")
	entries, err := os.ReadDir(store)
	if err != nil {
		t.Fatalf("read generated store: %v", err)
	}
	if len(entries) == 0 {
		t.Fatal("sqlc generated no files")
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			t.Errorf("store entry %q is not a generated Go file", entry.Name())
			continue
		}
		data, err := os.ReadFile(filepath.Join(store, entry.Name())) // #nosec G304 -- entry came from the test-owned store directory.
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		if !strings.Contains(string(data), "Code generated by sqlc. DO NOT EDIT.") {
			t.Errorf("%s lacks sqlc's generated ownership marker", entry.Name())
		}
	}
	run(goBin, "test", "./internal/features/widgets/store")

	for _, tc := range []struct {
		name    string
		query   string
		message string
	}{
		{
			name:    "unbounded delete",
			query:   "-- name: DeleteWidgets :exec\nDELETE FROM widgets;",
			message: "DELETE statements must contain a WHERE clause",
		},
		{
			name:    "unbounded update",
			query:   "-- name: RenameWidgets :exec\nUPDATE widgets SET name = 'unsafe';",
			message: "UPDATE statements must contain a WHERE clause",
		},
		{
			name:    "truncate",
			query:   "-- name: TruncateWidgets :exec\nTRUNCATE widgets;",
			message: "TRUNCATE is forbidden in application queries",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			writeProbeFile(t, filepath.Join(queries, "widgets.sql"), tc.query)
			cmd := exec.Command(makeBin, "sqlc-vet") // #nosec G204 -- makeBin is resolved above and argv is fixed.
			cmd.Dir = root
			cmd.Env = append(os.Environ(), "GOTOOLCHAIN=local", "GOFLAGS=-mod=mod")
			out, err := cmd.CombinedOutput()
			if err == nil {
				t.Fatalf("make sqlc-vet accepted %s", tc.name)
			}
			if !strings.Contains(string(out), tc.message) {
				t.Fatalf("make sqlc-vet output lacks %q:\n%s", tc.message, out)
			}
		})
	}

	writeProbeFile(t, filepath.Join(queries, "widgets.sql"), `
-- name: ListWidgets :many
SELECT id, name
FROM widgets
ORDER BY id;
`)
	configPath := filepath.Join(feature, "sqlc.yaml")
	config, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("read sqlc config: %v", err)
	}
	writeProbeFile(t, configPath, strings.Replace(string(config), "out: store", "out: ../../forbidden", 1))
	cmd := exec.Command(makeBin, "sqlc-vet") // #nosec G204 -- makeBin is resolved above and argv is fixed.
	cmd.Dir = root
	cmd.Env = append(os.Environ(), "GOTOOLCHAIN=local", "GOFLAGS=-mod=mod")
	out, err := cmd.CombinedOutput()
	if err == nil {
		t.Fatal("make sqlc-vet accepted generated output outside the feature-local store")
	}
	if !strings.Contains(string(out), "sqlc Go output must be exactly store") {
		t.Fatalf("forbidden output failure lacks safety guidance:\n%s", out)
	}
}

// TestGeneratedSQLCTargetsAreHonestWithNoFeatures keeps the Makefile's
// empty-tree behavior tested now that a generated project ships query-owning
// features. The property belongs to the Makefile, not to the templates: an
// application that removes or has not yet added a query-owning feature must
// still get an explicit message rather than a confusing success or failure.
func TestGeneratedSQLCTargetsAreHonestWithNoFeatures(t *testing.T) {
	makeBin, err := exec.LookPath("make")
	if err != nil {
		t.Skipf("skipping: make is unavailable: %v", err)
	}
	root := filepath.Join(t.TempDir(), "emptyprobe")
	if _, err := generator.Write(root, generator.Options{
		Name:       "emptyprobe",
		ModulePath: "example.com/emptyprobe",
		CLIVersion: fixedVersion,
	}); err != nil {
		t.Fatalf("Write: %v", err)
	}
	// Remove whatever query-owning features this generation shipped, without
	// naming them: the property under test belongs to the Makefile, and a
	// list here would break the day a third feature is added.
	featureRoot := filepath.Join(root, "internal", "features")
	entries, err := os.ReadDir(featureRoot)
	if err != nil {
		t.Fatalf("read the feature directory: %v", err)
	}
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		if err := os.RemoveAll(filepath.Join(featureRoot, entry.Name())); err != nil {
			t.Fatalf("remove feature %s: %v", entry.Name(), err)
		}
	}
	for _, target := range []string{"sqlc-compile", "sqlc-vet", "sqlc-generate"} {
		cmd := exec.Command(makeBin, "--no-print-directory", target) // #nosec G204 -- makeBin is resolved and args are fixed literals.
		cmd.Dir = root
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("make %s: %v\n%s", target, err, out)
		}
		if got := strings.TrimSpace(string(out)); got != "no feature-local sqlc.yaml files found" {
			t.Errorf("make %s output = %q, want explicit empty-feature message", target, got)
		}
	}
}

func writeProbeFile(t *testing.T, path, body string) {
	t.Helper()
	// #nosec G703 -- every caller constructs path beneath this test's t.TempDir-owned generated project.
	if err := os.WriteFile(path, []byte(strings.TrimSpace(body)+"\n"), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
