package generator_test

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/drilonrecica/nise-and-go/internal/generator"
)

// TestGeneratedProjectRunsColocatedSQLCConfigs catches a feature config
// being undiscoverable, resolving paths from the repository root instead of
// the feature, or emitting generated code outside that feature's store
// directory. It runs the real pinned sqlc binary against a real generated
// project; no parser imitation is involved.
func TestGeneratedProjectRunsColocatedSQLCConfigs(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping: this test builds the generated project's pinned sqlc tool")
	}
	makeBin, err := exec.LookPath("make")
	if err != nil {
		t.Skipf("skipping: make is unavailable: %v", err)
	}
	goBin, err := exec.LookPath("go")
	if err != nil {
		t.Skipf("skipping: go is unavailable: %v", err)
	}

	root := filepath.Join(t.TempDir(), "sqlcprobe")
	if _, err := generator.Write(root, generator.Options{
		Name:       "sqlcprobe",
		ModulePath: "example.com/sqlcprobe",
		CLIVersion: fixedVersion,
	}); err != nil {
		t.Fatalf("Write: %v", err)
	}

	feature := filepath.Join(root, "internal", "features", "widgets")
	queries := filepath.Join(feature, "queries")
	if err := os.MkdirAll(queries, 0o750); err != nil {
		t.Fatalf("create feature query directory: %v", err)
	}
	writeProbeFile(t, filepath.Join(feature, "schema.sql"), `
CREATE TABLE widgets (
    id bigint PRIMARY KEY,
    name text NOT NULL
);
`)
	writeProbeFile(t, filepath.Join(queries, "widgets.sql"), `
-- name: ListWidgets :many
SELECT id, name
FROM widgets
ORDER BY id;
`)
	writeProbeFile(t, filepath.Join(feature, "sqlc.yaml"), `
version: "2"
sql:
  - name: widgets
    engine: postgresql
    schema: schema.sql
    queries: queries
    gen:
      go:
        package: store
        out: store
        sql_package: pgx/v5
        emit_interface: true
        emit_empty_slices: true
        query_parameter_limit: 0
        omit_unused_structs: true
`)

	run := func(bin string, args ...string) string {
		t.Helper()
		cmd := exec.Command(bin, args...) // #nosec G204 -- bin is resolved above and args are fixed test inputs.
		cmd.Dir = root
		cmd.Env = append(os.Environ(), "GOTOOLCHAIN=local", "GOFLAGS=-mod=mod")
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("%s %s: %v\n%s", bin, strings.Join(args, " "), err, out)
		}
		return string(out)
	}

	frameworkRoot := findFrameworkRoot(t)
	run(goBin, "mod", "edit", "-replace", generator.NiseModulePath+"="+frameworkRoot)
	run(goBin, "mod", "tidy")
	run(makeBin, "sqlc-compile")
	run(makeBin, "sqlc-generate")

	store := filepath.Join(feature, "store")
	entries, err := os.ReadDir(store)
	if err != nil {
		t.Fatalf("read generated store: %v", err)
	}
	if len(entries) == 0 {
		t.Fatal("sqlc generated no files")
	}
	for _, entry := range entries {
		if entry.IsDir() || filepath.Ext(entry.Name()) != ".go" {
			t.Errorf("store entry %q is not a generated Go file", entry.Name())
			continue
		}
		data, err := os.ReadFile(filepath.Join(store, entry.Name())) // #nosec G304 -- entry came from the test-owned store directory.
		if err != nil {
			t.Fatalf("read %s: %v", entry.Name(), err)
		}
		if !strings.Contains(string(data), "Code generated by sqlc. DO NOT EDIT.") {
			t.Errorf("%s lacks sqlc's generated ownership marker", entry.Name())
		}
	}
	run(goBin, "test", "./internal/features/widgets/store")
}

func TestGeneratedSQLCTargetsAreHonestBeforeFirstFeature(t *testing.T) {
	makeBin, err := exec.LookPath("make")
	if err != nil {
		t.Skipf("skipping: make is unavailable: %v", err)
	}
	root := filepath.Join(t.TempDir(), "emptyprobe")
	if _, err := generator.Write(root, generator.Options{
		Name:       "emptyprobe",
		ModulePath: "example.com/emptyprobe",
		CLIVersion: fixedVersion,
	}); err != nil {
		t.Fatalf("Write: %v", err)
	}
	for _, target := range []string{"sqlc-compile", "sqlc-generate"} {
		cmd := exec.Command(makeBin, "--no-print-directory", target) // #nosec G204 -- makeBin is resolved and args are fixed literals.
		cmd.Dir = root
		out, err := cmd.CombinedOutput()
		if err != nil {
			t.Fatalf("make %s: %v\n%s", target, err, out)
		}
		if got := strings.TrimSpace(string(out)); got != "no feature-local sqlc.yaml files found" {
			t.Errorf("make %s output = %q, want explicit empty-feature message", target, got)
		}
	}
}

func writeProbeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(strings.TrimSpace(body)+"\n"), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}
