package generator_test

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/drilonrecica/nise-and-go/internal/generator"
)

func TestGeneratedProjectDefinesTypedFrontendClient(t *testing.T) {
	t.Parallel()

	files, err := generator.Plan(defaultOptions())
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	content := make(map[string]string, len(files))
	for _, file := range files {
		content[file.Path] = string(file.Content)
	}

	wants := map[string][]string{
		"frontend/src/lib/api/schema.d.ts": {
			"This file was auto-generated by openapi-typescript.",
			"export interface paths",
			`get: operations["getAPIIndex"]`,
		},
		"frontend/src/lib/api/client.ts": {
			`import type { paths } from './schema'`,
			"credentials: 'same-origin'",
			"signal: chosen.signal",
			"export class APIError extends Error",
			"export class APITransportError extends Error",
		},
		"frontend/src/lib/api/client.test.ts": {
			"returns the direct resource without an envelope",
			"maps HTTP failures without exposing their body in the message",
			"preserves cancellation errors",
		},
		"frontend/vitest.config.ts": {
			"defineConfig",
			"environment: 'node'",
		},
		"frontend/package.json": {
			`"api:generate": "openapi-typescript ../api/openapi.yaml -o src/lib/api/schema.d.ts"`,
			`"api:check": "openapi-typescript ../api/openapi.yaml -o src/lib/api/schema.d.ts --check"`,
			`"test:unit": "pnpm run messages:compile && svelte-kit sync && vitest run --project unit"`,
			`"openapi-typescript": "7.13.0"`,
			`"vitest": "4.1.11"`,
		},
		"Makefile": {
			"api-types-generate:",
			"api-types-check:",
			"pnpm --dir frontend run api:check",
			"web-test: web-check",
		},
		"deploy/Dockerfile": {
			"COPY api/openapi.yaml ./api/openapi.yaml",
			"RUN pnpm --dir frontend build",
		},
	}

	for path, fragments := range wants {
		body, exists := content[path]
		if !exists {
			t.Errorf("generated project lacks %s", path)
			continue
		}
		for _, fragment := range fragments {
			if !strings.Contains(body, fragment) {
				t.Errorf("%s lacks %q", path, fragment)
			}
		}
	}
}

func TestGeneratedTypeScriptClientIsReproducible(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping: this test installs and runs the generated frontend's pinned tools")
	}
	pnpmBin, err := exec.LookPath("pnpm")
	if err != nil {
		t.Skipf("skipping: no pnpm binary on PATH: %v", err)
	}

	root := filepath.Join(t.TempDir(), "typescriptprobe")
	if _, err := generator.Write(root, generator.Options{
		Name:       "typescriptprobe",
		ModulePath: "example.com/typescriptprobe",
		CLIVersion: fixedVersion,
	}); err != nil {
		t.Fatalf("Write: %v", err)
	}

	run := func(args ...string) (string, error) {
		cmd := exec.Command(pnpmBin, args...) // #nosec G204 -- command and arguments are fixed by this test.
		cmd.Dir = root
		cmd.Env = append(os.Environ(), "CI=false", "COREPACK_ENABLE_DOWNLOAD_PROMPT=0")
		out, err := cmd.CombinedOutput()
		return string(out), err
	}

	installOutput, err := run("--dir", "frontend", "install", "--ignore-scripts")
	if err != nil {
		t.Skipf("skipping: generated frontend dependencies could not be resolved: %v\n%s", err, installOutput)
	}
	if strings.Contains(installOutput, "unmet peer") {
		t.Fatalf("generated frontend has an unsupported dependency pair:\n%s", installOutput)
	}

	for _, tool := range []struct {
		name    string
		command []string
		version string
	}{
		{name: "openapi-typescript", command: []string{"--dir", "frontend", "exec", "openapi-typescript", "--version"}, version: generator.OpenAPITypescriptVersion},
		{name: "TypeScript", command: []string{"--dir", "frontend", "exec", "tsc", "--version"}, version: generator.TypeScriptVersion},
		{name: "Vitest", command: []string{"--dir", "frontend", "exec", "vitest", "--version"}, version: generator.VitestVersion},
	} {
		out, err := run(tool.command...)
		if err != nil {
			t.Fatalf("%s version: %v\n%s", tool.name, err, out)
		}
		if !strings.Contains(out, tool.version) {
			t.Fatalf("%s version output = %q, want %s", tool.name, out, tool.version)
		}
	}

	for _, script := range []string{"api:check", "test:unit", "check"} {
		if out, err := run("--dir", "frontend", "run", script); err != nil {
			t.Fatalf("pnpm %s: %v\n%s", script, err, out)
		}
	}

	schemaPath := filepath.Join(root, "frontend", "src", "lib", "api", "schema.d.ts")
	original, err := os.ReadFile(schemaPath) // #nosec G304 -- fixed child of this test's t.TempDir project.
	if err != nil {
		t.Fatalf("read generated schema: %v", err)
	}
	corrupted := append(bytes.Clone(original), []byte("\n// stale probe\n")...)
	// #nosec G703 -- schemaPath is a fixed child of this test's t.TempDir project.
	if err := os.WriteFile(schemaPath, corrupted, generator.FileMode); err != nil {
		t.Fatalf("corrupt generated schema: %v", err)
	}
	if out, err := run("--dir", "frontend", "run", "api:check"); err == nil {
		t.Fatal("api:check accepted stale TypeScript models")
	} else if !strings.Contains(out, "Generated types are not up-to-date") {
		t.Fatalf("stale api:check output = %q", out)
	}
	stillCorrupted, err := os.ReadFile(schemaPath) // #nosec G304 -- fixed child of this test's t.TempDir project.
	if err != nil {
		t.Fatalf("read schema after api:check: %v", err)
	}
	if !bytes.Equal(stillCorrupted, corrupted) {
		t.Fatal("api:check mutated the checked-in TypeScript models")
	}

	if out, err := run("--dir", "frontend", "run", "api:generate"); err != nil {
		t.Fatalf("api:generate: %v\n%s", err, out)
	}
	regenerated, err := os.ReadFile(schemaPath) // #nosec G304 -- fixed child of this test's t.TempDir project.
	if err != nil {
		t.Fatalf("read regenerated schema: %v", err)
	}
	if !bytes.Equal(regenerated, original) {
		t.Fatal("api:generate did not reproduce the checked-in TypeScript models byte-for-byte")
	}

	specPath := filepath.Join(root, "api", "openapi.yaml")
	// #nosec G703 -- specPath is a fixed child of this test's t.TempDir project.
	if err := os.WriteFile(specPath, []byte("openapi: [\n"), generator.FileMode); err != nil {
		t.Fatalf("write invalid OpenAPI probe: %v", err)
	}
	if out, err := run("--dir", "frontend", "run", "api:generate"); err == nil {
		t.Fatal("api:generate accepted an invalid OpenAPI document")
	} else if strings.TrimSpace(out) == "" {
		t.Fatal("invalid api:generate failed without a diagnostic")
	}
	afterInvalid, err := os.ReadFile(schemaPath) // #nosec G304 -- fixed child of this test's t.TempDir project.
	if err != nil {
		t.Fatalf("read schema after invalid generation: %v", err)
	}
	if !bytes.Equal(afterInvalid, original) {
		t.Fatal("failed TypeScript generation damaged the last valid checked-in models")
	}
}
