package generator

// The versions a generated project is pinned to. Every one of them is a
// literal here rather than a value read from the environment, the build, or
// the network: generation must produce byte-identical output on every
// machine, and a version resolved at generation time would make the output
// depend on when it ran.
//
// Bumping any of these is a deliberate edit with a corresponding line in
// docs/dependencies.md, the same way adding a dependency is.
const (
	// NiseModulePath is the framework module a generated application
	// imports runtime/ from.
	NiseModulePath = "github.com/drilonrecica/nise-and-go"

	// NiseModuleVersion is the framework version the generated go.mod
	// requires. It is deliberately separate from the recipe's
	// runtimeVersion field: the recipe records the version of the nise
	// binary that generated the project, which for a source build is the
	// non-module string "dev", while go.mod needs a resolvable module
	// version.
	NiseModuleVersion = "v0.1.0"

	// ChiVersion pins the HTTP router, the one non-Nise Go dependency a
	// generated project starts with.
	ChiVersion = "v5.3.2"

	// PgxVersion pins the PostgreSQL driver and pool used by generated
	// applications.
	PgxVersion = "v5.10.0"

	// SQLCVersion pins the query-code generator in generated projects.
	SQLCVersion = "v1.31.1"

	// GooseVersion pins the migration library and command in generated
	// projects. The application imports the provider API at runtime and also
	// declares the command as a Go tool for explicit operator workflows.
	GooseVersion = "v3.27.3"

	// XCryptoVersion pins golang.org/x/crypto, reached by generated
	// applications through runtime/password's Argon2id hashing. It is the
	// one non-standard-library dependency any runtime package has.
	XCryptoVersion = "v0.54.0"

	// OAPICodegenVersion pins the generator that turns the authoritative
	// OpenAPI document into strict chi server bindings.
	OAPICodegenVersion = "v2.8.0"

	// OAPIRuntimeVersion pins the small runtime the generated bindings
	// import to bind path and query parameters. It is not a framework
	// choice: it is the library the pinned generator's own output requires,
	// and it enters the generated go.mod for the same reason the output
	// does.
	OAPIRuntimeVersion = "v1.7.0"

	// OAPICodegenGeneratedHeader is the exact standard ownership marker the
	// pinned generator writes. Keeping the version in the marker is useful:
	// it lets ownership checks distinguish reproducible tool output from a
	// file produced by some other oapi-codegen release.
	OAPICodegenGeneratedHeader = "Code generated by github.com/oapi-codegen/oapi-codegen/v2 version " + OAPICodegenVersion + " DO NOT EDIT."

	// GoDirective is the go directive written into the generated go.mod.
	// It is the three-component form `go mod tidy` produces, so the first
	// tidy in a new project does not rewrite the file nise just wrote.
	GoDirective = "1.26.0"

	// GoImageTag is the golang container image tag the generated
	// Dockerfile builds with.
	GoImageTag = "1.26"

	// NodeVersion is the minimum Node version the generated frontend
	// declares in its engines field.
	NodeVersion = "22.22.2"

	// NodeMajor is the node container image tag the generated Dockerfile
	// builds the frontend with.
	NodeMajor = "22"

	// PnpmVersion is the pnpm version the generated package.json pins
	// through its packageManager field, so Corepack activates exactly this
	// one per project.
	PnpmVersion = "10.33.0"

	// OpenAPITypescriptVersion pins frontend type generation from the same
	// authoritative document as the strict Go server bindings.
	OpenAPITypescriptVersion = "7.13.0"

	// TypeScriptVersion is the newest TypeScript release in the major range
	// openapi-typescript declares compatible.
	TypeScriptVersion = "5.9.3"

	// VitestVersion pins the Node-based unit runner used for the generated
	// frontend's application-owned TypeScript contracts.
	VitestVersion = "4.1.11"

	// ValibotVersion pins the schema library the generated forms validate
	// with in the browser. It is the generated frontend's first package that
	// ships in the bundle rather than only building it.
	ValibotVersion = "1.1.0"

	// ParaglideVersion pins the compile-time internationalization toolchain.
	// It is a build tool, not a bundled package: messages compile to modules,
	// so what ships is the messages the application actually imports.
	ParaglideVersion = "2.25.0"

	// MessageFormatPluginVersion pins the inlang plugin that reads
	// messages/*.json. It is an ordinary devDependency, resolved from
	// node_modules by the settings file, rather than the CDN URL inlang's
	// own documentation uses: a build step that fetches an unpinned script
	// from a content delivery network is a supply-chain surface, and a
	// lockfile entry is not.
	MessageFormatPluginVersion = "4.1.0"

	// TableCoreVersion pins the framework-agnostic table primitive the
	// generated DataTable wraps. It is the 8.x line rather than the newer
	// 9.x: 9's core delegates reactivity to a per-framework adapter feature,
	// and constructing a table without one throws, so 9 is not usable from a
	// Nise-owned Svelte wrapper until a Svelte adapter exists.
	TableCoreVersion = "8.21.3"
)

// Dependency is one pinned frontend package.
type Dependency struct {
	// Name is the npm package name.
	Name string
	// Version is an exact version, never a range: a generated project is
	// reproducible from the moment it is created, before a lockfile exists.
	Version string
}

// frontendRuntimeDependencies is the generated package.json's dependencies:
// the packages that ship in the bundle rather than only building it. The list
// is short on purpose, and every entry is one docs/dependencies.md justifies.
var frontendRuntimeDependencies = []Dependency{
	{Name: "@tanstack/table-core", Version: TableCoreVersion},
	{Name: "valibot", Version: ValibotVersion},
}

// FrontendRuntimeDependencies returns the pinned packages that ship in the
// built bundle, in the order they are written into package.json. The returned
// slice is a copy; callers may modify it.
func FrontendRuntimeDependencies() []Dependency {
	out := make([]Dependency, len(frontendRuntimeDependencies))
	copy(out, frontendRuntimeDependencies)
	return out
}

// frontendDependencies is the generated package.json's devDependencies, in
// the order they are written. The order is fixed here rather than derived
// from a map, because map iteration order is exactly the kind of thing that
// makes generated output differ between two runs.
var frontendDependencies = []Dependency{
	{Name: "@sveltejs/adapter-static", Version: "3.0.10"},
	{Name: "@sveltejs/kit", Version: "2.70.3"},
	{Name: "@sveltejs/vite-plugin-svelte", Version: "7.3.0"},
	{Name: "@tailwindcss/vite", Version: "4.3.3"},
	{Name: "@inlang/paraglide-js", Version: ParaglideVersion},
	{Name: "@inlang/plugin-message-format", Version: MessageFormatPluginVersion},
	{Name: "openapi-typescript", Version: OpenAPITypescriptVersion},
	{Name: "svelte", Version: "5.56.10"},
	{Name: "svelte-check", Version: "4.7.6"},
	{Name: "tailwindcss", Version: "4.3.3"},
	{Name: "typescript", Version: TypeScriptVersion},
	{Name: "vite", Version: "8.2.2"},
	{Name: "vitest", Version: VitestVersion},
}

// FrontendDependencies returns the pinned frontend packages, in the order
// they are written into the generated package.json. The returned slice is a
// copy; callers may modify it.
func FrontendDependencies() []Dependency {
	out := make([]Dependency, len(frontendDependencies))
	copy(out, frontendDependencies)
	return out
}
