package generator

// The versions a generated project is pinned to. Every one of them is a
// literal here rather than a value read from the environment, the build, or
// the network: generation must produce byte-identical output on every
// machine, and a version resolved at generation time would make the output
// depend on when it ran.
//
// Bumping any of these is a deliberate edit with a corresponding line in
// docs/dependencies.md, the same way adding a dependency is.
const (
	// NiseModulePath is the framework module a generated application
	// imports runtime/ from.
	NiseModulePath = "github.com/drilonrecica/nise-and-go"

	// NiseModuleVersion is the framework version the generated go.mod
	// requires. It is deliberately separate from the recipe's
	// runtimeVersion field: the recipe records the version of the nise
	// binary that generated the project, which for a source build is the
	// non-module string "dev", while go.mod needs a resolvable module
	// version.
	NiseModuleVersion = "v0.1.0"

	// ChiVersion pins the HTTP router, the one non-Nise Go dependency a
	// generated project starts with.
	ChiVersion = "v5.3.2"

	// PgxVersion pins the PostgreSQL driver and pool used by generated
	// applications.
	PgxVersion = "v5.10.0"

	// SQLCVersion pins the query-code generator in generated projects.
	SQLCVersion = "v1.31.1"

	// GooseVersion pins the migration library and command in generated
	// projects. The application imports the provider API at runtime and also
	// declares the command as a Go tool for explicit operator workflows.
	GooseVersion = "v3.27.3"

	// RiverVersion pins the PostgreSQL-backed job queue, and with it both
	// of the modules its client needs: riverdriver is the storage-neutral
	// interface, riverdriver/riverpgxv5 is the pgx v5 implementation. All
	// three are released together and are only ever compatible in matched
	// sets, so they share one constant rather than three that could drift.
	//
	// River is the second Go dependency a generated project ships with in
	// its binary after chi and pgx. It earns that place by needing no
	// process the application does not already run: the queue is the
	// PostgreSQL database that is already there, which is the difference
	// between adding a job system and adding a second thing that can be
	// down. See docs/dependencies.md.
	RiverVersion = "v0.46.0"

	// RiverSchemaVersion is the highest River migration line version the
	// generated db/migrations/00009_jobs.sql brings the schema up to. It is
	// recorded in the generated river_migration table so River's own
	// migration tooling can take over later without re-running work that
	// migration already did.
	RiverSchemaVersion = 7

	// XCryptoVersion pins golang.org/x/crypto, reached by generated
	// applications through runtime/password's Argon2id hashing. It is the
	// one non-standard-library dependency any runtime package has.
	XCryptoVersion = "v0.54.0"

	// OAPICodegenVersion pins the generator that turns the authoritative
	// OpenAPI document into strict chi server bindings.
	OAPICodegenVersion = "v2.8.0"

	// OAPIRuntimeVersion pins the small runtime the generated bindings
	// import to bind path and query parameters. It is not a framework
	// choice: it is the library the pinned generator's own output requires,
	// and it enters the generated go.mod for the same reason the output
	// does.
	OAPIRuntimeVersion = "v1.7.0"

	// OAPICodegenGeneratedHeader is the exact standard ownership marker the
	// pinned generator writes. Keeping the version in the marker is useful:
	// it lets ownership checks distinguish reproducible tool output from a
	// file produced by some other oapi-codegen release.
	OAPICodegenGeneratedHeader = "Code generated by github.com/oapi-codegen/oapi-codegen/v2 version " + OAPICodegenVersion + " DO NOT EDIT."

	// GoDirective is the go directive written into the generated go.mod.
	// It is the three-component form `go mod tidy` produces, so the first
	// tidy in a new project does not rewrite the file nise just wrote.
	GoDirective = "1.26.0"

	// GoImageTag is the golang container image tag the generated
	// Dockerfile builds with.
	GoImageTag = "1.26"

	// The base images the generated Dockerfile builds from, pinned by
	// digest as well as by tag.
	//
	// A tag moves. `golang:1.26` is a different image next month, which
	// means the same commit produces a different binary — and an image
	// nobody can rebuild is one nobody can audit after an advisory. The tag
	// is kept beside the digest so a reader can see what the digest is
	// meant to be; the digest is what actually resolves.
	//
	// Bumping one is a deliberate edit with a line in docs/dependencies.md,
	// the same as any other pin. Resolve the new digest with:
	//
	//	docker buildx imagetools inspect <image>:<tag>
	GoImageDigest      = "sha256:ba4c8df3f74321b0d5c44911ccb694c8156340b684eed1fae09a9bd9f7a82b4d"
	NodeImageDigest    = "sha256:4d676821dff059fd00d277ee4261ef34ea712317fed0737c03941481b5760c96"
	RuntimeImage       = "gcr.io/distroless/static-debian12"
	RuntimeImageTag    = "nonroot"
	RuntimeImageDigest = "sha256:52dcfbabb7457ea47c82f6e13af8c8a4a1d9f7b0145142b3ecab20f2b888411d"

	// NodeVersion is the minimum Node version the generated frontend
	// declares in its engines field.
	NodeVersion = "22.22.2"

	// NodeMajor is the node container image tag the generated Dockerfile
	// builds the frontend with.
	NodeMajor = "22"

	// PnpmVersion is the pnpm version the generated package.json pins
	// through its packageManager field, so Corepack activates exactly this
	// one per project.
	PnpmVersion = "10.33.0"

	// OpenAPITypescriptVersion pins frontend type generation from the same
	// authoritative document as the strict Go server bindings.
	OpenAPITypescriptVersion = "7.13.0"

	// TypeScriptVersion is the newest TypeScript release in the major range
	// openapi-typescript declares compatible.
	TypeScriptVersion = "5.9.3"

	// VitestVersion pins the Node-based unit runner used for the generated
	// frontend's application-owned TypeScript contracts.
	VitestVersion = "4.1.11"

	// PlaywrightVersion pins the browser driver behind both the component
	// suite's browser mode and the end-to-end suite. One pin for both, so a
	// project cannot end up driving two different browsers.
	PlaywrightVersion = "1.62.1"

	// AxeCoreVersion pins the accessibility rule engine the component suite
	// asserts against. It is a test dependency: nothing from it ships.
	AxeCoreVersion = "4.13.0"

	// VitestBrowserSvelteVersion pins the renderer that mounts a Svelte 5
	// component inside browser mode.
	VitestBrowserSvelteVersion = "3.0.0"

	// BiomeVersion pins the JavaScript and TypeScript linter.
	//
	// Biome rather than ESLint, for the same reason this repository's own
	// golangci-lint configuration is a short curated list: ESLint is a
	// linter plus a plugin ecosystem, and a generated project would acquire
	// a parser, a plugin, a config preset, and their transitive versions
	// before it had checked a single file. Biome is one binary, one
	// dependency, and a configuration a reader can hold in their head.
	//
	// It lints TypeScript and the script blocks inside .svelte files.
	// Svelte's own rules — markup, accessibility, and the Svelte 5 runes
	// this project requires — are svelte-check's, which the generated
	// project already runs, plus the two purpose-built scripts under
	// frontend/scripts. The three cover different things and none of them
	// substitutes for the others.
	BiomeVersion = "2.5.11"

	// GolangciLintVersion is the version a generated project's `make lint`
	// requires. It matches this repository's own pin (docs/toolchain.md) so
	// that a contributor moving between the two sees one linter, not two
	// that disagree.
	GolangciLintVersion = "2.11.3"

	// ValibotVersion pins the schema library the generated forms validate
	// with in the browser. It is the generated frontend's first package that
	// ships in the bundle rather than only building it.
	ValibotVersion = "1.1.0"

	// ParaglideVersion pins the compile-time internationalization toolchain.
	// It is a build tool, not a bundled package: messages compile to modules,
	// so what ships is the messages the application actually imports.
	ParaglideVersion = "2.25.0"

	// MessageFormatPluginVersion pins the inlang plugin that reads
	// messages/*.json. It is an ordinary devDependency, resolved from
	// node_modules by the settings file, rather than the CDN URL inlang's
	// own documentation uses: a build step that fetches an unpinned script
	// from a content delivery network is a supply-chain surface, and a
	// lockfile entry is not.
	MessageFormatPluginVersion = "4.1.0"

	// TableCoreVersion pins the framework-agnostic table primitive the
	// generated DataTable wraps. It is the 8.x line rather than the newer
	// 9.x: 9's core delegates reactivity to a per-framework adapter feature,
	// and constructing a table without one throws, so 9 is not usable from a
	// Nise-owned Svelte wrapper until a Svelte adapter exists.
	TableCoreVersion = "8.21.3"
)

// Dependency is one pinned frontend package.
type Dependency struct {
	// Name is the npm package name.
	Name string
	// Version is an exact version, never a range: a generated project is
	// reproducible from the moment it is created, before a lockfile exists.
	Version string
}

// frontendRuntimeDependencies is the generated package.json's dependencies:
// the packages that ship in the bundle rather than only building it. The list
// is short on purpose, and every entry is one docs/dependencies.md justifies.
var frontendRuntimeDependencies = []Dependency{
	{Name: "@tanstack/table-core", Version: TableCoreVersion},
	{Name: "valibot", Version: ValibotVersion},
}

// FrontendRuntimeDependencies returns the pinned packages that ship in the
// built bundle, in the order they are written into package.json. The returned
// slice is a copy; callers may modify it.
func FrontendRuntimeDependencies() []Dependency {
	out := make([]Dependency, len(frontendRuntimeDependencies))
	copy(out, frontendRuntimeDependencies)
	return out
}

// frontendDependencies is the generated package.json's devDependencies, in
// the order they are written. The order is fixed here rather than derived
// from a map, because map iteration order is exactly the kind of thing that
// makes generated output differ between two runs.
var frontendDependencies = []Dependency{
	{Name: "@sveltejs/adapter-static", Version: "3.0.10"},
	{Name: "@sveltejs/kit", Version: "2.70.3"},
	{Name: "@sveltejs/vite-plugin-svelte", Version: "7.3.0"},
	{Name: "@playwright/test", Version: PlaywrightVersion},
	{Name: "@tailwindcss/vite", Version: "4.3.3"},
	{Name: "@vitest/browser", Version: VitestVersion},
	{Name: "@vitest/browser-playwright", Version: VitestVersion},
	{Name: "@biomejs/biome", Version: BiomeVersion},
	{Name: "axe-core", Version: AxeCoreVersion},
	{Name: "@inlang/paraglide-js", Version: ParaglideVersion},
	{Name: "@inlang/plugin-message-format", Version: MessageFormatPluginVersion},
	{Name: "openapi-typescript", Version: OpenAPITypescriptVersion},
	{Name: "playwright", Version: PlaywrightVersion},
	{Name: "svelte", Version: "5.56.10"},
	{Name: "svelte-check", Version: "4.7.6"},
	{Name: "tailwindcss", Version: "4.3.3"},
	{Name: "typescript", Version: TypeScriptVersion},
	{Name: "vite", Version: "8.2.2"},
	{Name: "vitest", Version: VitestVersion},
	{Name: "vitest-browser-svelte", Version: VitestBrowserSvelteVersion},
}

// FrontendDependencies returns the pinned frontend packages, in the order
// they are written into the generated package.json. The returned slice is a
// copy; callers may modify it.
func FrontendDependencies() []Dependency {
	out := make([]Dependency, len(frontendDependencies))
	copy(out, frontendDependencies)
	return out
}
