// Package upgrade moves a generated project from the Nise it was created with
// to the Nise that is running.
//
// The whole design follows from one rule the rest of this project already
// enforces: nise owns some files in a generated project and the application
// owns the rest, and nise never overwrites the second kind (ADR 0003). An
// upgrade is where that rule is under the most pressure — the framework has
// changed, the application's code may need to change with it, and the
// tempting shortcut is to regenerate everything and let the developer sort it
// out afterwards from a diff. That is not an upgrade; it is a restore from a
// backup nobody took.
//
// So an upgrade here is four separate things, applied in order of how much
// they are allowed to touch:
//
//  1. **Nise-owned files are regenerated.** These carry `Code generated by
//     nise; DO NOT EDIT.` and are the framework's to rewrite. A Nise-owned
//     file the new version no longer plans is removed, because an orphaned
//     .gen.go from a subsystem that no longer exists does not stop mattering
//     when it stops being written.
//
//  2. **go.mod's framework requirement is bumped**, and nothing else in
//     go.mod is touched. It is edited textually rather than through the go
//     toolchain, because `go mod tidy` resolves the whole module graph over
//     the network and an upgrade should not be the command that discovers a
//     dependency is unreachable. Running it is left to the developer, and
//     named in the output.
//
//  3. **Declared codemods run over application-owned Go source.** A codemod
//     is an exact textual replacement a migration declares, and every one is
//     reported with the file and the number of occurrences. Nothing is
//     inferred: there is no AST rewriting, no import reordering, no
//     formatting pass. A codemod that cannot be described as "this exact
//     string became that exact string" does not belong here — it belongs in
//     (4), where a person reads it.
//
//  4. **Everything else is a note.** A change that needs judgement is
//     printed for the developer to make, not guessed at. This is the category
//     that keeps the other three honest: the moment a migration is tempted to
//     rewrite application logic, it writes a paragraph instead.
//
// Planning and applying are separate calls, and Plan writes nothing. That is
// what `-dry-run` renders, and it is also what the applying path reports, so
// the summary a developer reads afterwards is the same value that was checked
// before anything was written.
package upgrade
