package upgrade_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/drilonrecica/nise-and-go/internal/generator"
	"github.com/drilonrecica/nise-and-go/internal/recipe"
	"github.com/drilonrecica/nise-and-go/internal/upgrade"
)

const generatingCLI = "v0.1.0"

// newProject generates a real project, so every test here runs against the
// tree `nise new` actually writes rather than a fixture that agrees with the
// generator by construction.
func newProject(t *testing.T) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), "app")
	_, err := generator.Write(root, generator.Options{
		Name:       "app",
		ModulePath: "example.com/app",
		CLIVersion: generatingCLI,
	})
	if err != nil {
		t.Fatalf("generating a project: %v", err)
	}
	return root
}

func options(root string) upgrade.Options {
	return upgrade.Options{
		Root:       root,
		CLIVersion: generatingCLI,
		Codemods:   true,
	}
}

func read(t *testing.T, root, rel string) string {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(rel))) // #nosec G304 -- a path under this test's own t.TempDir().
	if err != nil {
		t.Fatalf("reading %s: %v", rel, err)
	}
	return string(data)
}

func write(t *testing.T, root, rel, content string) {
	t.Helper()
	full := filepath.Join(root, filepath.FromSlash(rel))
	if err := os.MkdirAll(filepath.Dir(full), 0o750); err != nil {
		t.Fatalf("creating %s: %v", filepath.Dir(rel), err)
	}
	// #nosec G703 -- root is under this test's own t.TempDir().
	if err := os.WriteFile(full, []byte(content), 0o600); err != nil {
		t.Fatalf("writing %s: %v", rel, err)
	}
}

// A freshly generated project is already at this nise's version, so an upgrade
// has nothing to do — and says so as its own answer rather than as an empty
// list of changes.
func TestAFreshProjectIsUpToDate(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	report, err := upgrade.Plan(options(root))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if !report.UpToDate {
		t.Errorf("a project this nise just generated was reported as needing an upgrade: %+v", report)
	}
}

// The single most important property in this package. An upgrade that
// regenerates an application-owned file has not upgraded the project; it has
// discarded the application.
func TestApplicationOwnedFilesAreNeverRewritten(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	planned, err := generator.Plan(generator.Options{
		Name: "app", ModulePath: "example.com/app", CLIVersion: generatingCLI,
	})
	if err != nil {
		t.Fatalf("planning: %v", err)
	}

	// Rewrite every app-owned Go file to something that is unmistakably the
	// application's, and stale the recipe so an upgrade has work to do.
	var owned []string
	for _, file := range planned {
		if file.Owner != generator.OwnerApp || !strings.HasSuffix(file.Path, ".go") {
			continue
		}
		owned = append(owned, file.Path)
		write(t, root, file.Path, "// the application rewrote this entirely\npackage whatever\n")
	}
	if len(owned) == 0 {
		t.Fatal("the generated project has no application-owned Go files, so this test proves nothing")
	}
	stale(t, root)

	if _, err := upgrade.Apply(options(root)); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	for _, path := range owned {
		if got := read(t, root, path); got != "// the application rewrote this entirely\npackage whatever\n" {
			t.Errorf("%s was rewritten by the upgrade:\n%s", path, got)
		}
	}
}

// Nise-owned files are the framework's, and an upgrade is exactly when they
// have to move.
func TestNiseOwnedFilesAreRegenerated(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	// A Nise-owned file, clobbered.
	const clobbered = "internal/app/modules.gen.go"
	write(t, root, clobbered, "// something else entirely\n")
	stale(t, root)

	report, err := upgrade.Apply(options(root))
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if !mentions(report.Files, clobbered, upgrade.ActionUpdate) {
		t.Errorf("the report does not name %s as an update: %+v", clobbered, report.Files)
	}
	if got := read(t, root, clobbered); !strings.Contains(got, generator.NiseOwnedHeader) {
		t.Errorf("%s was not regenerated:\n%s", clobbered, got)
	}
}

// An orphaned generated file does not stop mattering when it stops being
// written: it still compiles, and still refers to things that may not exist.
//
// A removal is declared by the migration that stops writing the file, because
// an upgrade can only plan a project with the templates it has — the file set
// an older nise wrote is not something a newer one can compute.
func TestADeclaredRemovalDeletesTheOrphanedFile(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	const orphan = "internal/app/oldsubsystem.gen.go"
	write(t, root, orphan, "// Code generated by nise; DO NOT EDIT.\npackage app\n")
	stale(t, root)

	opts := options(root)
	opts.Migrations = []upgrade.Migration{{
		From: "v0.0.1", To: generator.NiseModuleVersion,
		Summary: "the old subsystem was removed",
		Removed: []string{orphan},
	}}

	report, err := upgrade.Apply(opts)
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if !mentions(report.Files, orphan, upgrade.ActionRemove) {
		t.Errorf("the declared removal is not in the report: %+v", report.Files)
	}
	if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(orphan))); !os.IsNotExist(err) {
		t.Errorf("the orphaned %s still exists", orphan)
	}
}

// The two refusals that guard the only place this package deletes anything.
func TestARemovalIsRefusedWhenItWouldDeleteTheWrongThing(t *testing.T) {
	t.Parallel()

	t.Run("a path the new version still writes", func(t *testing.T) {
		t.Parallel()
		root := newProject(t)
		stale(t, root)

		const stillPlanned = "internal/app/modules.gen.go"
		opts := options(root)
		opts.Migrations = []upgrade.Migration{{
			From: "v0.0.1", To: generator.NiseModuleVersion,
			Removed: []string{stillPlanned},
		}}
		if _, err := upgrade.Apply(opts); err != nil {
			t.Fatalf("Apply: %v", err)
		}
		if _, err := os.Stat(filepath.Join(root, filepath.FromSlash(stillPlanned))); err != nil {
			t.Errorf("%s was deleted even though this version still writes it: %v", stillPlanned, err)
		}
	})

	t.Run("a path outside the project", func(t *testing.T) {
		t.Parallel()
		root := newProject(t)
		outside := filepath.Join(filepath.Dir(root), "outside.txt")
		// #nosec G703 -- a path beside this test's own t.TempDir() project.
		if err := os.WriteFile(outside, []byte("not nise's"), 0o600); err != nil {
			t.Fatalf("writing the outside file: %v", err)
		}
		stale(t, root)

		opts := options(root)
		opts.Migrations = []upgrade.Migration{{
			From: "v0.0.1", To: generator.NiseModuleVersion,
			Removed: []string{"../outside.txt"},
		}}
		if _, err := upgrade.Apply(opts); err != nil {
			t.Fatalf("Apply: %v", err)
		}
		if _, err := os.Stat(outside); err != nil {
			t.Errorf("a file outside the project was deleted by a declared removal: %v", err)
		}
	})
}

// The dependency bump, on the file the application owns. Only the version
// token on a pinned requirement's own line moves, and nothing else in the file
// does.
func TestPinnedDependenciesAreBumpedAndNothingElseIsTouched(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	original := read(t, root, "go.mod")
	aged := strings.Replace(original,
		generator.NiseModulePath+" "+generator.NiseModuleVersion,
		generator.NiseModulePath+" v0.0.1", 1)
	if aged == original {
		t.Fatal("the generated go.mod does not require the framework at the pinned version, so this test proves nothing")
	}
	// Something the application added, which must survive untouched.
	aged = strings.Replace(aged, "require (", "require (\n\tgithub.com/example/theirs v1.2.3", 1)
	write(t, root, "go.mod", aged)
	stale(t, root)

	report, err := upgrade.Apply(options(root))
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}

	var bumped bool
	for _, change := range report.Dependencies {
		if change.Module == generator.NiseModulePath {
			bumped = true
			if change.From != "v0.0.1" || change.To != generator.NiseModuleVersion {
				t.Errorf("the framework bump is %s → %s, want v0.0.1 → %s", change.From, change.To, generator.NiseModuleVersion)
			}
		}
	}
	if !bumped {
		t.Errorf("the framework requirement was not bumped: %+v", report.Dependencies)
	}

	after := read(t, root, "go.mod")
	if !strings.Contains(after, generator.NiseModulePath+" "+generator.NiseModuleVersion) {
		t.Errorf("go.mod does not require the new framework version:\n%s", after)
	}
	if !strings.Contains(after, "github.com/example/theirs v1.2.3") {
		t.Error("the application's own requirement was removed by the upgrade")
	}
	if !strings.Contains(after, "// The require block is pinned rather than resolved") {
		t.Error("go.mod's comments were lost; a whole-file rewrite is not a reviewable diff")
	}
}

// A project pinned ahead of nise is not moved backwards. That is a downgrade
// wearing an upgrade's name, and it silently reverts whatever the developer
// took the newer version for.
func TestADependencyPinnedAheadOfNiseIsLeftAloneAndNamed(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	original := read(t, root, "go.mod")
	ahead := strings.Replace(original,
		"github.com/go-chi/chi/v5 "+generator.ChiVersion,
		"github.com/go-chi/chi/v5 v99.0.0", 1)
	if ahead == original {
		t.Fatal("chi is not pinned in the generated go.mod, so this test proves nothing")
	}
	write(t, root, "go.mod", ahead)

	report, err := upgrade.Plan(options(root))
	if err != nil {
		t.Fatalf("Plan: %v", err)
	}
	for _, change := range report.Dependencies {
		if change.Module == "github.com/go-chi/chi/v5" {
			t.Errorf("an upgrade moved chi from v99.0.0 to %s; an upgrade never moves a dependency backwards", change.To)
		}
	}
	if !anyContains(report.Notes, "which is newer than the") {
		t.Errorf("nothing in the report says the project is pinned ahead of nise: %v", report.Notes)
	}
}

// A requirement the application removed stays removed. go.mod is theirs.
func TestADependencyTheApplicationRemovedIsNotReAdded(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	original := read(t, root, "go.mod")
	without := strings.Replace(original, "\tgithub.com/go-chi/chi/v5 "+generator.ChiVersion+"\n", "", 1)
	if without == original {
		t.Fatal("chi's require line was not found, so this test proves nothing")
	}
	write(t, root, "go.mod", without)
	stale(t, root)

	if _, err := upgrade.Apply(options(root)); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if strings.Contains(read(t, root, "go.mod"), "github.com/go-chi/chi/v5") {
		t.Error("the upgrade re-added a requirement the application deleted")
	}
}

// The frontend manifest is bumped the same way, and the application's own
// packages, scripts, and formatting survive.
func TestFrontendPinsAreBumpedWithoutReformattingTheManifest(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	original := read(t, root, "frontend/package.json")
	aged := strings.Replace(original,
		`"valibot": "`+generator.ValibotVersion+`"`,
		`"valibot": "0.0.1"`, 1)
	if aged == original {
		t.Fatal("valibot is not pinned in the generated package.json, so this test proves nothing")
	}
	aged = strings.Replace(aged, `"dependencies": {`, `"dependencies": {`+"\n    \"their-package\": \"1.0.0\",", 1)
	write(t, root, "frontend/package.json", aged)
	stale(t, root)

	report, err := upgrade.Apply(options(root))
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	after := read(t, root, "frontend/package.json")
	if !strings.Contains(after, `"valibot": "`+generator.ValibotVersion+`"`) {
		t.Error("valibot was not bumped")
	}
	if !strings.Contains(after, `"their-package": "1.0.0"`) {
		t.Error("the application's own dependency was removed")
	}
	if !strings.Contains(after, `"check:runes":`) {
		t.Error("the manifest's scripts were lost; re-encoding JSON is not a reviewable diff")
	}
	if !anyStep(report.NextSteps, "pnpm --dir frontend install") {
		t.Errorf("nothing tells the developer to reinstall after a manifest change: %v", report.NextSteps)
	}
}

// The network is not touched during an upgrade, and the commands that would
// touch it are named rather than run.
func TestTheCommandsThatNeedANetworkAreNamedNotRun(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	original := read(t, root, "go.mod")
	write(t, root, "go.mod", strings.Replace(original,
		generator.NiseModulePath+" "+generator.NiseModuleVersion,
		generator.NiseModulePath+" v0.0.1", 1))
	stale(t, root)

	report, err := upgrade.Apply(options(root))
	if err != nil {
		t.Fatalf("Apply: %v", err)
	}
	if !anyStep(report.NextSteps, "go mod tidy") {
		t.Errorf("go mod tidy is not in the next steps: %v", report.NextSteps)
	}
	if !anyStep(report.NextSteps, "git diff") {
		t.Errorf("the developer is not told to review the diff, which is the whole review mechanism: %v", report.NextSteps)
	}
	// go.sum is what `go mod tidy` writes. An upgrade that had resolved the
	// module graph itself would have left one.
	if _, err := os.Stat(filepath.Join(root, "go.sum")); err == nil {
		t.Error("the upgrade wrote a go.sum, which means it resolved the module graph over the network")
	}
}

// Plan writes nothing. It is what -dry-run renders, and a dry run that
// modifies the tree is worse than no dry run at all.
func TestPlanWritesNothing(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	write(t, root, "internal/app/modules.gen.go", "// clobbered\n")
	original := read(t, root, "go.mod")
	write(t, root, "go.mod", strings.Replace(original,
		generator.NiseModulePath+" "+generator.NiseModuleVersion,
		generator.NiseModulePath+" v0.0.1", 1))
	stale(t, root)

	before := snapshot(t, root)
	if _, err := upgrade.Plan(options(root)); err != nil {
		t.Fatalf("Plan: %v", err)
	}
	if after := snapshot(t, root); after != before {
		t.Error("Plan modified the project")
	}
}

// The recipe is the record that the upgrade happened, and it is written last.
func TestTheRecipeRecordsTheUpgrade(t *testing.T) {
	t.Parallel()
	root := newProject(t)
	stale(t, root)

	if _, err := upgrade.Apply(upgrade.Options{Root: root, CLIVersion: "v9.9.9", Codemods: true}); err != nil {
		t.Fatalf("Apply: %v", err)
	}
	got := readRecipe(t, root)
	if got.CLIVersion != "v9.9.9" {
		t.Errorf("cliVersion = %q, want the nise that did the upgrade", got.CLIVersion)
	}
	if got.RuntimeVersion != generator.NiseModuleVersion {
		t.Errorf("runtimeVersion = %q, want %q", got.RuntimeVersion, generator.NiseModuleVersion)
	}
}

func TestADirectoryWithNoRecipeIsRefused(t *testing.T) {
	t.Parallel()
	if _, err := upgrade.Plan(upgrade.Options{Root: t.TempDir(), CLIVersion: generatingCLI}); err == nil {
		t.Error("a directory that is not a generated project was upgraded")
	}
}

// --- helpers ---------------------------------------------------------------

// stale ages the recipe so an upgrade has something to do.
func stale(t *testing.T, root string) {
	t.Helper()
	r := readRecipe(t, root)
	r.CLIVersion = "v0.0.1"
	r.RuntimeVersion = "v0.0.1"
	writeRecipe(t, root, r)
}

func readRecipe(t *testing.T, root string) recipe.Recipe {
	t.Helper()
	data, err := os.ReadFile(filepath.Join(root, recipe.FileName)) // #nosec G304 -- a path under this test's own t.TempDir().
	if err != nil {
		t.Fatalf("reading the recipe: %v", err)
	}
	r, err := recipe.Unmarshal(data)
	if err != nil {
		t.Fatalf("parsing the recipe: %v", err)
	}
	return r
}

func writeRecipe(t *testing.T, root string, r recipe.Recipe) {
	t.Helper()
	encoded, err := recipe.Marshal(r)
	if err != nil {
		t.Fatalf("encoding the recipe: %v", err)
	}
	write(t, root, recipe.FileName, string(encoded))
}

func mentions(changes []upgrade.FileChange, path string, action upgrade.Action) bool {
	for _, change := range changes {
		if change.Path == path && change.Action == action {
			return true
		}
	}
	return false
}

func anyContains(lines []string, want string) bool {
	for _, line := range lines {
		if strings.Contains(line, want) {
			return true
		}
	}
	return false
}

func anyStep(steps []string, want string) bool {
	for _, step := range steps {
		if step == want {
			return true
		}
	}
	return false
}

// snapshot renders every file's path and content hash, so a test can assert a
// tree is byte-identical before and after.
func snapshot(t *testing.T, root string) string {
	t.Helper()
	var b strings.Builder
	err := filepath.WalkDir(root, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		relative, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		info, infoErr := entry.Info()
		if infoErr != nil {
			return infoErr
		}
		b.WriteString(filepath.ToSlash(relative))
		b.WriteString(":")
		b.WriteString(info.Mode().String())
		b.WriteString(":")
		b.WriteString(strings.TrimSpace(itoa(info.Size())))
		b.WriteString("\n")
		return nil
	})
	if err != nil {
		t.Fatalf("walking the project: %v", err)
	}
	return b.String()
}

func itoa(n int64) string {
	if n == 0 {
		return "0"
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}

// Every write goes through an os.Root opened on the project, so a path can
// only resolve inside it. The paths come from this repository's own generator,
// so this is not defence against an attacker — it is defence against the thing
// that actually happens: a symlink somebody put inside their project, and a
// command that writes into a developer's working tree having no business being
// able to reach outside it.
func TestAnUpgradeCannotWriteOutsideTheProject(t *testing.T) {
	t.Parallel()
	root := newProject(t)

	outside := filepath.Join(filepath.Dir(root), "outside")
	if err := os.MkdirAll(outside, 0o750); err != nil {
		t.Fatalf("creating the outside directory: %v", err)
	}
	const sentinel = "the application's own file, untouched\n"
	// #nosec G703 -- a path beside this test's own t.TempDir() project.
	if err := os.WriteFile(filepath.Join(outside, "modules.gen.go"), []byte(sentinel), 0o600); err != nil {
		t.Fatalf("writing the sentinel: %v", err)
	}

	// Replace a Nise-owned *file* with a symlink out of the project, leaving
	// its directory a real one. A symlinked directory would be caught earlier,
	// when the parent directory is created; this is the case where every step
	// before the write looks ordinary.
	target := filepath.Join(root, "internal", "app", "modules.gen.go")
	if err := os.Remove(target); err != nil {
		t.Fatalf("removing %s: %v", target, err)
	}
	if err := os.Symlink(filepath.Join(outside, "modules.gen.go"), target); err != nil {
		t.Skipf("this filesystem does not support symlinks: %v", err)
	}
	stale(t, root)

	// Failing is a fine outcome, and so is succeeding without following the
	// link. What must not happen is the sentinel changing.
	_, _ = upgrade.Apply(options(root))

	after, err := os.ReadFile(filepath.Join(outside, "modules.gen.go")) // #nosec G304 -- a path this test just wrote.
	if err != nil {
		t.Fatalf("reading the sentinel: %v", err)
	}
	if string(after) != sentinel {
		t.Errorf("the upgrade wrote through a symlink and out of the project:\n%s", after)
	}
}
