package agentsfile_test

import (
	"encoding/json"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/drilonrecica/nise-and-go/internal/agentsfile"
	"github.com/drilonrecica/nise-and-go/internal/recipe"
)

// fullRecipe is a recipe with every module selected, matching the golden
// fixtures under testdata/.
func fullRecipe() recipe.Recipe {
	return recipe.Recipe{
		SchemaVersion:  recipe.SchemaVersion,
		Profile:        recipe.ProfileGoChiPostgresSvelte,
		Modules:        recipe.Modules(),
		CLIVersion:     "v0.1.0",
		RuntimeVersion: "v0.1.0",
	}
}

func TestGenerateIsDeterministic(t *testing.T) {
	t.Parallel()
	r := fullRecipe()

	a, err := agentsfile.Generate(r)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	b, err := agentsfile.Generate(r)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	if string(a.AgentsMD) != string(b.AgentsMD) {
		t.Error("AGENTS.md differs across two calls with an equal recipe")
	}
	if string(a.Architecture) != string(b.Architecture) {
		t.Error("architecture.json differs across two calls with an equal recipe")
	}
}

func TestGenerateMatchesGoldenFiles(t *testing.T) {
	t.Parallel()
	out, err := agentsfile.Generate(fullRecipe())
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}

	wantMD, err := os.ReadFile("testdata/AGENTS.golden.md")
	if err != nil {
		t.Fatalf("read golden AGENTS.md: %v", err)
	}
	if string(out.AgentsMD) != string(wantMD) {
		t.Errorf("AGENTS.md does not match testdata/AGENTS.golden.md\ngot:\n%s", out.AgentsMD)
	}

	wantArch, err := os.ReadFile("testdata/architecture.golden.json")
	if err != nil {
		t.Fatalf("read golden architecture.json: %v", err)
	}
	if string(out.Architecture) != string(wantArch) {
		t.Errorf("architecture.json does not match testdata/architecture.golden.json\ngot:\n%s", out.Architecture)
	}
}

func TestGenerateNoModulesSelected(t *testing.T) {
	t.Parallel()
	r := fullRecipe()
	r.Modules = nil

	out, err := agentsfile.Generate(r)
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	if !strings.Contains(string(out.AgentsMD), "Selected modules: none.") {
		t.Errorf("AGENTS.md does not report no modules selected:\n%s", out.AgentsMD)
	}

	var arch map[string]any
	if err := json.Unmarshal(out.Architecture, &arch); err != nil {
		t.Fatalf("architecture.json does not parse: %v", err)
	}
	for _, m := range arch["modules"].([]any) {
		mod := m.(map[string]any)
		if mod["selected"].(bool) {
			t.Errorf("module %v reported selected with an empty recipe.Modules", mod["name"])
		}
	}
}

func TestGeneratedFilesAreSelfConsistent(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	result, err := agentsfile.Write(root, fullRecipe(), false)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}

	agentsData, err := os.ReadFile(result.AgentsPath)
	if err != nil {
		t.Fatalf("read %s: %v", result.AgentsPath, err)
	}
	if !strings.HasPrefix(string(agentsData), "<!-- Code generated by nise; DO NOT EDIT. -->\n") {
		t.Error("AGENTS.md is missing its ownership header")
	}

	archData, err := os.ReadFile(result.ArchitecturePath)
	if err != nil {
		t.Fatalf("read %s: %v", result.ArchitecturePath, err)
	}
	var arch struct {
		Generated string `json:"generated"`
	}
	if err := json.Unmarshal(archData, &arch); err != nil {
		t.Fatalf("architecture.json does not parse: %v", err)
	}
	if arch.Generated != agentsfile.ArchitectureGeneratedMarker {
		t.Errorf("architecture.json generated field = %q, want %q", arch.Generated, agentsfile.ArchitectureGeneratedMarker)
	}
}

func TestWriteFirstTimeSucceedsWithoutForce(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	result, err := agentsfile.Write(root, fullRecipe(), false)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	if _, err := os.Stat(result.AgentsPath); err != nil {
		t.Errorf("AGENTS.md was not written: %v", err)
	}
	if _, err := os.Stat(result.ArchitecturePath); err != nil {
		t.Errorf("architecture.json was not written: %v", err)
	}
}

func TestWriteIsIdempotentWithoutForce(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	r := fullRecipe()

	if _, err := agentsfile.Write(root, r, false); err != nil {
		t.Fatalf("first Write: %v", err)
	}
	// Regenerating unedited nise-owned output must never be treated as a
	// conflict: nothing hand-edited it between the two calls.
	if _, err := agentsfile.Write(root, r, false); err != nil {
		t.Fatalf("second Write (unedited) returned an error, want success: %v", err)
	}
}

func TestWriteRefusesHandEditedAgentsMD(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	r := fullRecipe()

	result, err := agentsfile.Write(root, r, false)
	if err != nil {
		t.Fatalf("first Write: %v", err)
	}

	tamperMarker := "hand-edited by a human, not nise"
	original, err := os.ReadFile(result.AgentsPath)
	if err != nil {
		t.Fatal(err)
	}
	// Insert the marker right after the two header lines, so it lands
	// within the preview's first previewMaxLines lines rather than
	// possibly being truncated away if appended at the very end.
	lines := strings.SplitN(string(original), "\n", 3)
	tampered := lines[0] + "\n" + lines[1] + "\n" + tamperMarker + "\n" + lines[2]
	// #nosec G703 -- result.AgentsPath is this test's own agentsfile.Write
	// return value, joined from t.TempDir() a few lines above; it is not
	// attacker-controlled. gosec's taint analysis flags it only because
	// the path traveled through a struct field, not a literal.
	if err := os.WriteFile(result.AgentsPath, []byte(tampered), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err = agentsfile.Write(root, r, false)
	var conflictErr *agentsfile.ConflictError
	if !errors.As(err, &conflictErr) {
		t.Fatalf("Write after hand edit = %v, want *ConflictError", err)
	}
	if len(conflictErr.Conflicts) != 1 || conflictErr.Conflicts[0].Path != result.AgentsPath {
		t.Errorf("Conflicts = %+v, want exactly one entry for %s", conflictErr.Conflicts, result.AgentsPath)
	}
	if !strings.Contains(conflictErr.Conflicts[0].Preview, "hand-edited by a human") {
		t.Errorf("Preview does not show the tampered content: %q", conflictErr.Conflicts[0].Preview)
	}

	// The architecture map must be untouched: a refusal must not
	// partially apply, leaving one output regenerated and the other not.
	archBefore, err := os.ReadFile(result.ArchitecturePath)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := agentsfile.Write(root, r, false); err == nil {
		t.Fatal("expected the same conflict again")
	}
	archAfter, err := os.ReadFile(result.ArchitecturePath)
	if err != nil {
		t.Fatal(err)
	}
	if string(archBefore) != string(archAfter) {
		t.Error("architecture.json changed despite the refusal")
	}
}

func TestWriteRefusesHandEditedArchitectureJSON(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	r := fullRecipe()

	result, err := agentsfile.Write(root, r, false)
	if err != nil {
		t.Fatalf("first Write: %v", err)
	}

	if err := os.WriteFile(result.ArchitecturePath, []byte(`{"schemaVersion":1,"generated":"Code generated by nise; DO NOT EDIT.","contentHash":"sha256:0000000000000000000000000000000000000000000000000000000000000","profile":"tampered","modules":[],"directories":[],"features":[]}`), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err = agentsfile.Write(root, r, false)
	var conflictErr *agentsfile.ConflictError
	if !errors.As(err, &conflictErr) {
		t.Fatalf("Write after hand edit = %v, want *ConflictError", err)
	}
	if len(conflictErr.Conflicts) != 1 || conflictErr.Conflicts[0].Path != result.ArchitecturePath {
		t.Errorf("Conflicts = %+v, want exactly one entry for %s", conflictErr.Conflicts, result.ArchitecturePath)
	}
}

func TestWriteForceOverwritesHandEditedFiles(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	r := fullRecipe()

	result, err := agentsfile.Write(root, r, false)
	if err != nil {
		t.Fatalf("first Write: %v", err)
	}
	if err := os.WriteFile(result.AgentsPath, []byte("not what nise generated"), 0o644); err != nil {
		t.Fatal(err)
	}

	if _, err := agentsfile.Write(root, r, true); err != nil {
		t.Fatalf("Write with force=true = %v, want success", err)
	}

	data, err := os.ReadFile(result.AgentsPath)
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(string(data), "not what nise generated") {
		t.Error("force=true did not overwrite the hand-edited content")
	}
}

func TestWriteBothConflictsReportedTogether(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	r := fullRecipe()

	result, err := agentsfile.Write(root, r, false)
	if err != nil {
		t.Fatalf("first Write: %v", err)
	}
	if err := os.WriteFile(result.AgentsPath, []byte("tampered"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(result.ArchitecturePath, []byte("also tampered"), 0o644); err != nil {
		t.Fatal(err)
	}

	_, err = agentsfile.Write(root, r, false)
	var conflictErr *agentsfile.ConflictError
	if !errors.As(err, &conflictErr) {
		t.Fatalf("Write = %v, want *ConflictError", err)
	}
	if len(conflictErr.Conflicts) != 2 {
		t.Fatalf("Conflicts = %+v, want exactly two entries", conflictErr.Conflicts)
	}
}

func TestArchitecturePathIsUnderDotNiseDirectory(t *testing.T) {
	t.Parallel()
	root := t.TempDir()

	result, err := agentsfile.Write(root, fullRecipe(), false)
	if err != nil {
		t.Fatalf("Write: %v", err)
	}
	want := filepath.Join(root, ".nise", "architecture.json")
	if result.ArchitecturePath != want {
		t.Errorf("ArchitecturePath = %s, want %s", result.ArchitecturePath, want)
	}
}
