package agentsfile

import (
	"fmt"
	"sort"
	"strings"

	"github.com/drilonrecica/nise-and-go/internal/recipe"
)

// niseRepoURL is the Nise & Go repository, the authoritative source for
// every doc path this file references. It is a fixed literal, not
// resolved from the environment or a build tag, so it stays part of the
// deterministic output.
const niseRepoURL = "https://github.com/drilonrecica/nise-and-go"

// niseRepoDefaultBranch is the repository's default branch, as reported by
// `git symbolic-ref refs/remotes/origin/HEAD`. A generated AGENTS.md links
// into the repository by branch, so a wrong value here is a 404 in every
// project nise has ever generated — the one artifact whose audience is an
// external coding tool that will not sanity-check the link.
const niseRepoDefaultBranch = "master"

// niseRepoBlobURL is the base for a link to a file in the repository, and
// is deliberately the only place in the tree that spells a repository blob
// URL. TestRepositoryBlobLinksUseOneBranch enforces that: it scans every
// tracked file for a blob link and fails if any of them names a branch
// other than niseRepoDefaultBranch, so renaming the default branch is one
// edit here rather than a hunt through Go source, templates, fixtures, and
// documentation.
const niseRepoBlobURL = niseRepoURL + "/blob/" + niseRepoDefaultBranch

// buildAgentsMDBody renders AGENTS.md's content, excluding the ownership
// header and content-hash comment that wrapMarkdown prepends. Calling it
// twice with an equal r always returns byte-identical output: every list
// it renders (modules, directories) is already sorted before this
// function ever sees it (recipe.Modules() and layoutDirectories() are both
// fixed, non-map-derived slices), and nothing here reads a clock, an
// environment variable, or the filesystem.
func buildAgentsMDBody(r recipe.Recipe) []byte {
	var b strings.Builder

	b.WriteString("# AGENTS.md\n\n")
	b.WriteString("This file is generated by `nise agents`. It is Nise-owned: regenerating it\n")
	b.WriteString("overwrites this file, and hand edits are lost. Edit `nise.json` and re-run\n")
	b.WriteString("`nise agents` instead of changing this document directly; see\n")
	b.WriteString("[Files you must not hand-edit](#files-you-must-not-hand-edit) below.\n\n")

	writeStackSection(&b, r)
	writeLayoutSection(&b)
	writeOwnershipSection(&b)
	writeCommandsSection(&b)
	writeConventionsSection(&b)
	writeDocsSection(&b)

	return []byte(b.String())
}

func writeStackSection(b *strings.Builder, r recipe.Recipe) {
	b.WriteString("## Stack\n\n")
	fmt.Fprintf(b, "- Profile: `%s` — Go, chi, PostgreSQL (pgx, sqlc, Goose), and a\n", r.Profile)
	b.WriteString("  statically built SvelteKit frontend embedded in the compiled binary.\n")
	fmt.Fprintf(b, "- Generated or last upgraded by nise CLI version `%s`.\n", r.CLIVersion)
	fmt.Fprintf(b, "- Targets Nise runtime package version `%s`.\n", r.RuntimeVersion)
	b.WriteString("- Selected modules: " + moduleList(r) + ".\n\n")
}

// moduleList renders r's selected modules as a sorted, comma-separated
// list, or "none" when it selected none. recipe.Modules() is already
// sorted, so the filtered result stays sorted without an extra sort call —
// sort.Strings is still applied defensively so this function's determinism
// does not silently depend on recipe.Modules() staying sorted forever.
func moduleList(r recipe.Recipe) string {
	var selected []string
	for _, m := range recipe.Modules() {
		if r.HasModule(m) {
			selected = append(selected, string(m))
		}
	}
	if len(selected) == 0 {
		return "none"
	}
	sort.Strings(selected)
	return strings.Join(selected, ", ")
}

func writeLayoutSection(b *strings.Builder) {
	b.WriteString("## Directory layout and ownership\n\n")
	b.WriteString("`app` means the application owns the directory: nise writes it once (or\n")
	b.WriteString("not at all) and never overwrites your edits there. `nise` means nise owns\n")
	b.WriteString("it: it is regenerated, and hand edits are lost.\n\n")
	b.WriteString("| Path | Owner | Notes |\n")
	b.WriteString("|---|---|---|\n")
	for _, d := range layoutDirectories() {
		fmt.Fprintf(b, "| `%s` | %s | %s |\n", d.Path, d.Ownership, d.Description)
	}
	b.WriteString("\nOwnership is also readable from the path, wherever it appears: the\n")
	b.WriteString("directory names `store/`, `openapigen/`, and `embedded/`, and any file\n")
	b.WriteString("ending `.gen.go`, are always regenerated Nise output. The same layout,\n")
	b.WriteString("with the full rationale, is documented at [Generated application\n")
	b.WriteString("layout](" + niseRepoBlobURL + "/docs/generated-application-layout.md).\n\n")
	b.WriteString("The machine-readable form of this same table, plus this project's module\n")
	b.WriteString("selection, is `.nise/architecture.json` (schema version " +
		fmt.Sprintf("%d", ArchitectureSchemaVersion) + "), alongside this file.\n\n")
}

func writeOwnershipSection(b *strings.Builder) {
	b.WriteString("## Files you must not hand-edit\n\n")
	b.WriteString("These carry the `Code generated by nise; DO NOT EDIT.` header (or, for a\n")
	b.WriteString("JSON file, a `generated` field saying the same thing) and are overwritten\n")
	b.WriteString("on every regeneration:\n\n")
	items := []string{
		"`AGENTS.md` and `.nise/architecture.json` — this file and its machine-readable sibling",
		"`nise.json` — the project recipe",
		"`internal/app/modules.gen.go`",
		"`internal/platform/httpapi/openapigen/**`",
		"`internal/features/<feature>/store/**`",
		"`internal/platform/webui/embedded/client/**` — build output; not committed",
		"`frontend/src/lib/api/schema.d.ts`",
	}
	for _, item := range items {
		b.WriteString("- " + item + "\n")
	}
	b.WriteString("\n")
}

func writeCommandsSection(b *strings.Builder) {
	b.WriteString("## Build, test, and lint\n\n")
	b.WriteString("`frontend/` sits inside this Go module, so a bare `./...` also walks\n")
	b.WriteString("`frontend/node_modules/`. Name the Go targets explicitly instead:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("go build ./cmd/... ./db/... ./internal/...\n")
	b.WriteString("go test ./cmd/... ./db/... ./internal/...\n")
	b.WriteString("go vet ./cmd/... ./db/... ./internal/...\n")
	b.WriteString("gofmt -l cmd db internal\n")
	b.WriteString("```\n\n")
	b.WriteString("`db/` contains `db/embed.gen.go` and the source/embed parity test, so the\n")
	b.WriteString("Makefile, `nise test`, and this list all include it.\n\n")
	b.WriteString("Database schema operations are explicit and use the generated application's\n")
	b.WriteString("embedded migrations:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("nise db status\n")
	b.WriteString("nise db migrate\n")
	b.WriteString("```\n\n")
	b.WriteString("PostgreSQL integration tests use `internal/platform/database/dbtest` and\n")
	b.WriteString("create one database per test. Set `TEST_DATABASE_URL` to an administrative\n")
	b.WriteString("database on a disposable server; absence skips locally and fails in CI. Run\n")
	b.WriteString("`make migration-test` to gate clean installs and supported release upgrades.\n\n")
	b.WriteString("Feature-local SQL checks are explicit and offline:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("make sqlc-compile\n")
	b.WriteString("make sqlc-vet\n")
	b.WriteString("make sqlc-generate\n")
	b.WriteString("```\n\n")
	b.WriteString("Frontend:\n\n")
	b.WriteString("```sh\n")
	b.WriteString("pnpm --dir frontend install\n")
	b.WriteString("pnpm --dir frontend check\n")
	b.WriteString("pnpm --dir frontend build\n")
	b.WriteString("```\n\n")
}

func writeConventionsSection(b *strings.Builder) {
	b.WriteString("## Non-negotiable conventions\n\n")
	conventions := []string{
		"Svelte components use Svelte 5 runes (`$state`, `$derived`, `$effect`) only — no Svelte 4 reactive statements (`$:`) and no store-as-primary-state.",
		"A use case owns its transaction boundary through the explicit transactor and passes the callback's `pgx.Tx` to `store.New(tx)`. Propagate the callback context; nested runners are rejected. Handlers and repositories never begin business transactions.",
		"Direct pgx is a reviewed exception for operations sqlc cannot model. Keep a narrow adapter in the owning feature, construct it from the use case's callback `pgx.Tx`, and use only required tracer-covered methods with static SQL and identifiers plus bound values. Never add a shared raw repository.",
		"Authorization defaults to deny. A missing or unevaluated permission check is a bug, not an implicit allow.",
		"Input decoding is strict: an unknown field or a type mismatch is rejected, not ignored.",
		"No new dependency is added to `go.mod` or `frontend/package.json` without a documented, concrete reason.",
	}
	for _, c := range conventions {
		b.WriteString("- " + c + "\n")
	}
	b.WriteString("\n")
}

func writeDocsSection(b *strings.Builder) {
	b.WriteString("## Where the authoritative docs live\n\n")
	b.WriteString("This project was generated by [Nise & Go](" + niseRepoURL + "). Its own\n")
	b.WriteString("`docs/` directory is the authoritative reference for this layout, its\n")
	b.WriteString("conventions, and its constraints, in particular:\n\n")
	docs := []string{
		"docs/generated-application-layout.md",
		"docs/direct-pgx.md",
		"docs/adr/0009-generated-application-layout.md",
		"docs/adr/0003-application-ownership.md",
		"docs/adr/0010-project-recipe-format.md",
	}
	for _, d := range docs {
		b.WriteString("- [" + d + "](" + niseRepoBlobURL + "/" + d + ")\n")
	}
	b.WriteString("\n`nise.json` in this project's root records the exact profile and module\n")
	b.WriteString("selection this document was generated from.\n")
}
