package agentsfile

import "github.com/drilonrecica/nise-and-go/internal/recipe"

// ArchitectureSchemaVersion is the schema version of .nise/architecture.json
// this package writes and understands. Bump it, and document the change
// here, whenever a field's meaning, type, or presence changes in a way a
// consumer must account for; adding a purely additive optional field does
// not require a bump.
const ArchitectureSchemaVersion = 1

// ArchitectureGeneratedMarker is ArchitectureMap.Generated's fixed value.
// JSON has no comment syntax, so the ownership header
// docs/generated-application-layout.md defines for a [nise]-owned file is
// carried as a field instead — the same accommodation ADR 0009 makes for
// nise.json.
const ArchitectureGeneratedMarker = "Code generated by nise; DO NOT EDIT."

// Ownership values for ArchitectureDirectory.Ownership, matching
// docs/generated-application-layout.md's two ownership markers.
const (
	OwnershipNise = "nise"
	OwnershipApp  = "app"
)

// ArchitectureMap is the top-level shape of .nise/architecture.json: a
// deterministic, versioned description of a generated Nise project's
// directory layout and module selection, for an external coding tool to
// read without invoking nise or parsing AGENTS.md's prose.
type ArchitectureMap struct {
	// SchemaVersion is ArchitectureSchemaVersion at the time this document
	// was written.
	SchemaVersion int `json:"schemaVersion"`
	// Generated is always ArchitectureGeneratedMarker; see that constant's
	// doc comment for why this is a field rather than a comment.
	Generated string `json:"generated"`
	// ContentHash is "sha256:" followed by the hex digest of this document
	// with ContentHash itself set to "". Write uses it to detect a hand
	// edit: a document that no longer verifies is never silently
	// overwritten. See hash.go.
	ContentHash string `json:"contentHash"`
	// Profile is the recipe's generation profile (recipe.Recipe.Profile).
	Profile string `json:"profile"`
	// Modules lists every compile-time module this build of nise knows
	// about (recipe.Modules(), already sorted), each flagged with whether
	// this project's recipe selected it.
	Modules []ArchitectureModule `json:"modules"`
	// Directories describes the generated tree's second-level directories
	// and their ownership, mirroring
	// docs/generated-application-layout.md's Tree section. It does not
	// enumerate every file; ownership readable from a path pattern (a
	// directory named store/, openapigen/, or embedded/, or a file ending
	// .gen.go) is documented once in AGENTS.md rather than repeated here
	// per file.
	Directories []ArchitectureDirectory `json:"directories"`
	// Features lists the project's vertical-slice features under
	// internal/features/. It is empty for a project that has not yet had
	// any feature generated or hand-written — Slice 1 leaves
	// internal/features/ holding only a .gitkeep
	// (docs/generated-application-layout.md, "What Slice 1 generates") —
	// and is populated by a future nise generate/nise new as features are
	// added. The field is never omitted, so a consumer can always read
	// its length without a presence check.
	Features []ArchitectureFeature `json:"features"`
}

// ArchitectureModule is one entry of ArchitectureMap.Modules.
type ArchitectureModule struct {
	// Name is the module's recipe name, e.g. "organizations".
	Name string `json:"name"`
	// Selected reports whether the project's recipe selected this module.
	Selected bool `json:"selected"`
}

// ArchitectureDirectory is one entry of ArchitectureMap.Directories.
type ArchitectureDirectory struct {
	// Path is the directory's path from the project root, using "/" and a
	// trailing slash (e.g. "internal/platform/webui/").
	Path string `json:"path"`
	// Ownership is OwnershipNise or OwnershipApp. Some directories (noted
	// in Description) hold a mix, in which case Ownership names the
	// predominant owner and Description names the exception.
	Ownership string `json:"ownership"`
	// Description is a one-line, human-and-machine-readable note on what
	// the directory holds and, for a mixed directory, which part is
	// Nise-owned.
	Description string `json:"description"`
}

// ArchitectureFeature is one entry of ArchitectureMap.Features.
type ArchitectureFeature struct {
	// Name is the feature's directory name under internal/features/, e.g.
	// "invoice".
	Name string `json:"name"`
	// Path is the feature's directory path from the project root.
	Path string `json:"path"`
}

// layoutDirectories is the fixed, hand-maintained mirror of
// docs/generated-application-layout.md's Tree section this package treats
// as its single source of truth for "directory layout with ownership per
// directory" — buildAgentsMDBody's Markdown table and buildArchitecture's
// JSON Directories field are both built from this one slice, so the two
// generated documents can never drift apart from each other (only from
// the hand-maintained page itself, if that page changes without this
// slice being updated to match). It is written in the path order the
// layout page itself uses, top to bottom, which is already lexical.
func layoutDirectories() []ArchitectureDirectory {
	return []ArchitectureDirectory{
		{Path: "api/", Ownership: OwnershipApp,
			Description: "The authoritative OpenAPI document (api/openapi.yaml); hand-edited from generation onward."},
		{Path: "cmd/<app>/", Ownership: OwnershipApp,
			Description: "Application entry point: flag parsing and process-mode selection, calling internal/app."},
		{Path: "db/", Ownership: OwnershipNise,
			Description: "db/embed.gen.go embeds db/migrations/*.sql into the binary."},
		{Path: "db/migrations/", Ownership: OwnershipApp,
			Description: "Sequential, hand-written SQL migrations, NNNNN_snake_case.sql."},
		{Path: "deploy/", Ownership: OwnershipApp,
			Description: "Dockerfile, local compose file, and deployment notes."},
		{Path: "frontend/", Ownership: OwnershipApp,
			Description: "SvelteKit project; contains no Go files. frontend/src/lib/api/schema.d.ts is the one Nise-owned file in this tree, regenerated from api/openapi.yaml."},
		{Path: "internal/app/", Ownership: OwnershipApp,
			Description: "Explicit constructor wiring and process-mode selection; internal/app/modules.gen.go is Nise-owned and regenerated as the module selection changes."},
		{Path: "internal/features/", Ownership: OwnershipApp,
			Description: "One vertical slice per feature: domain rules, use cases, handlers, SQL, and tests. Each feature's store/ subdirectory is Nise-owned sqlc output."},
		{Path: "internal/platform/config/", Ownership: OwnershipApp,
			Description: "Typed configuration built over runtime/config."},
		{Path: "internal/platform/database/", Ownership: OwnershipApp,
			Description: "pgxpool setup and the Goose migration runner."},
		{Path: "internal/platform/httpapi/", Ownership: OwnershipApp,
			Description: "Router and middleware order; internal/platform/httpapi/openapigen/ is Nise-owned oapi-codegen output."},
		{Path: "internal/platform/jobs/", Ownership: OwnershipApp,
			Description: "The River job runner, its queues, and their registration. A job's payload and business rules belong to the feature that enqueues it."},
		{Path: "internal/platform/mail/", Ownership: OwnershipApp,
			Description: "The mail interface, SMTP transport, and templates. A message's content belongs to the feature that sends it."},
		{Path: "internal/platform/webui/", Ownership: OwnershipNise,
			Description: "Embeds the built frontend and serves the SPA; internal/platform/webui/embedded/client/ is pnpm build output and is not committed."},
	}
}

// buildArchitecture derives an ArchitectureMap from r. It never sets
// ContentHash; the caller (Generate, via wrapArchitecture) computes that
// from the finished document.
func buildArchitecture(r recipe.Recipe) ArchitectureMap {
	modules := make([]ArchitectureModule, 0, len(recipe.Modules()))
	for _, m := range recipe.Modules() {
		modules = append(modules, ArchitectureModule{Name: string(m), Selected: r.HasModule(m)})
	}

	return ArchitectureMap{
		SchemaVersion: ArchitectureSchemaVersion,
		Generated:     ArchitectureGeneratedMarker,
		Profile:       string(r.Profile),
		Modules:       modules,
		Directories:   layoutDirectories(),
		Features:      []ArchitectureFeature{},
	}
}
