package agentsfile

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"strings"
)

// Decision: content hash embedded in the file's own header/field, not a
// separate sidecar. A sidecar (e.g. a ".nise/generated.sha256" manifest)
// can be deleted, moved, or left stale independently of the files it
// describes, silently disabling the refusal-to-overwrite check without
// anyone editing the protected file at all. Embedding the hash makes each
// generated file self-verifying: the one artifact that must exist for the
// check to run is the same artifact the check protects.

// markdownHeaderLine1 is the ownership marker
// docs/generated-application-layout.md's "Ownership markers" section
// defines for a [nise]-owned file, spelled as an HTML comment so it
// renders invisibly wherever AGENTS.md is viewed as Markdown.
const markdownHeaderLine1 = "<!-- Code generated by nise; DO NOT EDIT. -->"

const (
	markdownHashPrefix = "<!-- nise-content-sha256: "
	markdownHashSuffix = " -->"
)

// wrapMarkdown prepends the ownership header and a content hash to body,
// producing the exact bytes Write puts on disk. The hash covers body only
// (never the header lines themselves, which would make the hash depend on
// its own encoded form) so verifyMarkdown can recompute it from any file
// claiming to be this one.
func wrapMarkdown(body []byte) []byte {
	sum := sha256.Sum256(body)
	var b strings.Builder
	b.WriteString(markdownHeaderLine1)
	b.WriteByte('\n')
	b.WriteString(markdownHashPrefix)
	b.WriteString(hex.EncodeToString(sum[:]))
	b.WriteString(markdownHashSuffix)
	b.WriteString("\n\n")
	b.Write(body)
	return []byte(b.String())
}

// verifyMarkdown reports whether data is self-consistent: its first two
// lines are the exact header and hash-comment forms wrapMarkdown produces,
// and the declared hash matches a fresh hash of everything after the
// blank line that follows them. A file that fails this — because a human
// edited its body without recomputing the comment, replaced it outright,
// or it was never generated by nise at all — must not be silently
// overwritten.
func verifyMarkdown(data []byte) bool {
	parts := strings.SplitN(string(data), "\n", 3)
	if len(parts) != 3 {
		return false
	}
	header, hashLine, rest := parts[0], parts[1], parts[2]
	if header != markdownHeaderLine1 {
		return false
	}
	if !strings.HasPrefix(hashLine, markdownHashPrefix) || !strings.HasSuffix(hashLine, markdownHashSuffix) {
		return false
	}
	declared := strings.TrimSuffix(strings.TrimPrefix(hashLine, markdownHashPrefix), markdownHashSuffix)
	body := strings.TrimPrefix(rest, "\n") // the blank line separating the header from the body
	sum := sha256.Sum256([]byte(body))
	return hex.EncodeToString(sum[:]) == declared
}

// architectureHashPrefix is prepended to the hex digest recorded in
// ArchitectureMap.ContentHash, so the field self-describes its own
// algorithm the way a URI scheme would (e.g. "sha256:abcd...").
const architectureHashPrefix = "sha256:"

// canonicalArchitectureBytes encodes m with ContentHash cleared, two-space
// indented and without HTML-escaping, for both computing and verifying
// its content hash. Encoding is entirely determined by ArchitectureMap's
// own field order and json tags — never by map iteration or any other
// non-deterministic source — so two calls with an equal m always produce
// equal bytes.
func canonicalArchitectureBytes(m ArchitectureMap) ([]byte, error) {
	m.ContentHash = ""
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(m); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// wrapArchitecture returns m encoded with ContentHash set to the hash of
// its own canonical form (computed with ContentHash empty).
func wrapArchitecture(m ArchitectureMap) ([]byte, error) {
	canonical, err := canonicalArchitectureBytes(m)
	if err != nil {
		return nil, err
	}
	sum := sha256.Sum256(canonical)
	m.ContentHash = architectureHashPrefix + hex.EncodeToString(sum[:])
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetEscapeHTML(false)
	enc.SetIndent("", "  ")
	if err := enc.Encode(m); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// verifyArchitecture reports whether data decodes as an ArchitectureMap
// whose declared ContentHash matches a fresh hash of its own canonical
// form. Field reordering that changes no value still verifies (JSON
// object key order carries no meaning); any changed, added, or removed
// value does not, because it changes canonicalArchitectureBytes' output.
func verifyArchitecture(data []byte) bool {
	var m ArchitectureMap
	if err := json.Unmarshal(data, &m); err != nil {
		return false
	}
	declared := m.ContentHash
	if declared == "" {
		return false
	}
	canonical, err := canonicalArchitectureBytes(m)
	if err != nil {
		return false
	}
	sum := sha256.Sum256(canonical)
	want := architectureHashPrefix + hex.EncodeToString(sum[:])
	return declared == want
}
