package agentsfile

import "testing"

func TestVerifyMarkdownRoundTrips(t *testing.T) {
	t.Parallel()
	body := []byte("# Title\n\nSome content.\n")
	wrapped := wrapMarkdown(body)
	if !verifyMarkdown(wrapped) {
		t.Error("verifyMarkdown rejected wrapMarkdown's own output")
	}
}

func TestVerifyMarkdownRejectsForeignContent(t *testing.T) {
	t.Parallel()
	cases := map[string][]byte{
		"empty":                []byte(""),
		"plain text":           []byte("just some text, not generated by nise at all"),
		"missing hash comment": []byte(markdownHeaderLine1 + "\n\nbody\n"),
		"wrong header":         []byte("<!-- something else -->\n" + markdownHashPrefix + "abc" + markdownHashSuffix + "\n\nbody\n"),
		"tampered body":        append(wrapMarkdown([]byte("original")), []byte("tampered")...),
		"tampered hash":        []byte(markdownHeaderLine1 + "\n" + markdownHashPrefix + "0000000000000000000000000000000000000000000000000000000000000000" + markdownHashSuffix + "\n\nbody\n"),
	}
	for name, data := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if verifyMarkdown(data) {
				t.Errorf("verifyMarkdown accepted %q content", name)
			}
		})
	}
}

func TestVerifyArchitectureRoundTrips(t *testing.T) {
	t.Parallel()
	m := ArchitectureMap{
		SchemaVersion: ArchitectureSchemaVersion,
		Generated:     ArchitectureGeneratedMarker,
		Profile:       "go-chi-postgres-svelte",
		Modules:       []ArchitectureModule{{Name: "totp", Selected: true}},
		Directories:   []ArchitectureDirectory{{Path: "api/", Ownership: OwnershipApp, Description: "d"}},
		Features:      []ArchitectureFeature{},
	}
	data, err := wrapArchitecture(m)
	if err != nil {
		t.Fatalf("wrapArchitecture: %v", err)
	}
	if !verifyArchitecture(data) {
		t.Errorf("verifyArchitecture rejected wrapArchitecture's own output:\n%s", data)
	}
}

func TestVerifyArchitectureRejectsForeignOrTamperedContent(t *testing.T) {
	t.Parallel()
	cases := map[string]string{
		"empty":               "",
		"not json":            "not json at all",
		"missing contentHash": `{"schemaVersion":1,"generated":"Code generated by nise; DO NOT EDIT.","profile":"p","modules":[],"directories":[],"features":[]}`,
		"tampered value":      `{"schemaVersion":1,"generated":"Code generated by nise; DO NOT EDIT.","contentHash":"sha256:0000000000000000000000000000000000000000000000000000000000000000","profile":"tampered","modules":[],"directories":[],"features":[]}`,
	}
	for name, data := range cases {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if verifyArchitecture([]byte(data)) {
				t.Errorf("verifyArchitecture accepted %q content", name)
			}
		})
	}
}

func TestVerifyArchitectureIgnoresKeyReorderingOnly(t *testing.T) {
	t.Parallel()
	m := ArchitectureMap{
		SchemaVersion: 1,
		Generated:     ArchitectureGeneratedMarker,
		Profile:       "p",
		Modules:       []ArchitectureModule{},
		Directories:   []ArchitectureDirectory{},
		Features:      []ArchitectureFeature{},
	}
	data, err := wrapArchitecture(m)
	if err != nil {
		t.Fatal(err)
	}
	// verifyArchitecture decodes into the Go struct and re-encodes in the
	// struct's own fixed field order, so key order in the on-disk bytes is
	// not itself part of what is verified — only the values are. This
	// documents that intentional tradeoff (see verifyArchitecture's doc
	// comment) rather than leaving it as an unstated assumption.
	if !verifyArchitecture(data) {
		t.Fatal("sanity check: wrapArchitecture's own output must verify")
	}
}
